/* eslint-disable no-irregular-whitespace */
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-nocheck
import { LOCALE } from '../locales'

/** Hero lore/description text - split out of regular.ts and dynamically imported
 * (see getHeroDescriptionLocale in lang/lang.ts) so it isn't part of the
 * always-loaded locale bundle. Mirrors hero_talents.ts's lazy-load pattern. */
const hero_description_data: { [key in LOCALE]?: { [key in string]: string } } = {
  [LOCALE.UNK_DESCRIPTION]: {
    en: 'Will be added soon!',
    ru: 'Скоро будет добавлено!',
    br: 'Será adicionado em breve!',
    cz: 'Brzy bude přidáno!',
    zh: '即將加入，敬請期待！',
    fr: 'Sera bientôt ajouté!',
    id: 'Akan segera ditambahkan!',
    vi: 'Sẽ được thêm vào sớm thôi!',
    kr: `곧 추가될 예정입니다!`,
  },
  [LOCALE.KUMIHU_DESCRIPTION]: {
    en: 'Kumihu is an evil spirit in the guise of a beautiful woman who is always hungry for new souls. But be careful: in the blink of an eye she can show her true form, destroying any chance to survive, since the Soul Sphere will catch even the most tenacious fools.',
    ru: 'Кумиху - злой дух, принявший облик прекрасной женщины, жаждущий новых душ. Но будьте осторожны: в мгновение ока она может показать свою истинную форму, уничтожив любой шанс на выживание, поскольку Сфера души поймает даже самых упорных дураков.',
    br: 'Um demonio da floresta que foi capturado pelo reino vemelho, Kumihu conseguiu fugir roubando o corpo de uma duqueza para se vingar das pessoas que a fizeram mal.',
    cz: 'Kumihu je zlý duch v převleku krásné ženy, která neustále touží po nových duších. Ale buďte opatrní: mrknutím oka může ukázat svou pravou podobu a zničit jakoukoli šanci na přežití, protože její sféra duše zachytí i ti nejhouževnatější blázni.',
    zh: '　　庫咪戶是一個偽裝成貌美女性的惡靈，總是渴求著新鮮的靈魂。萬分注意：一旦被靈魂球體逮到，只需眨眼之間，她就能現出真實面目將任何一絲存活的機會通通摧毀，縱使是最頑強的愚者也不例外。',
    fr: "Kumihu est un esprit maléfique se faisant passer pour une belle femme qui a toujours faim de nouvelles âmes. Mais attention : en un clin d'œil, elle peut montrer sa véritable forme, détruisant ainsi toute chance de survie, car la Sphère d'âme attrapera même les plus tenaces des fous.",
    id: 'Kumihu adalah roh jahat yang menyamar sebagai wanita cantik yang selalu lapar akan jiwa baru. Tapi hati-hati: dalam sekejap mata, dia bisa menunjukkan wujud aslinya, menghancurkan setiap kesempatan untuk bertahan hidup, karena Bola Jiwa akan menangkap bahkan orang bodoh yang paling gigih.',
    vi: 'Kumihu là một tinh linh ác quỷ dưới hình dạng một người phụ nữ xinh đẹp, luôn khao khát những linh hồn mới. Nhưng hãy cẩn thận: chỉ trong nháy mắt, cô ta có thể hiện ra hình dạng thật của mình, phá hủy mọi cơ hội sống sót, vì Quả cầu Linh hồn sẽ bắt được ngay cả những kẻ kiên trì ngu ngốc nhất.',
    kr: `쿠미후는 아름다운 여인의 모습을 한 악령으로, 언제나 새로운 영혼에 굶주려 있다. 하지만 조심해야 한다. 그녀는 눈 깜짝할 사이에 본모습을 드러낼 수 있으며, 그녀의 영혼 구슬은 아무리 끈질긴 자라도 결국 사로잡아 생존의 기회를 완전히 앗아가 버린다.`,
  },
  [LOCALE.ICEAT_DESCRIPTION]: {
    en: "Belonging to a colony of penguins in the arctic region of Civia, I'ceat stood out among the rest. Possessing magical powers, I'ceat can manifest ice and snow at the tip of his flippers. No one knows where his powers came from, but everyone embraces his uniqueness among the group. Waddling past the tall trees in the dense forest, I'ceat is determined to find the true meaning behind the powers he once used to protect his family.",
    ru: "Принадлежащий к колонии пингвинов в арктическом регионе Кливии, Ай'сит выделялся среди остальных. Обладая магическими способностями, Ай'сит может создавать лёд и снег на кончиках ласт. Никто не знает, откуда взялись его силы, но все в группе принимают его уникальность. Пробираясь мимо высоких деревьев в густом лесу, Ай'сит наполнен решимостью разыскать истинный смысл своих сил, которые он когда-то использовал для защиты своей семьи.",
    br: "Pertencente a uma colônia de pinguins na região ártica de Civia, I'ceat se destacou entre os demais. Possuindo poderes mágicos que apenas demônios tem, I'ceat pode manifestar pedras de gelo e neve da ponta de suas nadadeiras. Ninguém sabe de onde veio seus poderes, mas todos o aceitam no grupo acreditando não ter ligação com os demônios. Passando pelas árvores altas da floresta das fadas, I'ceat está determinado a encontrar o verdadeiro significado por trás dos poderes que ele usou para proteger sua colônia.",
    cz: "I'ceat patřil ke kolonii tučňáků v arktické oblasti Civia, ale vždy vyčníval mezi ostatními. Díky magickým schopnostem dokáže I'ceat vztvořit led a sníh na špičce svých křidel. Nikdo neví, kde se jeho schopnosti vzaly , ale každý přijímá jeho jedinečnost ve kmenu. Kolébájíc se kolem vysokých stromů v hustém lese je I'ceat odhodlán najít skutečný význam za schopnostmi, které kdysi používal k ochraně své rodiny.",
    zh: '　　隸屬於北極地帶希維亞的企鵝群，艾希特在企鵝群中脫穎而出。擁有魔法之力，艾希特可以在他的腳蹼間現出冰雪。沒人知曉他的能力從何而來，但大家都接納他在群體中的獨特性。搖搖擺擺地走過了重重的高樹茂林，艾希特下定了決心，去尋找他那曾經用來保護整個家族的力量其背後的真實意涵。',
    fr: "Appartenant à une colonie de pingouins dans la région arctique de Civia, I'ceat se démarquait des autres. Possédant des pouvoirs magiques, I'ceat peut manifester de la glace et de la neige à l'extrémité de ses palmes. Personne ne sait d'où viennent ses pouvoirs, mais tout le monde accepte son unicité au sein du groupe. En se dandinant devant les grands arbres de la forêt dense, I'ceat est déterminé à trouver la véritable signification derrière les pouvoirs qu'il utilisait autrefois pour protéger sa famille.",
    id: "Bergabung dengan koloni penguin di wilayah arktik Civia, I'ceat menonjol di antara yang lain. Memiliki kekuatan magis, I'ceat dapat memanifestasikan es dan salju di ujung siripnya. Tidak ada yang tahu dari mana kekuatannya berasal, tetapi semua orang menerima keunikannya di antara kelompok. Berjalan goyang melewati pohon-pohon tinggi di hutan lebat, I'ceat bertekad untuk menemukan makna sebenarnya di balik kekuatan yang pernah digunakannya untuk melindungi keluarganya.",
    vi: "Thuộc về một chủng tộc chim cánh cụt ở vùng Bắc Cực Civia, I'ceat nổi bật hơn những con khác. Sở hữu sức mạnh ma thuật, I'ceat có thể hiện ra băng và tuyết ở đầu vây của mình. Không ai biết sức mạnh của anh đến từ đâu, nhưng mọi người đều chấp nhận sự độc đáo của anh trong nhóm. Lạch bạch đi qua những cây cao trong rừng rậm, I'ceat quyết tâm tìm ra ý nghĩa thực sự đằng sau sức mạnh mà anh đã từng sử dụng để bảo vệ gia đình mình.",
    kr: `시비아의 극지방에 사는 펭귄 무리 출신인 아이싯은 다른 개체들과는 확연히 달랐다. 마법의 힘을 지닌 아이싯은 지느러미 끝에서 얼음과 눈을 만들어낼 수 있다. 그 힘이 어디서 비롯되었는지는 아무도 모르지만, 무리의 모두는 그의 특별함을 있는 그대로 받아들였다. 울창한 숲의 높은 나무들 사이를 뒤뚱거리며 걸어가는 아이싯은, 한때 가족을 지키기 위해 사용했던 그 힘에 담긴 진정한 의미를 찾아 나서기로 결심한다.`,
  },
  [LOCALE.THOMAS_DESCRIPTION]: {
    en: "Coming from an underground laboratory in the heated war zone of Rotite, Thomas fought for Etygia's guerilla force and partook in ambushes focused on the upper ranks of the enemy forces. He gained notoriety among allies and foes alike because of his unique style of killing. During a secret experiment gone wrong, the test subject blasted the laboratory wide open. Wanting to leave the hectic environment and hellish landscape, Thomas dared to leave the guerilla force for good. Through the spray of bullets, he managed to swiftly make it past as he witnessed the loss of many lives in the chaos. For Thomas, he wanted freedom, but at the cost of betraying the kingdom. Keeping a low profile and lurking in the shadows, it's only a matter of time. The hunter has become the hunted.",
    ru: 'Выйдя из подземной лаборатории в жаркой зоне боевых действий Ротита, Томас сражался на стороне партизан Этигии и участвовал в засадах, сосредоточенных на верхних званиях вражеских сил. Он получил известность как среди союзников, так и среди врагов из-за своего уникального стиля убийств. Во время секретного эксперимента, который закончился неудачей, испытуемый полностью взорвал лабораторию. Желая покинуть суету и адские пейзажи, Томас осмелился навсегда покинуть партизанские отряды. Ему удалось быстро миновать осколки пуль, становясь свидетелем гибели многих людей в происходящем хаосе. Томас просто хотел свободы, даже ценой предательства целого королевства. Незаметность и скрытность в тени - это лишь вопрос времени. Охотник превратился в добычу.',
    br: 'Vindo de um laboratório subterrâneo na zona de guerra aquecida de Rotite, Thomas foi obrigado a lutar pelas forças de guerrilha de Etygia e sua especialidade era de emboscadas focadas nas fileiras superiores das forças inimigas. Ele ganhou notoriedade entre aliados e inimigos por causa de seu estilo único de luta com uma espada demoníaca. Durante um experimento secreto que deu errado, uma das cobaias explodiu um laboratório subterrâneo perto de onde ele patrulhava. Ele testemunhou a perda de muitas vidas no caos. Thomas aproveitou a oportunidade e se atreveu a deixar as forças de guerrilha, mas ao custo de trair o reino e virar um fugitivo.',
    cz: 'Tomáš, králík pocházející z podzemní laboratoře ve válečné zóně Rotite, bojoval za partyzánské síly Etygie a účastnil se přepadení zaměřených na vyšší řady nepřátelských sil. Díky svému jedinečnému stylu zabíjení si získal proslulost mezi spojenci i nepřáteli. Během tajného experimentu, který se pokazil, testovaný subjekt znicil laboratoř. Thomas chtěl opustit hektické prostředí a pekelnou krajinu a odvážil se navždy opustit partyzány. Přes spršku kulek se mu podařilo rychle uniknout, když byl svědkem ztráty mnoha životů v chaosu. Bunninju chtěl svobodu, ale za cenu zrady království. Držejic se nízko a číhat ve stínu, je to jen otázka času. Z lovce se stal lovený.',
    zh: '　　來自洛泰特激烈戰區的地下實驗室，湯瑪士作為艾提吉亞的游擊隊勢力一員作戰，並專門伏擊敵方勢力的高級階層。他因為其獨特的殺戮風格，在敵友之間皆惡名昭彰。在某一次機密實驗出錯時，受試者爆裂將實驗室炸毀了。渴望著離開這奔波不斷的環境以及猶如地獄般的光景，湯瑪士毅然決然離開了游擊隊勢力。他設法迅速離開，穿越過了漫天四散的子彈，同時親眼目睹了許多性命被葬送在這場混亂當中。對湯瑪士而言，他想要自由，然而代價則是背叛了整個王國。要時時刻刻保持低調潛伏在影子中，一個獵殺者反成了獵物，只會是時間上的問題。',
    fr: "Venu d'un laboratoire souterrain dans la zone de guerre brûlante de Rotite, Thomas combattit pour la guérilla d'Etygia et participa à des embuscades visant les hauts rangs ennemis. Il devint célèbre auprès de ses alliés comme de ses ennemis grâce à son style de mise à mort unique. Après une expérience secrète qui tourna mal, il saisit l'occasion de quitter la guérilla, mais au prix de trahir le royaume. Discret et tapi dans l'ombre, il sait que ce n'est qu'une question de temps : le chasseur est devenu la proie.",
    id: 'Datang dari laboratorium bawah tanah di zona perang yang panas di Rotite, Thomas berjuang untuk pasukan gerilya Etygia dan ikut serta dalam penyergapan yang berfokus pada peringkat atas pasukan musuh. Dia mendapatkan ketenaran di antara sekutu dan musuh karena gaya pembunuhannya yang unik. Selama eksperimen rahasia yang salah, subjek percobaan meledakkan laboratorium itu. Ingin meninggalkan lingkungan yang kacau dan pemandangan yang mengerikan, Thomas berani meninggalkan pasukan gerilya untuk selamanya. Melalui hujan peluru, dia berhasil melintasi dengan cepat sambil menyaksikan hilangnya banyak nyawa dalam kekacauan. Bagi Thomas, dia menginginkan kebebasan, tetapi dengan biaya mengkhianati kerajaan. Menjaga profil rendah dan bersembunyi di bayang-bayang, hanya masalah waktu. Pemburu telah menjadi buruan.',
    vi: 'Xuất phát từ một phòng thí nghiệm ngầm trong khu vực chiến tranh nóng bỏng ở Rotite, Thomas đã chiến đấu cho lực lượng du kích của Etygia và tham gia vào các cuộc phục kích nhằm vào các cấp bậc cao của quân địch. Anh đã trở nên nổi tiếng giữa đồng minh và kẻ thù nhờ phong cách giết độc đáo của mình. Trong một thí nghiệm bí mật thất bại, đối tượng thử nghiệm đã làm nổ tung phòng thí nghiệm. Muốn rời khỏi môi trường hỗn loạn và cảnh quan địa ngục, Thomas đã dám rời bỏ lực lượng du kích mãi mãi. Qua làn đạn khói, anh đã nhanh chóng vượt qua khi chứng kiến sự mất mát của nhiều sinh mạng trong hỗn loạn. Đối với Thomas, anh muốn tự do, nhưng với cái giá phải phản bội vương quốc. Giữ một hình ảnh thấp và ẩn nấp trong bóng tối, chỉ là vấn đề thời gian. Thợ săn đã trở thành con mồi.',
    kr: `격전지 로타이트의 지하 실험실 출신인 토마스는 에티지아의 게릴라 부대를 위해 싸우며 적군 수뇌부를 노린 기습 작전에 참여했다. 독특한 살상 방식 때문에 그는 아군과 적군 모두에게 악명을 떨쳤다. 어느 비밀 실험이 잘못되어 실험체가 실험실을 통째로 날려버린 그날, 혼란스러운 환경과 지옥 같은 풍경을 벗어나고자 했던 토마스는 마침내 게릴라 부대를 영영 떠나기로 결심했다. 빗발치는 총탄 속에서도 그는 재빨리 그곳을 빠져나갔고, 그 혼돈 속에서 수많은 목숨이 스러지는 모습을 목격했다. 토마스가 원한 것은 오직 자유뿐이었지만, 그 대가는 왕국을 배신하는 것이었다. 몸을 낮추고 그림자 속에 숨어 지내는 지금, 남은 것은 시간문제일 뿐이다. 사냥꾼이 이제는 사냥감이 되었다.`,
  },
  [LOCALE.SPARROW_DESCRIPTION]: {
    en: `A courageous and fierce woman previously a Hermit, Sparrow committed most of her life following the demon Artuklas. She and her family lived in a village deep within the dense Sasugroen Rainforest. Her strong sense of adventure distinguished her from the timid and discreet natured children of her generation. Together with her family, they pursued the path that Artuklas set for the Hermits.
        <br />Artuklas, being akin to discovery and knowledge, was intrigued by the curious Sparrow and her bravery to venture out, seeking the unknown and discovering information. He slowly forged his path to cater to Sparrow's needs, dismissing the other Hermits who wanted to follow and worship him. Sparrow noticed the changes, but Artuklas assured her that destiny chose this path for her to take. During the following years of training and preparing, the bond between the hermit and demon grew closer, and Artuklas divulged information about his kin to Sparrow.
        <br />Unfortunately, even with the training and rituals all complimenting Sparrow's strengths, the child could not fully grasp the power Artuklas extends to share. Artuklas, growing impatient and infuriated at the child's incompetency, decided to force a fraction of his power to flow through her body. This power would prove too much for Sparrow, and she would have to expel a lot of this to stay conscious.
        <br />A small scouting team of Guardians would take notice of the immense demonic energy concentrated in one spot. Upon arrival, they would see the shape of a greater demon trying to take control of a collapsed woman. They seized the opportunity to strike, but Sparrow retaliated, allowing Artuklas to escape in the chaos. After a long-drawn-out fight, the Guardians would subdue and overpower her because she could not effectively use her newfound abilities.`,
    ru: `Спарроу - смелая и свирепая девушка, в прошлом отшельник, большую часть своей жизни посвятившая следованию демону Артукласу. Она и ее семья жили в деревне глубоко в густом тропическом лесу Сасугроен. Её сильное стремление к приключениям отличало её от робких и сдержанных детей её возраста. Вместе с её семьей они пошли по пути, который Артуклас указал отшельникам.
        <br />Артукласу были по душе открытия и новые знания, и он был очень заинтригован любопытной Спарроу и ее храбростью, когда она отправлялась на поиски неизвестного. Он медленно прокладывал свой путь, чтобы удовлетворить потребности Спарроу, увольняя других отшельников, которые хотели следовать за ним и поклоняться ему. Спарроу замечала изменения, но Артуклас заверял, что сама судьба избрала для неё этот путь. В последующие годы обучения и подготовки связь между отшельницей и демоном стала теснее, и Артуклас выдал Спарроу информацию о своём с ней родстве.
        <br />К сожалению, даже с обучением и ритуалами, дополняющими сильные стороны Спарроу, ребёнок не мог полностью осознать силу, которой Артуклас делится. Артуклас, теряя терпение и гневаясь из-за некомпетентности ребёнка, решил заставить часть своей силы течь через её тело. Эта сила оказалась бы слишком большой для Спарроу, и ей пришлось бы исключить многое из этого, чтобы оставаться в сознании.
        <br />Небольшая разведывательная группа стражей вскоре заметит огромную демоническую энергию, сосредоточенную в одном месте. По прибытии они увидят очертания огромного демона, пытающегося взять под контроль лежащую в обмороке девушку. Они воспользовались возможностью нанести удар, но Спарроу контратаковала, позволив Артукласу сбежать в хаосе. После затяжной битвы стражи подавили и усмирили её пыл, поскольку она не могла эффективно использовать свои новообретённые способности.`,
    br: `Elizabeth Dolores Sperrow II, uma mulher corajosa e feroz do reino de Etygia, teve um casamento político com o Rei de Eilys Edgar III, com o tempo ela se apaixonou por ele mas tudo mudou depois que seu marido foi assassinado por um demônio da floresta.
        <br A Rainha de Eilys ficou sedenta por vingança, sem saber o motivo pelo qual seu marido foi assassinado, ela declarou guerra aos seres mágicos, agora ela luta na linha de frente para se vingar e descobrir a verdade.`,
    cz: `Sparrow, odvážná a prudká žena, bývala poustevnicí a většinu života zasvětila démonu Artuklasovi. Se svou rodinou žila hluboko v deštném lese Sasugroen a touha po objevování ji odlišovala od ostatních dětí.
        <br />Artuklas ji postupně vedl po vlastní cestě a sdílel s ní zlomek své moci. Síla však byla příliš velká a přitáhla pozornost Strážců. Po dlouhém boji ji přemohli, protože své nové schopnosti nedokázala plně ovládnout.`,
    zh: `　　曾經作為一名隱士，史佩羅勇敢而兇猛，過往一直追隨著惡魔阿圖克拉斯。她與她的家人住在薩蘇古隆恩熱帶雨林深處的一個村落，她那強大的冒險意識將她與她那一代膽小而謹慎的孩子們區分了開來。隨著她的家族一行，他們追隨著阿圖克拉斯替隱士們設下的道路。
        <br />　　阿圖克拉斯，近乎於探索與見聞，對於史佩羅勇敢冒險，尋求未知以及探索情報的好奇心感到興趣。他漸漸打造出一條專門迎合史佩羅需求的道路，將其他想要追隨崇拜他的隱士們通通遣送走。史佩羅注意到了這些變動，但阿圖克拉斯向她保證，是命運選擇了這條道路，迎接她的到來。在接下來這幾年來的訓練及準備中，隱士與惡魔的關係越來越緊密，而阿圖克拉斯則透漏與史佩羅結識為親屬關係的消息。
        <br />　　不幸的是，縱然在訓練與儀式當中史佩羅的力量一致受到大家讚揚，這個孩子依然無法完全掌握阿圖克拉斯共享給她的能量。阿圖克拉斯開始感到不耐煩，被孩子的無能給激怒了，決定將他一小部分份的能量強行灌輸到她的身體。這份能量對史佩羅來說太多了，她必須將大量的能量驅散才能保持意識清醒。
        <br />　　一組守衛者的小偵查隊注意到了匯集在一點的邪惡能量。到達之後，他們看到了一個更大的惡魔形體正在試圖操控一個已經倒下的女人。他們逮到了機會迎擊，但史佩羅展開了反擊，使得阿圖克拉斯在這場混亂當中逃脫而出。在一場曠日持久的戰鬥後，守衛隊制伏並打敗了她，因為她無法有效使用她那新發現的能力。`,
    fr: `Femme courageuse et féroce, autrefois ermite, Sparrow consacra une grande partie de sa vie au démon Artuklas. Elle vivait avec sa famille au cœur de la forêt tropicale de Sasugroen, et son goût de l'aventure la distinguait des enfants plus timides de sa génération.
        <br />Artuklas façonna peu à peu une voie faite pour elle et lui transmit une fraction de son pouvoir. Cette énergie était trop lourde à porter et attira les Gardiens. Après un long combat, ils la maîtrisèrent, car elle ne pouvait pas encore utiliser efficacement ses nouvelles capacités.`,
    id: `Seorang wanita yang berani dan garang, sebelumnya seorang Pertapa, Sparrow mengabdikan sebagian besar hidupnya mengikuti iblis Artuklas. Dia dan keluarganya tinggal di sebuah desa yang dalam di dalam Hutan Hujan Sasugroen yang lebat. Rasa petualang yang kuat membedakannya dari anak-anak generasinya yang pemalu dan tertutup. Bersama keluarganya, mereka mengejar jalan yang ditetapkan Artuklas untuk para Pertapa.
        <br />Artuklas, yang mirip dengan penemuan dan pengetahuan, tertarik pada Sparrow yang penasaran dan keberaniannya untuk menjelajah, mencari yang tidak diketahui dan menemukan informasi. Dia perlahan-lahan membentuk jalannya untuk memenuhi kebutuhan Sparrow, mengabaikan Pertapa lain yang ingin mengikuti dan menyembahnya. Sparrow menyadari perubahan tersebut, tetapi Artuklas meyakinkannya bahwa takdir memilih jalan ini untuknya. Selama tahun-tahun pelatihan dan persiapan berikutnya, ikatan antara pertapa dan iblis semakin dekat, dan Artuklas mengungkapkan informasi tentang kerabatnya kepada Sparrow.
        <br />Sayangnya, meskipun pelatihan dan ritual semua melengkapi kekuatan Sparrow, anak itu tidak dapat sepenuhnya memahami kekuatan yang ingin dibagikan Artuklas. Artuklas, yang semakin tidak sabar dan marah atas ketidakmampuan anak itu, memutuskan untuk memaksa sebagian kekuatannya mengalir melalui tubuhnya. Kekuatan ini akan terbukti terlalu banyak bagi Sparrow, dan dia harus mengeluarkan banyak dari ini untuk tetap sadar.
        <br />Sekelompok kecil tim pengintai Penjaga akan memperhatikan energi demonik yang sangat besar terkonsentrasi di satu tempat. Setibanya, mereka akan melihat sosok iblis yang lebih besar mencoba mengendalikan seorang wanita yang terjatuh. Mereka mengambil kesempatan untuk menyerang, tetapi Sparrow melawan, memungkinkan Artuklas melarikan diri dalam kekacauan. Setelah pertarungan yang berkepanjangan, Para Penjaga akan menaklukkan dan mengalahkannya karena dia tidak dapat menggunakan kemampuan barunya secara efektif.`,
    vi: `Một người phụ nữ dũng cảm và dữ dội, trước đây là một ẩn sĩ, Sparrow đã dành phần lớn cuộc đời mình để theo đuổi con quỷ Artuklas. Cô và gia đình sống trong một ngôi làng sâu trong rừng mưa Sasugroen dày đặc. Cảm giác phiêu lưu mạnh mẽ của cô đã phân biệt cô với những đứa trẻ nhút nhát và kín đáo trong thế hệ của mình. Cùng với gia đình, họ đã theo đuổi con đường mà Artuklas đã chỉ định cho các ẩn sĩ.
        <br />Artuklas, giống như khám phá và tri thức, đã bị cuốn hút bởi Sparrow tò mò và sự dũng cảm của cô khi dám ra ngoài, tìm kiếm điều chưa biết và khám phá thông tin. Anh từ từ tạo ra con đường của mình để đáp ứng nhu cầu của Sparrow, bỏ qua những ẩn sĩ khác muốn theo và thờ phượng anh. Sparrow nhận thấy những thay đổi, nhưng Artuklas đảm bảo với cô rằng số phận đã chọn con đường này cho cô. Trong những năm tiếp theo của việc đào tạo và chuẩn bị, mối liên kết giữa ẩn sĩ và quỷ ngày càng gần gũi, và Artuklas đã tiết lộ thông tin về dòng dõi của mình cho Sparrow.
        <br />Thật không may, ngay cả với việc đào tạo và các nghi lễ đều bổ sung cho sức mạnh của Sparrow, đứa trẻ không thể nắm bắt hoàn toàn sức mạnh mà Artuklas muốn chia sẻ. Artuklas, ngày càng mất kiên nhẫn và tức giận vì sự bất tài của đứa trẻ, đã quyết định ép một phần sức mạnh của mình chảy qua cơ thể cô. Sức mạnh này sẽ chứng tỏ là quá nhiều đối với Sparrow, và cô sẽ phải loại bỏ nhiều điều này để giữ được ý thức.
        <br />Một nhóm nhỏ các đội trinh sát của Người Bảo vệ sẽ nhận thấy năng lượng quỷ dữ khổng lồ tập trung ở một điểm. Khi đến nơi, họ sẽ thấy hình dáng của một con quỷ lớn hơn đang cố gắng kiểm soát một người phụ nữ đã ngã xuống. Họ đã nắm bắt cơ hội để tấn công, nhưng Sparrow đã phản công, cho phép Artuklas trốn thoát trong sự hỗn loạn. Sau một cuộc chiến kéo dài, các Người Bảo vệ sẽ chế ngự và đánh bại cô vì cô không thể sử dụng hiệu quả khả năng mới tìm thấy của mình.`,
    kr: `본래 은둔자였던 용감하고 사나운 여인 스패로우는, 생의 대부분을 악마 아르투클라스를 따르는 데 바쳤다. 그녀와 그녀의 가족은 울창한 사수그로엔 열대우림 깊숙한 곳의 마을에서 살았다. 강한 모험심을 지닌 그녀는 겁 많고 조용한 또래 아이들과는 확연히 달랐다. 그녀는 가족과 함께 아르투클라스가 은둔자들에게 정해준 길을 따랐다.
        <br />발견과 지식을 상징하는 존재였던 아르투클라스는, 미지의 것을 찾아 나서고 정보를 캐내려는 호기심 많고 용감한 스패로우에게 흥미를 느꼈다. 그는 자신을 따르고 숭배하려던 다른 은둔자들을 물리치면서까지 스패로우의 필요에 맞춰 서서히 자신의 길을 만들어갔다. 스패로우는 그 변화를 눈치챘지만, 아르투클라스는 운명이 그녀를 위해 이 길을 정한 것이라며 안심시켰다. 이어진 수년간의 훈련과 준비 속에서 은둔자와 악마 사이의 유대는 더욱 깊어졌고, 아르투클라스는 자신의 혈족에 관한 정보를 스패로우에게 털어놓기 시작했다.
        <br />하지만 스패로우의 재능에 맞춘 훈련과 의식에도 불구하고, 그녀는 아르투클라스가 나누어주려는 힘을 온전히 다루지 못했다. 아이의 미숙함에 조바심을 내며 분노한 아르투클라스는 결국 자신의 힘 일부를 강제로 그녀의 몸에 흘려보내기로 했다. 그러나 그 힘은 스패로우에게 너무 벅찼고, 그녀는 의식을 유지하기 위해 그 대부분을 다시 방출해야만 했다.
        <br />가디언 소규모 정찰대가 한곳에 집중된 거대한 악마의 기운을 감지했다. 현장에 도착한 그들은 쓰러진 여인을 지배하려는 거대한 악마의 형상을 목격했다. 그들은 기회를 놓치지 않고 공격했지만, 스패로우는 반격했고 그 혼란을 틈타 아르투클라스는 달아났다. 길고 치열한 싸움 끝에, 새로 얻은 힘을 제대로 다루지 못한 스패로우는 결국 가디언들에게 제압당하고 말았다.`,
  },
  [LOCALE.BELLE_DESCRIPTION]: {
    en: "Belle was born in the heart of an ancient, magical forest, where nature and magic coexisted in perfect harmony. Her family were the guardians of this enchanted woodland, tasked with preserving its beauty and protecting its secrets. From a young age, Belle showed a unique affinity for the flora around her, able to communicate with plants and channel their natural energy through her magic. One fateful day, a force of hermits invaded the forest, seeking to exploit its magical resources for their nefarious purposes. Belle's family fought valiantly to defend their home, but the enemy was too powerful. In a desperate bid to save the forest, Belle unleashed a powerful enchantment, intertwining her own life force with that of the forest. This act of selflessness granted her immense power but also bound her fate to the wellbeing of the woodland. Now, as the Thorn Enchantress, Belle roams the land, using her magical abilities to protect nature and fight against those who would harm it. She is a symbol of resilience, embodying the strength and fragility of the natural world she cherishes.",
    br: 'Parte de uma antiga raça de criaturas fay na floresta antiga, Belle nasceu com controle sobre as plantas, seu pai era um humano e sua mãe uma fada, depois de ter dois filhos, sua mãe escondeu sua família em uma parte isolada da floresta magica, quando ela e seu irmão cresceram, seu pai desapareceu misteriosamente sem deixar pistas, agora Belle e seu irmão procuram por seu pai e tentam esconder sua verdadeira identidade.',
    ru: 'Белла родилась в самом сердце древнего волшебного леса, где природа и магия жили в абсолютной гармонии. Её семья была хранителями этого зачарованного края, им доверено было сохранять его первозданную красоту и оберегать его тайны. С юных лет Белла проявляла удивительную связь с миром растений: она могла общаться с ними и направлять их природную энергию через свою магию. Но однажды покой леса был нарушен. Воины-отшельники вторглись в его священные пределы, стремясь использовать магическую силу леса для своих тёмных замыслов. Семья Беллы сражалась храбро, защищая свой дом, но враг оказался слишком силён. В отчаянной попытке спасти лес, Белла наложила мощное заклинание, переплетя свою жизненную силу с энергией леса в единое целое. Этот акт самоотверженности даровал ей огромную мощь, но также навеки связал её судьбу с благополучием этого лесного мира. Теперь, став Чародейкой Шипов, Белла странствует по миру, защищая природу от рук тех, кто жаждет её разрушения. Она – воплощение стойкости и нежности, символ неукротимой силы и хрупкости природы, которую она столь заботливо охраняет.',
    cz: 'Belle se narodila v srdci prastarého magického lesa, kde příroda a magie žily v dokonalé rovnováze. Její rodina chránila toto začarované místo a jeho tajemství. Když les napadli poustevníci, Belle spojila vlastní životní sílu se silou lesa, aby jej zachránila. Získala obrovskou moc, ale její osud se navždy svázal s blahobytem hvozdu. Nyní jako Trnová čarodějka chrání přírodu před každým, kdo by jí chtěl ublížit.',
    zh: '　　蓓蕾生在一個古老而神奇的森林中央，那是個大自然與魔法共存的完美和諧之地。她的家人皆是這片魔法森林的守護者，肩負著守護其美麗並保護其秘密的任務。在年少時，蓓蕾對她周遭的鮮花表現出一股獨特的親和力，能夠與植物溝通，透過魔法之力疏通植物的大自然能量。在某個攸關運命的日子，一群隱士入侵森林，試圖利用這個魔法資源來達成邪惡的目的。蓓蕾的家人們為了守護家園勇敢抗爭，但是那些敵人實在是太強大了。作為守住森林的絕望代價，蓓蕾釋放出一個堅實的結界，將自己與森林的生命力交織在一起。這個無私的行動造就出她巨大的力量，但這使她的命運與森林的福祉綁在了一起。現在，身為一個荊棘女巫，漫遊在這森林境地，使用她的神奇力量保護大自然並與可能會傷害這片境地的人戰鬥。她是堅韌的象徵，這體現出她所珍視的東西－大自然的力量，同時也包含著大自然的脆弱。',
    fr: "Belle naquit au cœur d'une ancienne forêt magique, où la nature et la magie vivaient en parfaite harmonie. Sa famille protégeait ce bois enchanté et ses secrets. Lorsque des ermites envahirent la forêt, Belle mêla sa propre force vitale à celle des arbres pour la sauver. Ce sacrifice lui donna une grande puissance, mais lia son destin à celui du bois. Désormais, enchanteresse des ronces, elle protège la nature contre ceux qui voudraient la blesser.",
    id: 'Bagian dari ras kuno makhluk fay di hutan kuno, Belle lahir dengan kendali arcane atas tanaman yang tak tertandingi oleh siapa pun sebelumnya, dia adalah seorang elemental yang sejenis dan menggunakan pengetahuannya tentang alam untuk menyembuhkan mereka yang membutuhkan, namun kedua belah pihak mencoba merekrutnya tetapi gagal dan sementara para penjaga hanya kecewa, para pertapa melakukan upaya berulang kali untuk menggabungkannya ke dalam kekuatan mereka. Akhirnya, para kultus memutuskan untuk menghilangkan ancaman tersebut dan mereka membawa tiga pemimpin pertapa: Flin, Kumihu, dan Puppeteer untuk mencemari atau membunuhnya, Belle berhasil mengalahkan Flin sebelum menyerah pada mantra pesona yang dilemparkan oleh Kumihu dengan sisa kesadarannya yang terakhir, dia melemparkan sebuah polong ke arah Kumihu yang meledak di wajahnya, saat Belle bangkit kembali dia terikat oleh benang yang muncul dari jari-jari Puppeteer dan kehilangan kendali atas tubuhnya, saat dia dipaksa berjalan kembali ke kamp pertapa dia berjuang melawan benang yang bersinar tetapi dia tidak sebanding dengan iblis besar. Di tangan para pertapa Belle disiksa dan dilanggar hingga dirinya yang asli yang bahagia dan ceria terjebak di sudut terdalam pikirannya sementara kepribadian baru yang penuh kebencian muncul dan dia tidak pernah sama lagi, mungkin beberapa penyembuh arcane akan datang dan membangkitkan dirinya yang lama atau mungkin dia akan terjebak sebagai pertapa gila selamanya.',
    vi: 'Là một phần của một chủng tộc cổ xưa của những sinh vật thần bí trong rừng cổ, Belle được sinh ra với khả năng điều khiển huyền bí đối với thực vật không ai sánh kịp trước cô, cô là một người điều khiển nguyên tố và đã sử dụng kiến thức của mình về thiên nhiên để chữa lành những người cần giúp đỡ, tuy nhiên cả hai bên đã cố gắng chiêu mộ cô nhưng đều thất bại và trong khi các người bảo vệ chỉ thất vọng, các ẩn sĩ đã thực hiện nhiều nỗ lực để bắt cô vào lực lượng của họ. Cuối cùng, các tín đồ quyết định loại bỏ mối đe dọa và họ đã mang đến ba nhà lãnh đạo ẩn sĩ: Flin, Kumihu và Puppeteer để hoặc làm ô uế cô hoặc giết cô, Belle đã thành công đánh bại Flin trước khi đầu hàng trước các phép thuật quyến rũ do Kumihu thi triển, với mảnh ý thức cuối cùng của mình, cô đã ném một quả đậu vào Kumihu khiến nó nổ tung vào mặt cô, khi Belle đứng dậy, cô bị trói buộc bởi những sợi dây xuất hiện từ ngón tay của Puppeteer và mất quyền kiểm soát cơ thể, khi cô bị buộc phải đi bộ trở lại trại ẩn sĩ, cô đã chống lại những sợi chỉ phát sáng nhưng không thể so sánh với một con quỷ lớn. Trong tay các ẩn sĩ, Belle đã bị tra tấn và xâm hại cho đến khi bản thân vui vẻ và hạnh phúc ban đầu của cô bị mắc kẹt ở những góc sâu nhất trong tâm trí cô trong khi một nhân cách mới đầy thù hận xuất hiện và cô không bao giờ còn như trước nữa, có thể một số thầy thuốc huyền bí sẽ đến và đánh thức lại bản thân cũ của cô hoặc có thể cô sẽ bị mắc kẹt như một ẩn sĩ điên cuồng mãi mãi.',
    kr: `벨은 자연과 마법이 완벽한 조화를 이루는 고대의 신비로운 숲 한가운데서 태어났다. 그녀의 가족은 이 마법의 숲을 지키는 수호자로서, 그 아름다움을 보존하고 비밀을 지키는 임무를 맡고 있었다. 어린 시절부터 벨은 주변 식물들과 남다른 교감을 보였으며, 식물과 대화하고 마법을 통해 그들의 자연 에너지를 다룰 수 있었다. 운명의 어느 날, 은둔자 무리가 사악한 목적으로 숲의 마법 자원을 노리고 침입해 왔다. 벨의 가족은 용감히 맞서 싸웠지만 적은 너무나 강력했다. 숲을 구하기 위한 필사적인 시도로, 벨은 강력한 마법을 발동해 자신의 생명력을 숲의 생명력과 하나로 엮었다. 이 헌신적인 행위는 그녀에게 엄청난 힘을 주었지만, 동시에 그녀의 운명을 숲의 안녕과 영원히 묶어버렸다. 이제 가시의 마법사가 된 벨은 대지를 떠돌며 마법의 힘으로 자연을 지키고, 자연을 해치려는 자들에 맞서 싸운다. 그녀는 자신이 소중히 여기는 자연계의 강인함과 연약함을 동시에 지닌, 불굴의 상징이다.`,
  },
  [LOCALE.KIRA_DESCRIPTION]: {
    en: 'As a young girl, Kira used to sit at the window of her home and watch the lightning. As she grew up, she began a hobby of chasing storm clouds, hoping to see flashes of electricity in the sky. The rain did not bother her, the wind could not deter her, only when she felt the true power of the storm did she stop. As Kira reached the highest peak of a mountain, she was struck by the thunder she chased. As she fell, she was found by a hermit and brought back to a hidden encampment watched over by a demonic vassal. She was forged into whatever they wanted her to be against any free will. They made her into an electromancer, to aid the dark forces. They did not expect her to fight back as she called forth fury from above. Most of the hermits were caught unprepared and annihilated while the demonic leader named Draklavain strode through the barrage and would have killed her if not for hunting party of guardians attracted by the chaos. As she left with them, she found a tome and with it became an important asset to the crusade against the demons, although some say the tome found her.',
    br: 'Ex-general do exército do rei. Agora professora da Escola Mágica de demonologia do reino de Eilys, Kira é uma renomada instrutora, possuindo o demônio relâmpago selado em seu livro, ela procura ensinar a seus alunos a melhor maneira de usar o poder dos selados.',
    ru: 'В юности Кира любила сидеть у окна своего дома и наблюдать за молниями, а повзрослев, увлеклась погоней за грозовыми тучами в надежде увидеть в небе вспышки молний. Дождь её совершенно не беспокоил, а ветер не мог удержать её порыв. Лишь только почувствовав истинную силу бури она смогла остановиться. Она и не заметила, как достигла самой высокой вершины горы. Гром, за которым она гналась, поразил её, из-за чего она сорвалась и упала, потеряв сознание, но чудом выжив. Её обнаружил отшельник и отнёс в скрытый лагерь под покровительством демонического вассала. Против её воли они провели тёмный ритуал,  превратив в электроманта, в надежде, что она поможет тёмным силам. Неожиданным стал для всех оказанный ею отпор: вызванная ярость с небес застала врасплох многих отшельников, стерев их с лица земли в одно мгновение. В это время, лидер демонов Драклавейн пробирался через заградительный огонь из вспышек молний в надежде уничтожить отступницу. К счастью, стражи, охотящиеся на силы хаоса нашли её и помогли сбежать, сокрыв от опасности. Во время побега Кира обнаружила старинную книгу на своём пути, которую она сумела использовать в дальнейшем походе против армии демонов. Поговаривают, что не она нашла книгу, а книга нашла её.',
    cz: 'Jako mladá dívka Kira sedávala u okna a pozorovala blesky. Později začala pronásledovat bouřkové mraky, aby zahlédla záblesky elektřiny na obloze. Na vrcholu hory ji zasáhl hrom, který tak dlouho následovala. Našel ji poustevník a odnesl do skrytého tábora pod dohledem démonického vazala. Proti její vůli z ní vytvořili elektromantku, ale Kira se vzepřela a přivolala zuřivost shůry. Když odešla se Strážci, našla knihu, která z ní učinila důležitou zbraň proti démonům.',
    zh: '　　曾是年輕少女時，奇菈習慣坐在她家中的窗邊觀望閃電。長大後，追尋雷雲，期望能夠在空中看見閃電成為她的愛好，就連風雨也無法撼動她那蓬勃的心，直到她感受到暴風的真實之力後才會就此打住。當她爬向山頂的巔峰，她被她不斷追逐的閃電擊中，她沉寂後被一名隱士發現，並帶回了一個祕密營地交由惡魔附庸看守。違背了她的自由意志，他們想將她鍛造成任何他們想要的樣子，使她成為協助闇黑勢力的雷電巫師。但他們沒料想到她會召喚雷霆之怒展開逆襲，大部分的隱士因而毫無防備的被擒獲與殲滅，若不是此時此刻，惡魔首領「德拉克拉文」正為了被混沌勢力吸引而來的守衛狩獵隊而穿越槍林彈雨，他大概早已斷送她的性命。當她與守衛者們同行離開後，她發現了一本魔道書，而有了這本書，它將會成為與惡魔黨決一聖戰的重要資產。雖然有人是這麼說的：「是這本書找到了她。」',
    fr: "Jeune, Kira aimait regarder les éclairs depuis la fenêtre de sa maison. En grandissant, elle se mit à poursuivre les nuages d'orage pour apercevoir l'électricité dans le ciel. Au sommet d'une montagne, elle fut frappée par la foudre qu'elle chassait. Un ermite la trouva et l'amena dans un camp caché gardé par un vassal démoniaque. Ils firent d'elle une électromancienne contre sa volonté, mais Kira se rebella en appelant la colère du ciel. En partant avec les Gardiens, elle trouva un grimoire qui devint une arme majeure contre les démons.",
    id: 'Sebagai seorang gadis muda, Kira biasa duduk di jendela rumahnya dan menonton kilat. Saat dia tumbuh dewasa, dia mulai hobi mengejar awan badai, berharap bisa melihat kilatan listrik di langit. Hujan tidak mengganggunya, angin tidak bisa menghalanginya, hanya ketika dia merasakan kekuatan sejati dari badai, dia berhenti. Ketika Kira mencapai puncak tertinggi sebuah gunung, dia tersambar petir yang dia kejar. Saat dia jatuh, dia ditemukan oleh seorang pertapa dan dibawa kembali ke sebuah perkemahan tersembunyi yang dijaga oleh seorang vassal demonik. Dia dipaksa menjadi apa pun yang mereka inginkan melawan kehendak bebasnya. Mereka menjadikannya seorang elektromancer, untuk membantu kekuatan gelap. Mereka tidak mengharapkan dia melawan saat dia memanggil kemarahan dari atas. Sebagian besar para pertapa terkejut dan dihancurkan sementara pemimpin demon bernama Draklavain melangkah melalui hujan peluru dan akan membunuhnya jika bukan karena kelompok pemburu penjaga yang tertarik oleh kekacauan. Saat dia pergi bersama mereka, dia menemukan sebuah buku dan dengan itu menjadi aset penting dalam perang salib melawan para demon, meskipun beberapa orang mengatakan buku itu menemukannya.',
    vi: 'Khi còn là một cô gái trẻ, Kira thường ngồi bên cửa sổ nhà mình và ngắm nhìn những tia chớp. Khi lớn lên, cô bắt đầu có sở thích đuổi theo những đám mây bão, hy vọng sẽ thấy những tia điện trong bầu trời. Cơn mưa không làm phiền cô, gió không thể ngăn cản cô, chỉ khi cô cảm nhận được sức mạnh thực sự của cơn bão thì cô mới dừng lại. Khi Kira đạt đến đỉnh cao nhất của một ngọn núi, cô bị sét đánh mà cô đã đuổi theo. Khi cô ngã xuống, cô được một người ẩn sĩ phát hiện và đưa trở lại một trại ẩn giấu được bảo vệ bởi một thuộc hạ quỷ dữ. Cô bị ép trở thành bất cứ điều gì mà họ muốn cô trở thành, trái với ý chí tự do của mình. Họ đã biến cô thành một nhà điện thuật, để hỗ trợ các thế lực bóng tối. Họ không mong đợi cô sẽ phản kháng khi cô gọi ra cơn thịnh nộ từ trên cao. Hầu hết các ẩn sĩ đều bị bất ngờ và bị tiêu diệt trong khi lãnh đạo quỷ dữ tên là Draklavain bước qua cơn mưa đạn và sẽ giết cô nếu không có nhóm thợ săn bảo vệ bị thu hút bởi sự hỗn loạn. Khi cô rời đi cùng họ, cô tìm thấy một cuốn sách và với nó trở thành một tài sản quan trọng trong cuộc thánh chiến chống lại các quỷ dữ, mặc dù một số người nói rằng cuốn sách đã tìm thấy cô.',
    kr: `어린 시절, 키라는 집 창가에 앉아 번개를 바라보곤 했다. 자라면서 그녀는 하늘에서 번쩍이는 전기를 보고 싶은 마음에 폭풍우 구름을 쫓아다니는 취미를 갖게 되었다. 비도 그녀를 막지 못했고 바람도 그녀를 단념시키지 못했으며, 오직 폭풍의 진정한 힘을 느꼈을 때에야 비로소 멈춰 섰다. 키라가 산의 가장 높은 봉우리에 다다랐을 때, 그녀가 쫓던 번개가 그녀를 내리쳤다. 쓰러진 그녀는 한 은둔자에게 발견되어, 악마 신하가 감시하는 은신처로 끌려갔다. 그녀는 자신의 의지와는 상관없이 그들이 원하는 존재로 만들어졌다. 그들은 어둠의 세력을 돕기 위해 그녀를 전기술사로 개조했다. 하지만 그녀가 하늘에서 분노를 불러내며 맞서 싸우리라고는 예상하지 못했다. 대부분의 은둔자들은 미처 대비하지 못한 채 전멸했고, 악마 지도자 드라클라베인은 포화 속을 뚫고 걸어와 그녀를 죽이려 했으나, 소란에 이끌려 온 가디언 사냥대 덕분에 목숨을 건졌다. 그들과 함께 떠난 그녀는 한 권의 마도서를 발견했고, 그것과 함께 악마에 맞선 성전의 중요한 전력이 되었다. 비록 일각에서는 그 책이 오히려 그녀를 찾아낸 것이라고도 하지만.`,
  },
  [LOCALE.AREL_DESCRIPTION]: {
    en: 'Captured as a small child at the tail end of the Demonic Subjugation War, subject D01, also known as Arel, was used as an experiment by the Guardians in their demonic magic research. Years of psychological torture, physical augmentation, and forced implantation of magical pathways in his body led to his being rendered nearly blind, and his left leg crippled. However, upon his clearance to be infused with demonic magic, something went horribly wrong. A sliver of his humanity cried out, and rejected the infusion, creating a nova of demonic magic that destroyed the facility he was being held in, and rendered him in a coma. When he next awoke, one thought filled his mind: vengeance. Picking up a belt of grenades and a pistol, Arel now wanders the outskirts of Guardian territory, inflicting swift death to those that tormented him all those years ago.',
    ru: 'Пленённый ещё ребёнком в конце Войны Подчинения Демонов, объект D01, также известный как Арел, стал подопытным для Стражей в их исследованиях демонической магии. Годы психологических истязаний, физических экспериментов и принудительной имплантации магических каналов для демонической магии в его тело привели к почти полной слепоте и параличу левой ноги. Но когда пришло время ввести в него проклятую энергию, всё пошло не по плану. Крупица его человечности восстала и отвергла тёмную силу, породив взрыв магической энергии, который уничтожил лабораторию, где его держали, и погрузил его в кому. Когда Арел очнулся, лишь одно чувство овладело его разумом: жажда мести. Вооружившись поясом с гранатами и пистолетом, он теперь бродит по окраинам земель Стражей, неся быструю смерть тем, кто обрёк его на годы страданий.',
    br: 'Capturado ainda criança no fim da Guerra de Subjugação Demoníaca, o sujeito D01, conhecido como Arel, foi usado pelos Guardiões em pesquisas de magia demoníaca. Anos de tortura e experimentos quase o cegaram e deixaram sua perna esquerda aleijada. Quando tentaram infundi-lo com magia demoníaca, sua humanidade rejeitou o ritual e destruiu a instalação. Ao acordar, Arel só pensava em vingança. Com granadas e uma pistola, ele caça aqueles que o atormentaram.',
    cz: 'Arel, zajatý jako malé dítě na konci Války podrobení démonů pod označením D01, byl Strážci použit při výzkumu démonické magie. Roky mučení, úprav těla a násilného vkládání magických cest ho téměř oslepily a ochromily mu levou nohu. Když do něj měla být vlita démonická magie, jeho zbytky lidskosti ji odmítly a zničily zařízení. Po probuzení myslel jen na pomstu.',
    zh: '　　物件D01，又稱為艾瑞爾，孩時在一場降魔戰爭的末期中被俘虜，被守護者拿來做為研究邪惡魔法的實驗對象。經歷過數多年的心理折磨與生理強化，並且被強行將魔道植入體內，這使他幾乎快要成為盲眼的存在，且使他的左腳殘廢了。然而，在他同意注入邪惡魔法之後，發生了嚴重的問題，他的一絲人性大聲嘶吼拒絕了注入，產生了一個邪惡魔法的爆破，摧毀了監禁他的設施，並使他陷入了昏迷。在他下一次醒來之後，有一個想法充斥了他的內心：復仇。拾起手榴彈腰帶和一把手槍之後，他在守護者領地附近徘迴，令那些前幾年害他飽受折磨的人迅速死去。',
    fr: "Capturé enfant à la fin de la Guerre de soumission démoniaque, le sujet D01, aussi appelé Arel, servit d'expérience aux Gardiens dans leurs recherches sur la magie démoniaque. Des années de torture et de modifications l'ont presque rendu aveugle et ont brisé sa jambe gauche. Quand on tenta de lui infuser cette magie, son humanité la rejeta et détruisit le laboratoire. À son réveil, il ne lui restait qu'une pensée : la vengeance.",
    id: 'Ditangkap saat masih kecil pada akhir Perang Penaklukan Demonik, subjek D01, juga dikenal sebagai Arel, digunakan oleh para Penjaga dalam riset sihir demonik. Bertahun-tahun penyiksaan dan eksperimen membuatnya hampir buta dan melumpuhkan kaki kirinya. Ketika sihir demonik hendak ditanamkan, sisi kemanusiaannya menolak dan menghancurkan fasilitas itu. Saat bangun, pikirannya hanya dipenuhi balas dendam.',
    vi: 'Bị bắt khi còn nhỏ vào cuối Cuộc chiến Khuất phục Quỷ, đối tượng D01, còn gọi là Arel, bị các Người Bảo vệ dùng làm vật thí nghiệm trong nghiên cứu ma thuật quỷ. Nhiều năm tra tấn và cải tạo cơ thể khiến anh gần như mù và què chân trái. Khi ma thuật quỷ được truyền vào, chút nhân tính còn lại đã chống lại và phá hủy cơ sở giam giữ. Khi tỉnh dậy, Arel chỉ còn một ý nghĩ: trả thù.',
    kr: `악마 진압 전쟁이 끝나갈 무렵 어린 나이에 포로로 잡힌 실험체 D01, 일명 아렐은 가디언들의 악마 마법 연구를 위한 실험 대상으로 이용되었다. 수년에 걸친 심리적 고문과 신체 개조, 그리고 강제로 이식된 마법 회로로 인해 그는 거의 실명에 가까운 상태가 되었고 왼쪽 다리마저 불구가 되었다. 그러나 악마 마법을 주입받기로 한 그날, 끔찍한 사고가 벌어졌다. 그의 안에 남아 있던 한 조각의 인간성이 비명을 지르며 주입을 거부했고, 그 여파로 발생한 악마 마법의 폭발이 그가 갇혀 있던 시설을 파괴하고 그를 혼수상태에 빠뜨렸다. 다시 눈을 떴을 때, 그의 머릿속을 가득 채운 것은 단 하나, 복수였다. 수류탄 벨트와 권총을 챙긴 아렐은 이제 가디언 영토의 변두리를 떠돌며, 오래전 자신을 고통스럽게 했던 자들에게 신속한 죽음을 안기고 있다.`,
  },
  [LOCALE.FOXY_DESCRIPTION]: {
    en: "Foxy was born into a family of survivalists deep in the forests. His parents, former military operatives, taught him everything they knew about survival, combat, and weaponry from a young age. Growing up in this harsh environment, Foxy developed a keen sense of awareness and a fierce independence. His skill with firearms and explosives quickly became apparent. When he was 18, tragedy struck. A rogue hermit group attacked his family, seeking to eliminate any threats to their illegal operations in the region. Foxy's parents were killed in the assault, but he managed to escape, swearing revenge. Driven by this loss, he spent the next decade honing his skills, training with various heroes and the strongest champions he could find.",
    ru: 'Фокси родился в семье выживальщиков, глубоко в лесных дебрях. Его родители, бывшие военные, с ранних лет учили его всему, что знали о выживании, боевых искусствах и обращении с оружием. Выросший в этих суровых условиях, Фокси обрёл острое чувство бдительности и неукротимую независимость. Его талант в стрельбе и работе с взрывчаткой раскрылся с поразительной быстротой. Когда ему исполнилось восемнадцать, случилась трагедия. Отряд отшельников-ренегатов напал на его семью, стремясь устранить любую угрозу своим незаконным делам в этом крае. Родители Фокси погибли в сражении, но он сумел бежать, дав клятву отомстить. Охваченный болью утраты, он посвятил следующие десять лет тому, чтобы отточить свои навыки ещё больше, тренируясь с героями и сильнейшими чемпионами, которых мог найти.',
    br: 'Foxy nasceu em uma família de sobrevivencialistas nas profundezas da floresta. Seus pais, antigos agentes militares, ensinaram tudo sobre sobrevivência, combate e armas. Quando ele tinha 18 anos, um grupo de eremitas renegados atacou sua família, matando seus pais. Foxy escapou e jurou vingança. Movido pela perda, passou anos aperfeiçoando suas habilidades com armas de fogo e explosivos.',
    cz: 'Foxy se narodil do rodiny přeživších hluboko v lesích. Jeho rodiče, bývalí vojenští agenti, ho od dětství učili přežití, boji a zacházení se zbraněmi. Když mu bylo osmnáct, skupina odpadlických poustevníků napadla jeho rodinu a zabila jeho rodiče. Foxy unikl a přísahal pomstu. Další roky strávil zdokonalováním svých schopností se střelnými zbraněmi a výbušninami.',
    zh: '　　弗克西誕生在森林深處的一個生存主義家庭之中。他的雙親，作為前軍事人員，在他年輕時教他任何以他們所知的生存、戰鬥、與使用武器的法則。在如此嚴峻的環境下長大，弗克西發展出了敏銳的意識與強烈的獨立性。他的槍械與爆炸技巧很快地就顯現了出來。在他十八歲時，一場悲劇發生了。一個惡棍隱士群體攻擊了他的家庭，為著消除任何在此境地非法活動會碰到的威脅。弗克西的雙親在這場突擊中喪生，但他拒絕逃跑，發誓要復仇。在這場落失的驅使之下，他在接下來的十年當中不斷琢磨他的技能，與各種英雄以及他所能找到的最強勝利者進行訓練。',
    fr: "Foxy naquit dans une famille de survivalistes au fond des forêts. Ses parents, anciens agents militaires, lui apprirent dès l'enfance la survie, le combat et les armes. À dix-huit ans, un groupe d'ermites renégats attaqua sa famille et tua ses parents. Foxy réussit à s'enfuir et jura de se venger. Guidé par cette perte, il passa les années suivantes à perfectionner son tir et son usage des explosifs.",
    id: 'Foxy lahir dalam keluarga penyintas jauh di dalam hutan. Orang tuanya, mantan agen militer, mengajarinya bertahan hidup, bertarung, dan menggunakan senjata sejak kecil. Saat berusia 18 tahun, kelompok pertapa pemberontak menyerang keluarganya dan membunuh orang tuanya. Foxy berhasil kabur dan bersumpah membalas dendam. Didorong kehilangan itu, ia mengasah keahlian senjata api dan bahan peledaknya selama bertahun-tahun.',
    vi: 'Foxy sinh ra trong một gia đình chuyên sinh tồn sâu trong rừng. Cha mẹ anh, từng là đặc vụ quân sự, dạy anh mọi điều về sinh tồn, chiến đấu và vũ khí từ nhỏ. Khi anh 18 tuổi, một nhóm ẩn sĩ phản loạn tấn công gia đình và giết cha mẹ anh. Foxy trốn thoát và thề trả thù. Nỗi mất mát đó khiến anh dành nhiều năm rèn luyện súng đạn và chất nổ.',
    kr: `폭시는 깊은 숲속, 생존주의자 가족 밑에서 태어났다. 전직 군 요원이었던 그의 부모는 어린 시절부터 생존과 전투, 무기에 관해 아는 모든 것을 그에게 가르쳤다. 이 혹독한 환경에서 자란 폭시는 예리한 감각과 강한 독립심을 기르게 되었다. 그의 화기 및 폭발물 다루는 솜씨는 금세 두각을 나타냈다. 그가 18살이 되던 해, 비극이 닥쳤다. 지역 내 불법 활동에 위협이 될 만한 요소를 제거하려던 불량 은둔자 무리가 그의 가족을 습격한 것이다. 폭시의 부모는 그 습격으로 목숨을 잃었지만, 그는 가까스로 탈출해 복수를 다짐했다. 그 상실감에 이끌려 그는 이후 10년간 실력을 갈고닦으며, 찾을 수 있는 온갖 영웅과 가장 강한 챔피언들에게 훈련을 받았다.`,
  },
  [LOCALE.MAGDALENE_DESCRIPTION]: {
    en: 'Magdalene was once a revered priestess in a forgotten realm, dedicated to maintaining the balance between life and death. She served as a bridge between the living and the dead, guiding souls to their final resting place with compassion and wisdom. However, her peaceful existence was shattered when the hermit force invaded her homeland, corrupting the land and enslaving the souls of the departed. Desperate to save her people and the souls she had sworn to protect, Magdalene performed a forbidden ritual, merging her essence with the power of an ancient, dark scythe. This act transformed her into a being of immense power, but at a great cost. She became the Soul Reaper, a harbinger of death who could command the souls of the fallen. While she succeeded in driving back the invaders, the corruption had taken root within her, and she was forever changed.',
    ru: 'Магдалина некогда была почитаемой жрицей в затерянном измерении, посвящённой сохранению равновесия между жизнью и смертью. Она служила проводницей между миром живых и царством мёртвых, с мудростью и состраданием провожая души в их последний путь. Но её мирное существование было разрушено, когда силы отшельников вторглись в её родные земли, осквернив их и поработив души умерших. В отчаянной попытке спасти свой народ и тех, чьи души она клялась оберегать, Магдалина совершила запретный ритуал, соединив свою сущность с древним тёмным серпом. Этот акт наделил её невероятной мощью, но это стоило ей многого. Она стала Жницей Душ — вестницей смерти, способной повелевать павшими душами. Ей удалось изгнать захватчиков, но тьма пустила корни в её сердце, навсегда изменив её.',
    br: 'Magdalene já foi uma sacerdotisa venerada em um reino esquecido, dedicada ao equilíbrio entre vida e morte. Ela guiava almas com compaixão e sabedoria. Quando os eremitas invadiram sua terra e escravizaram os mortos, Magdalene realizou um ritual proibido, unindo sua essência a uma antiga foice sombria. Ela se tornou a Ceifadora de Almas, poderosa, mas marcada para sempre pela corrupção que tentou combater.',
    cz: 'Magdalene bývala uctívanou kněžkou v zapomenuté říši a střežila rovnováhu mezi životem a smrtí. S laskavostí a moudrostí vedla duše na poslední cestu. Když její domov napadli poustevníci a zotročili duše mrtvých, vykonala zakázaný rituál a spojila svou podstatu se starobylou temnou kosou. Stala se Sekačkou duší, mocnou, ale navždy změněnou korupcí.',
    zh: '　　瑪格達琳曾是一個在被人遺忘的國度中受人尊敬的女祭司，致力於維持生與死的平衡。她作為生與死之間的橋樑服侍著，以慈悲與智慧領導靈魂到它們最後的安息之地。然而，她的平靜生活就在隱士勢力入侵她的家園後被打破了，他們腐化了土地並奴役了死者的靈魂。不顧一切地拯救她的人民與她誓言要保護的靈魂，瑪格達琳展開一場禁忌的儀式，將她的本質與古老、暗黑的鐮刀結合在了一塊。這一舉動使她轉變成了擁有無比力量的存在，但因此付出了巨大的代價。她成了死亡的預兆－奪魂者，指揮著墮落的靈魂。當她成功擊退了入侵者，她的腐化已經在她體內徹底扎根，她的後生已被永遠改變了。',
    fr: "Magdalene était autrefois une prêtresse révérée d'un royaume oublié, vouée à l'équilibre entre la vie et la mort. Elle guidait les âmes avec compassion et sagesse. Quand les ermites envahirent sa patrie et asservirent les morts, elle accomplit un rituel interdit, mêlant son essence à une ancienne faux obscure. Elle devint la Faucheuse d'âmes, puissante, mais changée à jamais par la corruption qu'elle avait combattue.",
    id: 'Magdalene pernah menjadi pendeta terhormat di alam terlupakan, menjaga keseimbangan antara hidup dan mati. Ia membimbing jiwa dengan belas kasih dan kebijaksanaan. Ketika pasukan pertapa menyerbu tanahnya dan memperbudak jiwa orang mati, Magdalene melakukan ritual terlarang, menyatukan dirinya dengan sabit gelap kuno. Ia menjadi Penuai Jiwa, kuat tetapi selamanya diubah oleh korupsi.',
    vi: 'Magdalene từng là một nữ tu sĩ được tôn kính ở một vương quốc bị lãng quên, tận tụy giữ cân bằng giữa sự sống và cái chết. Cô dẫn dắt linh hồn bằng lòng trắc ẩn và trí tuệ. Khi các ẩn sĩ xâm lược quê hương và nô dịch linh hồn người chết, Magdalene thực hiện nghi lễ cấm, hòa bản thể với một lưỡi hái hắc ám cổ xưa. Cô trở thành Kẻ Gặt Linh Hồn, mạnh mẽ nhưng mãi mãi bị thay đổi.',
    kr: `마그달렌은 한때 잊힌 왕국에서 삶과 죽음의 균형을 지키는 데 헌신했던 존경받는 여사제였다. 그녀는 산 자와 죽은 자를 잇는 다리 역할을 하며, 자비와 지혜로 영혼들을 그들의 마지막 안식처로 인도했다. 그러나 은둔자 세력이 그녀의 고향을 침략해 대지를 오염시키고 떠난 이들의 영혼을 노예로 삼으면서, 그녀의 평화로운 삶은 산산조각 났다. 자신의 백성과 지키기로 맹세한 영혼들을 구하기 위해 절박해진 마그달렌은 금지된 의식을 치러, 자신의 본질을 고대의 어두운 낫이 지닌 힘과 융합시켰다. 이 행위는 그녀를 엄청난 힘을 지닌 존재로 바꾸어 놓았지만, 그 대가는 컸다. 그녀는 쓰러진 자들의 영혼을 다스릴 수 있는 죽음의 사자, 영혼 수확자가 되었다. 침략자들을 물리치는 데는 성공했지만, 그 오염은 이미 그녀의 내면에 뿌리내려 그녀를 영원히 바꾸어 놓고 말았다.`,
  },
  [LOCALE.PUPPETEER_DESCRIPTION]: {
    en: 'A wandering marionettist who never travels alone. Bound to the wooden puppet he carved and gave life to through a forbidden craft, the Puppeteer commands it from a distance, pulling on unseen threads to strike, drag, and bind his enemies. Some say the puppet has a will of its own now, straining against its master whenever no one is looking.',
    ru: 'Странствующий кукловод, который никогда не путешествует один. Связанный с деревянной куклой, которую он вырезал и оживил запретным ремеслом, Кукловод управляет ею на расстоянии, дёргая за невидимые нити, чтобы бить, тащить и связывать врагов. Некоторые говорят, что у куклы теперь есть собственная воля, и она сопротивляется хозяину, когда никто не смотрит.',
    cz: 'Potulný loutkář, který nikdy necestuje sám. Spojen s dřevěnou loutkou, kterou vyřezal a oživil zakázaným řemeslem, ovládá ji na dálku a tahá za neviditelné nitě, aby udeřil, táhl a svázal své nepřátele. Někteří říkají, že loutka má nyní vlastní vůli.',
    zh: '一位從不獨自旅行的流浪操偶師。他與親手雕刻並以禁忌技藝賦予生命的木偶羈絆相連，從遠處操控著它，拉動看不見的絲線來打擊、拖拽並束縛敵人。有人說，這具木偶如今已有了自己的意志，總在無人注意時對抗著它的主人。',
    fr: "Un marionnettiste errant qui ne voyage jamais seul. Lié à la marionnette de bois qu'il a sculptée et animée grâce à un art interdit, le Marionnettiste la commande à distance, tirant des fils invisibles pour frapper, traîner et entraver ses ennemis. Certains disent que la marionnette a désormais sa propre volonté.",
    br: 'Um marionetista errante que nunca viaja sozinho. Ligado à marionete de madeira que esculpiu e deu vida através de um ofício proibido, o Marionetista a comanda à distância, puxando fios invisíveis para atacar, arrastar e prender seus inimigos. Alguns dizem que a marionete agora tem vontade própria.',
    id: 'Seorang dalang pengembara yang tak pernah bepergian sendirian. Terikat pada boneka kayu yang ia ukir dan hidupkan lewat keahlian terlarang, Sang Dalang mengendalikannya dari kejauhan, menarik benang tak kasat mata untuk menyerang, menyeret, dan mengikat musuh-musuhnya.',
    vi: 'Một người điều khiển rối lang thang không bao giờ đi một mình. Gắn liền với con rối gỗ mà anh đã khắc và thổi hồn bằng một thuật nghệ bị cấm, Bậc Thầy Rối điều khiển nó từ xa, kéo những sợi dây vô hình để tấn công, kéo lê và trói buộc kẻ thù.',
    kr: `결코 홀로 떠돌지 않는 방랑하는 인형사. 금지된 기술로 직접 깎아 생명을 불어넣은 나무 인형과 이어진 퍼펫티어는, 보이지 않는 실을 당겨 원거리에서 인형을 조종하며 적을 가격하고, 끌어당기고, 옭아맨다. 일각에서는 이제 그 인형이 스스로의 의지를 갖게 되어, 아무도 보지 않을 때면 주인에게 저항한다는 소문도 있다.`,
  },
  [LOCALE.PATROKLOS_DESCRIPTION]: {
    en: 'Patroklos sat idle, consumed by a restless inertia, as he watched his subjects battle day in and out. What manner of king would he be if he remained sequestered on the backlines while his people shed blood? Action was imperative. Clad in the mythic panoply bequeathed by the legendary exploits of his youth—adventures that ultimately forged his crown—he resolved once more to pioneer the vanguard, marching forward not only for the preservation of his kingdom, but for eternal glory.',
    ru: 'Патрокл сидел без дела, снедаемый тревожным бездействием, наблюдая, как его подданные день за днём сражаются в бою. Разве достоин звания короля тот, кто прячется в тылу, пока его народ проливает кровь? Действовать было необходимо. Облачившись в легендарные доспехи, доставшиеся ему от подвигов юности — тех самых приключений, что в итоге принесли ему корону, — он вновь решил встать во главе передовой, чтобы сражаться не только за спасение своего королевства, но и за вечную славу.',
    cz: 'Patroklos seděl nečinně, zmítán neklidnou netrpělivostí, zatímco sledoval, jak jeho poddaní den co den bojují v bitvách. Jakým by byl králem, kdyby zůstal ukryt v zázemí, zatímco jeho lid prolévá krev? Čin byl nevyhnutelný. Oděn do legendární výzbroje, odkazu hrdinských činů svého mládí – dobrodružství, která mu nakonec vynesla korunu – se znovu rozhodl vykročit do první linie, aby bojoval nejen za záchranu svého království, ale i za věčnou slávu.',
    zh: '帕特羅克洛斯終日無所事事，內心被難以平息的躁動侵蝕，眼睜睜看著臣民日復一日浴血奮戰。若他甘於困守後方，任憑子民流血犧牲，又算得上什麼樣的君王？行動勢在必行。身披年少時傳奇戰功所鑄就的神話戰甲——正是那些冒險最終為他贏得王冠——他再度決心奔赴最前線，不僅是為了守護自己的王國，更是為了永恆的榮耀。',
    fr: "Patroklos restait inactif, rongé par une inertie tenace, regardant ses sujets combattre jour après jour. Quel genre de roi serait-il s'il demeurait retranché à l'arrière pendant que son peuple versait son sang ? Il fallait agir. Revêtu de la panoplie mythique léguée par les exploits légendaires de sa jeunesse — les mêmes aventures qui avaient forgé sa couronne — il résolut une fois de plus de se porter à l'avant-garde, marchant en avant non seulement pour préserver son royaume, mais pour une gloire éternelle.",
    br: 'Patroklos permanecia ocioso, consumido por uma inércia inquieta, observando seus súditos lutarem dia após dia. Que tipo de rei ele seria se permanecesse escondido na retaguarda enquanto seu povo derramava sangue? Agir era imperativo. Vestindo a armadura mítica legada pelas façanhas lendárias de sua juventude — aventuras que, no fim, forjaram sua coroa — ele decidiu mais uma vez liderar a vanguarda, marchando à frente não apenas para preservar seu reino, mas em busca de glória eterna.',
    id: 'Patroklos duduk diam, dilanda kegelisahan yang tak kunjung reda, sambil menyaksikan rakyatnya bertempur hari demi hari. Raja macam apa dirinya jika terus bersembunyi di garis belakang sementara rakyatnya menumpahkan darah? Bertindak adalah keharusan. Mengenakan baju zirah legendaris warisan petualangan masa mudanya—petualangan yang pada akhirnya membawanya ke mahkota—ia sekali lagi bertekad memimpin garis depan, maju bukan hanya demi menjaga kerajaannya, tetapi demi kejayaan abadi.',
    vi: 'Patroklos ngồi yên, bị giày vò bởi sự bứt rứt không nguôi, nhìn thần dân của mình ngày ngày chinh chiến. Ông sẽ là vị vua như thế nào nếu cứ mãi ẩn mình phía sau trong khi dân chúng đổ máu? Hành động là điều tất yếu. Khoác lên mình bộ giáp huyền thoại thừa hưởng từ những chiến công lẫy lừng thời trai trẻ—những cuộc phiêu lưu đã tạo nên vương miện của ông—ông một lần nữa quyết tâm tiên phong ra tiền tuyến, tiến bước không chỉ để bảo vệ vương quốc mà còn vì vinh quang bất diệt.',
    kr: `파트로클로스는 매일 백성들이 전투를 벌이는 모습을 지켜보며, 가라앉지 않는 초조함에 사로잡힌 채 가만히 앉아 있었다. 백성이 피를 흘리는 동안 후방에 몸을 숨기고 있다면, 그가 어떤 왕이라 할 수 있겠는가? 행동은 필수였다. 젊은 시절의 전설적인 무훈으로 물려받은 신화적인 갑주를 걸치고—바로 그 모험들이 결국 그의 왕관을 만들어냈다—그는 다시 한번 최전선에 서기로 결심했다. 왕국을 지키기 위해서만이 아니라, 영원한 영광을 위해.`,
  },
}

export default hero_description_data
