/* eslint-disable no-irregular-whitespace */
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-nocheck
import { LOCALE } from 'lang/locales'

export const home_page: { [key in LOCALE]?: { [key in string]: string } } = {
  [LOCALE.LOGIN_AS_GUEST]: {
    en: 'Login as Guest',
    ru: 'Войти как гость',
    cz: 'Přihlaste se jako host',
    zh: '以游客身份登录',
    fr: "Se connecter en tant qu'invité",
    br: 'Entrar como convidado',
  },
  [LOCALE.LOGIN_LINK_CODE]: {
    en: 'Login with Link Code',
    ru: 'Войти с кодом ссылки',
    cz: 'Přihlaste se pomocí kódu odkazu',
    zh: '使用链接代码登录',
    fr: 'Se connecter avec un code de lien',
    br: 'Entrar com código de link',
  },
  [LOCALE.LOGIN_OTHER_METHODS]: {
    en: 'Login with Other Methods',
    ru: 'Войти с другими методами',
    cz: 'Přihlaste se pomocí jiných metod',
    zh: '使用其他方法登录',
    fr: "Se connecter avec d'autres méthodes",
    br: 'Entrar com outros métodos',
  },
  [LOCALE.USERNAME]: {
    en: 'Username',
    ru: 'Имя пользователя',
    cz: 'Uživatelské jméno',
    zh: '用户名',
    fr: "Nom d'utilisateur",
    br: 'Nome de usuário',
  },
  [LOCALE.LINK_CODE]: {
    en: 'Link Code',
  },
  [LOCALE.SELECT_REGION]: {
    en: 'Select Region',
    ru: 'Выбрать регион',
    cz: 'Vybrat region ',
    zh: '选择地区',
    fr: 'Sélectionner une région',
    br: 'Selecione a região',
  },
  [LOCALE.SERVER]: {
    en: 'Server',
    ru: 'Сервер',
    cz: 'Server',
    zh: '服务器',
    fr: 'Serveur',
    br: 'Servidor',
  },
  [LOCALE.PING]: {
    en: 'Ping',
    ru: 'Пинг',
    cz: 'Ping',
    zh: 'Ping',
    fr: 'Ping',
    br: 'Ping',
  },
  [LOCALE.DISCORD]: {
    en: 'Discord',
    ru: 'Discord',
    cz: 'Discord',
    zh: 'Discord',
    fr: 'Discord',
    br: 'Discord',
  },
  [LOCALE.TERMS_OF_SERVICES]: {
    en: 'Terms of Service',
    ru: 'Условия использования',
    cz: 'Podmínky služby',
    zh: '服务条款',
    fr: "Conditions d'utilisation",
    br: 'Termos de serviço',
  },
  [LOCALE.PRIVACY_POLICY]: {
    en: 'Privacy Policy',
    ru: 'Политика конфиденциальности',
    cz: 'Zásady ochrany',
    zh: '隐私政策',
    fr: 'Politique de confidentialité',
    br: 'Política de privacidade',
  },
  [LOCALE.PARTNERS]: {
    en: 'Partners',
    ru: 'Партнёры',
    cz: 'Partneři',
    zh: '合作伙伴',
    fr: 'Partenaires',
    br: 'Parceiros',
  },
  [LOCALE.SOCIAL]: {
    en: 'Social',
    ru: 'Социальные сети',
    cz: 'Sociální sítě',
    zh: '社交',
    fr: 'Social',
    br: 'Social',
  },
  [LOCALE.INFORMATIONS]: {
    en: 'Information',
    ru: 'Информация',
    cz: 'Informace',
    zh: '信息',
    fr: 'Informations',
    br: 'Informações',
  },
  [LOCALE.LOGIN_AS]: {
    en: 'Login as',
    ru: 'Войти как',
    cz: 'Přihlásit se jako',
    zh: '登录为',
    fr: 'Se connecter en tant que',
    br: 'Entrar como',
  },
  [LOCALE.RENAME_ERROR_ALREADY_EXISTS]: {
    en: 'Name is already taken. Select another one!',
    ru: 'Это имя уже занято. Выберите другое!',
    cz: 'Toto jméno je již obsazeno. Vyberte jiné!',
    zh: '此名称已被使用。请选择另一个！',
    fr: 'Le nom est déjà pris. Sélectionnez-en un autre!',
    br: 'Nome já está em uso. Selecione outro!',
  },
  [LOCALE.RENAME_ERROR_INCORRECT_NAME]: {
    en: 'The name must be between 3 and 15 letters long and cannot contain forbidden letters.',
    ru: 'Имя должно быть от 3 до 15 букв и не должно содержать запрещенных символов.',
    cz: 'Jméno musí být dlouhé 3 až 15 písmen a nesmí obsahovat zakázané znaky.',
    zh: '名称必须介于3到15个字母之间，且不能包含禁用字母。',
    fr: 'Le nom doit comporter entre 3 et 15 lettres et ne peut pas contenir de lettres interdites.',
    br: 'O nome deve ter entre 3 e 15 letras e não pode conter letras proibidas.',
  },
  [LOCALE.RENAME_ERROR_NO_CONNECTION]: {
    en: "Can't connect with server",
    ru: 'Нет соединения с сервером',
    cz: 'Nelze se připojit k serveru',
    zh: '无法连接到服务器',
    fr: 'Impossible de se connecter au serveur',
    br: 'Não é possível conectar-se ao servidor',
  },
  [LOCALE.LOADING]: {
    en: 'Loading...',
    ru: 'Загрузка...',
    cz: 'Načítá se...',
    zh: '载入中...',
    fr: 'Chargement...',
    br: 'Carregando...',
  },
  [LOCALE.CONGRATULATION]: {
    en: 'Congratulations',
    ru: 'Поздравляем',
    cz: 'Gratuluji',
    zh: '祝贺',
    fr: 'Félicitations',
    br: 'Parabéns',
  },
  [LOCALE.PLAY_PAGE_RANKED_DESCRIPTION]: {
    en: ' - Reward: experience, coins and ELO\n - <b>+15% experience and coins</b>\n - Rank based matchmaking\n - 2 vs 2 only',
    ru: ' - Награды: опыт, монеты и Очки рейтинга\n - <b>+15% к получаемому опыту и монетам</b>\n - Подбор на основе ранга\n - Только 2 vs 2',
    cz: ' - Odměna: zkušenosti, mince a ELO\n - <b>+15% více zkušeností a mincí</b>\n - Dohazování na základě hodnocení\n - Pouze 2 vs 2',
    zh: ' - 奖励：经验、硬币和ELO\n - <b>+15% 经验和硬币</b>\n - 基于排名的匹配\n - 仅限2对2',
    fr: " - Récompense : expérience, pièces et ELO\n - <b>+15% d'expérience et de pièces</b>\n - Matchmaking basé sur le rang\n - 2 vs 2 seulement",
    br: ' - Recompensa: experiência, moedas e ELO\n - <b>+15% de experiência e moedas</b>\n - Matchmaking baseado em classificação\n - Apenas 2 vs 2',
  },
  [LOCALE.PLAY_PAGE_UNRANKED_DESCRIPTION]: {
    en: ' - Reward: experience and coins\n - 1 vs 1 and 2 vs 2',
    ru: ' - Награды: опыт и монеты\n - 1vs1 и 2vs2',
    cz: ' - Odměna: zkušenosti a mince\n - 1 vs 1 a 2 vs 2',
    zh: ' - 奖励：经验和硬币\n - 1对1和2对2',
    fr: ' - Récompense : expérience et pièces\n - 1 vs 1 et 2 vs 2',
    br: ' - Recompensa: experiência e moedas\n - 1 vs 1 e 2 vs 2',
  },
  [LOCALE.PLAY_PAGE_2VAI_DESCRIPTION]: {
    en: ' - Reward: experience and coins\n - 2 Players vs 2 Hard AI\n - 25% less experience and coins',
    ru: ' - Награды: опыт и монеты\n - 2 игрока против 2 Сложных ботов\n - На 25% меньше получаемого опыта и монет',
    cz: ' - Odměna: zkušenosti a mince\n - 2 hráči vs 2 tvrdá umělá inteligence\n - o 25 % méně zkušeností a mincí',
    zh: ' - 奖励：经验和硬币\n - 2玩家对2个困难AI\n - 减少25%的经验和硬币',
    fr: " - Récompense : expérience et pièces\n - 2 joueurs contre 2 IA difficiles\n - 25% d'expérience et de pièces en moins",
    br: ' - Recompensa: experiência e moedas\n - 2 Jogadores vs 2 IA Difícil\n - 25% menos experiência e moedas',
  },
  [LOCALE.POPUP_GENERATE_NAME]: {
    en: 'Generate Name',
    ru: 'Сгенерировать имя',
    cz: 'Generovat jméno',
    zh: '生成名称',
    fr: 'Générer un nom',
    br: 'Gerar Nome',
  },
  [LOCALE.LOGIN_ALREADY_LOGGED_IN]: {
    en: 'You are already logged in',
    ru: 'Вы уже вошли в систему',
    cz: 'Již jste přihlášeni',
    zh: '您已经登录',
    fr: 'Vous êtes déjà connecté',
    br: 'Você já está logado',
  },
  [LOCALE.RANKED_MATCH]: {
    en: 'Ranked',
    ru: 'Ранговая очередь',
    br: 'Lutas',
    cz: 'Hodnocení',
    zh: '爬分賽',
    fr: 'Classé',
  },
  [LOCALE.NORMAL_MATCH]: {
    en: 'Unranked Game',
    cz: 'Nehodnocená hra',
    zh: '非排名赛',
    fr: 'Partie non classée',
    ru: 'Не ранговая игра',
    fr: 'Partie non classée',
    br: 'Partida sem classificação',
  },
  [LOCALE.PLAY_PAGE_PLAY_A_GAME]: {
    en: 'Play a Game!',
    ru: 'Играть!',
    br: 'Jogar uma partida!',
    cz: 'Hrát hru!',
    zh: '開始遊戲！',
    fr: 'Jouer une partie!',
  },
  [LOCALE.AI_MATCH]: {
    en: 'AI Matches (PvAI):',
    ru: 'Игры против ботов:',
    br: 'Partida contra Bot (PvAI):',
    cz: 'Zápasy proti AI (PvAI):',
    zh: 'AI 对战 (人机对战)：',
    ru: 'Игры против ИИ:',
    fr: "Matchs contre l'IA (PvIA):",
    br: 'Partida contra IA (PvIA):',
  },
}
