/* eslint-disable no-irregular-whitespace */
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-nocheck
import { LOCALE } from 'lang/locales'

export const home_page: { [key in LOCALE]?: { [key in string]: string } } = {
  [LOCALE.LOGIN_AS_GUEST]: {
    en: 'Login as Guest',
    ru: 'Войти как гость',
    cz: 'Přihlaste se jako host',
    zh: '以訪客身份登入',
    fr: "Se connecter en tant qu'invité",
    br: 'Entrar como convidado',
    vi: 'Đăng nhập tài khoản khách',
    id: 'Masuk sebagai Tamu',
  },
  [LOCALE.LOGIN_LINK_CODE]: {
    en: 'Login with Link Code',
    ru: 'Войти с кодом ссылки',
    cz: 'Přihlaste se pomocí kódu odkazu',
    zh: '使用連結代碼登入',
    fr: 'Se connecter avec un code de lien',
    br: 'Entrar com código de link',
    vi: 'Đăng nhập bằng mã liên kết',
    id: 'Masuk dengan Kode Tautan',
  },
  [LOCALE.LOGIN_OTHER_METHODS]: {
    en: 'Login with Other Methods',
    ru: 'Войти с другими методами',
    cz: 'Přihlaste se pomocí jiných metod',
    zh: '使用其他方法登入',
    fr: "Se connecter avec d'autres méthodes",
    br: 'Entrar com outros métodos',
    vi: 'Đăng nhập bằng các phương pháp khác',
    id: 'Masuk dengan Metode Lainnya',
  },
  [LOCALE.USERNAME]: {
    en: 'Username',
    ru: 'Имя пользователя',
    cz: 'Uživatelské jméno',
    zh: '用戶名',
    fr: "Nom d'utilisateur",
    br: 'Nome de usuário',
    vi: 'Tên tài khoản',
    id: 'Nama Pengguna',
  },
  [LOCALE.LINK_CODE]: {
    en: 'Link Code',
    ru: 'Код ссылки',
    cz: 'Kód odkazu',
    zh: '連結代碼',
    fr: 'Code de lien',
    br: 'Código de link',
    vi: 'Mã liên kết',
    id: 'Kode Tautan',
  },
  [LOCALE.SELECT_REGION]: {
    en: 'Select Region',
    ru: 'Выбрать регион',
    cz: 'Vybrat region ',
    zh: '選擇地區',
    fr: 'Sélectionner une région',
    br: 'Selecione a região',
    vi: 'Chọn Khu vực',
    id: 'Pilih Wilayah',
  },
  [LOCALE.SERVER]: {
    en: 'Server',
    ru: 'Сервер',
    cz: 'Server',
    zh: '伺服器',
    fr: 'Serveur',
    br: 'Servidor',
    vi: 'Máy chủ',
    id: 'Server',
  },
  [LOCALE.PING]: {
    en: 'Ping',
    ru: 'Пинг',
    zh: '延遲',
  },
  [LOCALE.DISCORD]: {
    en: 'Discord',
    // Discord in Russian
    ru: 'Дискорд',
  },
  [LOCALE.TERMS_OF_SERVICES]: {
    en: 'Terms of Service',
    ru: 'Условия использования',
    cz: 'Podmínky služby',
    zh: '服務條款',
    fr: "Conditions d'utilisation",
    br: 'Termos de serviço',
    vi: 'Điều khoản Dịch vụ',
    id: 'Syarat Layanan',
  },
  [LOCALE.PRIVACY_POLICY]: {
    en: 'Privacy Policy',
    ru: 'Политика конфиденциальности',
    cz: 'Zásady ochrany',
    zh: '隐私政策',
    fr: 'Politique de confidentialité',
    br: 'Política de privacidade',
    vi: 'Chính sách Bảo mật',
    id: 'Kebijakan Privasi',
  },
  [LOCALE.PARTNERS]: {
    en: 'Partners',
    ru: 'Партнёры',
    cz: 'Partneři',
    zh: '合作伙伴',
    fr: 'Partenaires',
    br: 'Parceiros',
    vi: 'Đối tác',
    id: 'Mitra',
  },
  [LOCALE.SOCIAL]: {
    en: 'Social',
    ru: 'Социальные сети',
    cz: 'Sociální sítě',
    zh: '社交',
    fr: 'Social',
    br: 'Social',
    vi: 'Mạng Xã hội',
    id: 'Sosial',
  },
  [LOCALE.INFORMATIONS]: {
    en: 'Information',
    ru: 'Информация',
    cz: 'Informace',
    zh: '資訊',
    fr: 'Informations',
    br: 'Informações',
    vi: 'Thông tin',
    id: 'Informasi',
  },
  [LOCALE.LOGIN_AS]: {
    en: 'Login as',
    ru: 'Войти как',
    cz: 'Přihlásit se jako',
    zh: '登入方式',
    fr: 'Se connecter en tant que',
    br: 'Entrar como',
    vi: 'Đăng nhập như',
    id: 'Masuk sebagai',
  },
  [LOCALE.MAINTENANCE_MODE_TITLE]: {
    en: 'Maintenance Mode',
    ru: 'Техническое обслуживание',
    cz: 'Režim údržby',
    zh: '维护模式',
    fr: 'Mode maintenance',
    br: 'Modo de manutenção',
    vi: 'Chế độ bảo trì',
    id: 'Mode pemeliharaan',
  },
  [LOCALE.MAINTENANCE_MODE_DESCRIPTION]: {
    en: 'We are currently under maintenance. Game will be available soon. Stay tuned and check our Discord for more information.',
    ru: 'Сейчас ведутся технические работы. Игра скоро снова будет доступна. Следите за новостями и загляните в наш Discord для подробностей.',
    cz: 'Právě probíhá údržba. Hra bude brzy znovu dostupná. Sleduj novinky a podívej se na náš Discord pro více informací.',
    zh: '我们目前正在维护中。游戏很快就会重新开放。请持续关注，并查看我们的 Discord 获取更多信息。',
    fr: 'Nous sommes actuellement en maintenance. Le jeu sera bientôt de nouveau disponible. Restez à l’écoute et consultez notre Discord pour plus d’informations.',
    br: 'Estamos em manutenção no momento. O jogo estará disponível em breve. Fique ligado e confira nosso Discord para mais informações.',
    vi: 'Chúng tôi hiện đang bảo trì. Trò chơi sẽ sớm khả dụng trở lại. Hãy theo dõi và vào Discord của chúng tôi để biết thêm thông tin.',
    id: 'Kami sedang dalam masa pemeliharaan. Game akan segera tersedia kembali. Tetap pantau dan cek Discord kami untuk informasi lebih lanjut.',
  },
  [LOCALE.MAINTENANCE_MODE_DISCORD]: {
    en: 'Discord Link',
    ru: 'Ссылка на Discord',
    cz: 'Odkaz na Discord',
    zh: 'Discord 链接',
    fr: 'Lien Discord',
    br: 'Link do Discord',
    vi: 'Liên kết Discord',
    id: 'Tautan Discord',
  },
  [LOCALE.MAINTENANCE_MODE_PATCH_NOTES]: {
    en: 'Update Log',
    ru: 'Список обновлений',
    cz: 'Seznam aktualizací',
    zh: '更新日志',
    fr: 'Journal des mises à jour',
    br: 'Registro de atualizações',
    vi: 'Nhật ký cập nhật',
    id: 'Log pembaruan',
  },
  [LOCALE.LANDING_SCROLL]: {
    en: 'Scroll',
    ru: 'Прокрутка',
    cz: 'Posunout',
    zh: '滚动',
    fr: 'Défiler',
    br: 'Rolar',
    vi: 'Cuộn',
    id: 'Gulir',
  },
  [LOCALE.LANDING_CONTINUE_AS]: {
    en: 'Continue as',
    ru: 'Продолжить как',
    cz: 'Pokračovat jako',
    zh: '继续为',
    fr: 'Continuer en tant que',
    br: 'Continuar como',
    vi: 'Tiếp tục với vai trò',
    id: 'Lanjutkan sebagai',
  },
  [LOCALE.LANDING_LOGIN_WITH_ARMOR_GAMES]: {
    en: 'Login with Armor Games',
    ru: 'Войти через Armor Games',
    cz: 'Přihlásit se přes Armor Games',
    zh: '使用 Armor Games 登录',
    fr: 'Se connecter avec Armor Games',
    br: 'Entrar com Armor Games',
    vi: 'Đăng nhập bằng Armor Games',
    id: 'Masuk dengan Armor Games',
  },
  [LOCALE.LANDING_SERVER_STATUS]: {
    en: 'Server Status',
    ru: 'Статус сервера',
    cz: 'Stav serveru',
    zh: '服务器状态',
    fr: 'Statut du serveur',
    br: 'Status do servidor',
    vi: 'Trạng thái máy chủ',
    id: 'Status server',
  },
  [LOCALE.LANDING_STATUS_ONLINE]: {
    en: 'Online',
    ru: 'Онлайн',
    cz: 'Online',
    zh: '在线',
    fr: 'En ligne',
    br: 'Online',
    vi: 'Trực tuyến',
    id: 'Online',
  },
  [LOCALE.LANDING_STATUS_OFFLINE]: {
    en: 'Offline',
    ru: 'Оффлайн',
    cz: 'Offline',
    zh: '离线',
    fr: 'Hors ligne',
    br: 'Offline',
    vi: 'Ngoại tuyến',
    id: 'Offline',
  },
  [LOCALE.LANDING_REGION_DEVELOPMENT]: {
    en: 'Development',
    ru: 'Разработка',
    cz: 'Vývoj',
    zh: '开发环境',
    fr: 'Développement',
    br: 'Desenvolvimento',
    vi: 'Phát triển',
    id: 'Pengembangan',
  },
  [LOCALE.LANDING_REGION_EUROPE]: {
    en: 'Europe',
    ru: 'Европа',
    cz: 'Evropa',
    zh: '欧洲',
    fr: 'Europe',
    br: 'Europa',
    vi: 'Châu Âu',
    id: 'Eropa',
  },
  [LOCALE.LANDING_REGION_US]: {
    en: 'United States (Texas)',
    ru: 'США (Техас)',
    cz: 'Spojené státy (Texas)',
    zh: '美国（德州）',
    fr: 'États-Unis (Texas)',
    br: 'Estados Unidos (Texas)',
    vi: 'Hoa Kỳ (Texas)',
    id: 'Amerika Serikat (Texas)',
  },
  [LOCALE.LANDING_REGION_SEA]: {
    en: 'South East Asia',
    ru: 'Юго-Восточная Азия',
    cz: 'Jihovýchodní Asie',
    zh: '东南亚',
    fr: 'Asie du Sud-Est',
    br: 'Sudeste Asiático',
    vi: 'Đông Nam Á',
    id: 'Asia Tenggara',
  },
  [LOCALE.LANDING_ABOUT_TITLE]: {
    en: 'Kingdom of Pixels',
    ru: 'Kingdom of Pixels',
    cz: 'Kingdom of Pixels',
    zh: 'Kingdom of Pixels',
    fr: 'Kingdom of Pixels',
    br: 'Kingdom of Pixels',
    vi: 'Kingdom of Pixels',
    id: 'Kingdom of Pixels',
  },
  [LOCALE.LANDING_ABOUT_TEXT]: {
    en: 'Kingdom of Pixels is a 2D online multiplayer side-scrolling MOBA platformer where players choose unique heroes, fight in fast-paced matches, and outplay opponents through skill, teamwork, and strategy.',
    ru: 'Kingdom of Pixels — это 2D онлайн многопользовательский сайд-скроллинговый MOBA-платформер, где игроки выбирают уникальных героев, сражаются в динамичных матчах и побеждают за счет навыка, командной игры и стратегии.',
    cz: 'Kingdom of Pixels je 2D online multiplayer side-scrolling MOBA plošinovka, kde si hráči vybírají unikátní hrdiny, bojují v rychlých zápasech a přehrávají soupeře dovedností, týmovou hrou a strategií.',
    zh: 'Kingdom of Pixels 是一款 2D 在线多人横版卷轴 MOBA 平台游戏，玩家可以选择独特英雄，在快节奏对局中通过操作、团队配合和策略击败对手。',
    fr: 'Kingdom of Pixels est un MOBA platformer 2D en ligne à défilement horizontal, où les joueurs choisissent des héros uniques, s’affrontent dans des matchs rapides et surpassent leurs adversaires grâce au skill, au travail d’équipe et à la stratégie.',
    br: 'Kingdom of Pixels é um MOBA platformer 2D online side-scrolling, onde os jogadores escolhem heróis únicos, lutam em partidas rápidas e superam os oponentes com habilidade, trabalho em equipe e estratégia.',
    vi: 'Kingdom of Pixels là game MOBA platformer cuộn cảnh ngang 2D nhiều người chơi trực tuyến, nơi người chơi chọn các vị tướng độc đáo, chiến đấu trong những trận đấu nhịp độ nhanh và vượt qua đối thủ bằng kỹ năng, phối hợp và chiến thuật.',
    id: 'Kingdom of Pixels adalah game MOBA platformer side-scrolling 2D multiplayer online, tempat pemain memilih hero unik, bertarung dalam match cepat, dan mengungguli lawan lewat skill, kerja sama tim, dan strategi.',
  },
  [LOCALE.LANDING_ABOUT_IMAGE_ALT]: {
    en: 'Kingdom of Pixels logo',
    ru: 'Логотип Kingdom of Pixels',
    cz: 'Logo Kingdom of Pixels',
    zh: 'Kingdom of Pixels 标志',
    fr: 'Logo Kingdom of Pixels',
    br: 'Logo do Kingdom of Pixels',
    vi: 'Logo Kingdom of Pixels',
    id: 'Logo Kingdom of Pixels',
  },
  [LOCALE.LANDING_MULTIPLAYER_TITLE]: {
    en: 'True Multiplayer Experience',
    ru: 'Настоящий мультиплеерный опыт',
    cz: 'Skutečný multiplayerový zážitek',
    zh: '真正的多人游戏体验',
    fr: 'Une véritable expérience multijoueur',
    br: 'Verdadeira experiência multiplayer',
    vi: 'Trải nghiệm multiplayer thực thụ',
    id: 'Pengalaman multiplayer sejati',
  },
  [LOCALE.LANDING_MULTIPLAYER_TEXT]: {
    en: 'Enter a high-intensity online battle arena where every second matters. Queue with friends, pick your main, and dominate through pure skill. No shortcuts, just fast gameplay, sharp mechanics, and real competition in Kingdom of Pixels.',
    ru: 'Вступай в напряженную онлайн-боевую арену, где важна каждая секунда. Ищи матч с друзьями, выбирай своего основного героя и побеждай за счет чистого навыка. Никаких shortcuts — только быстрый геймплей, точные механики и настоящая конкуренция в Kingdom of Pixels.',
    cz: 'Vstup do intenzivní online bojové arény, kde záleží na každé vteřině. Zařaď se do fronty s přáteli, vyber si svého maina a dominuj čistě dovedností. Žádné zkratky, jen rychlá hratelnost, přesné mechaniky a skutečná soutěž v Kingdom of Pixels.',
    zh: '进入一个每一秒都至关重要的高强度在线战场。和朋友一起排队，选择你的本命英雄，并凭借纯粹的技巧主宰比赛。没有捷径，只有快速的玩法、扎实的机制，以及 Kingdom of Pixels 中真正的竞争。',
    fr: 'Entrez dans une arène de bataille en ligne intense où chaque seconde compte. Lancez la file avec vos amis, choisissez votre main et dominez grâce au pur skill. Aucun raccourci, seulement un gameplay rapide, des mécaniques précises et une vraie compétition dans Kingdom of Pixels.',
    br: 'Entre em uma arena de batalha online intensa onde cada segundo importa. Entre na fila com amigos, escolha seu main e domine com pura habilidade. Sem atalhos, apenas gameplay rápido, mecânicas afiadas e competição de verdade em Kingdom of Pixels.',
    vi: 'Bước vào đấu trường chiến đấu trực tuyến cường độ cao, nơi từng giây đều quan trọng. Xếp hàng cùng bạn bè, chọn vị tướng tủ và thống trị bằng kỹ năng thuần túy. Không có lối tắt, chỉ có gameplay nhanh, cơ chế sắc bén và cạnh tranh thực sự trong Kingdom of Pixels.',
    id: 'Masuk ke arena pertempuran online intens tempat setiap detik berarti. Queue bersama teman, pilih hero andalanmu, dan kuasai pertandingan dengan skill murni. Tanpa jalan pintas, hanya gameplay cepat, mekanik tajam, dan kompetisi nyata di Kingdom of Pixels.',
  },
  [LOCALE.LANDING_MULTIPLAYER_IMAGE_ALT]: {
    en: 'Kingdom of Pixels multiplayer battle',
    ru: 'Мультиплеерная битва Kingdom of Pixels',
    cz: 'Multiplayerová bitva Kingdom of Pixels',
    zh: 'Kingdom of Pixels 多人对战',
    fr: 'Bataille multijoueur Kingdom of Pixels',
    br: 'Batalha multiplayer de Kingdom of Pixels',
    vi: 'Trận chiến multiplayer Kingdom of Pixels',
    id: 'Pertempuran multiplayer Kingdom of Pixels',
  },
  [LOCALE.LANDING_TUTORIAL_TITLE]: {
    en: 'Learn Through Interactive Tutorial',
    ru: 'Обучение через интерактивный туториал',
    cz: 'Uč se prostřednictvím interaktivního tutoriálu',
    zh: '通过互动教程学习',
    fr: 'Apprenez grâce à un tutoriel interactif',
    br: 'Aprenda com um tutorial interativo',
    vi: 'Học thông qua hướng dẫn tương tác',
    id: 'Belajar melalui tutorial interaktif',
  },
  [LOCALE.LANDING_TUTORIAL_TEXT]: {
    en: 'Get hands-on with the core mechanics through a guided interactive tutorial. Learn movement, combat, and game fundamentals step by step, so you are ready to compete from your very first match.',
    ru: 'Освой основные механики на практике с помощью интерактивного обучения. Изучай передвижение, бой и базовые принципы игры шаг за шагом, чтобы быть готовым к соревнованию уже с первого матча.',
    cz: 'Seznam se s hlavními mechanikami v řízeném interaktivním tutoriálu. Nauč se pohyb, boj a základy hry krok za krokem, aby ses mohl zapojit do soutěže už od prvního zápasu.',
    zh: '通过引导式互动教程亲自体验核心机制。逐步学习移动、战斗和游戏基础，让你从第一场比赛开始就能上手竞技。',
    fr: 'Découvrez les mécaniques de base grâce à un tutoriel interactif guidé. Apprenez les déplacements, le combat et les fondamentaux du jeu étape par étape afin d’être prêt à rivaliser dès votre tout premier match.',
    br: 'Aprenda na prática as mecânicas principais por meio de um tutorial interativo guiado. Domine movimento, combate e os fundamentos do jogo passo a passo para estar pronto para competir desde a sua primeira partida.',
    vi: 'Trải nghiệm trực tiếp các cơ chế cốt lõi thông qua hướng dẫn tương tác có chỉ dẫn. Học di chuyển, chiến đấu và các nền tảng của trò chơi từng bước một để sẵn sàng thi đấu ngay từ trận đầu tiên.',
    id: 'Pelajari langsung mekanik inti melalui tutorial interaktif terpandu. Pelajari pergerakan, pertarungan, dan dasar-dasar game langkah demi langkah agar kamu siap bertanding sejak match pertamamu.',
  },
  [LOCALE.LANDING_TUTORIAL_IMAGE_ALT]: {
    en: 'Kingdom of Pixels tutorial gameplay',
    ru: 'Геймплей обучения Kingdom of Pixels',
    cz: 'Tutoriálový gameplay Kingdom of Pixels',
    zh: 'Kingdom of Pixels 教程玩法',
    fr: 'Gameplay du tutoriel Kingdom of Pixels',
    br: 'Gameplay do tutorial de Kingdom of Pixels',
    vi: 'Lối chơi hướng dẫn của Kingdom of Pixels',
    id: 'Gameplay tutorial Kingdom of Pixels',
  },
  [LOCALE.LANDING_OBJECTIVES_TITLE]: {
    en: 'Game Objectives',
    ru: 'Цели игры',
    cz: 'Cíle hry',
    zh: '游戏目标',
    fr: 'Objectifs du jeu',
    br: 'Objetivos do jogo',
    vi: 'Mục tiêu trò chơi',
    id: 'Tujuan permainan',
  },
  [LOCALE.LANDING_OBJECTIVES_TEXT]: {
    en: 'Adapt to every match through heroes, items, and map objectives that constantly change how the game is played. Smart decisions, timing, and strategy matter just as much as mechanics, giving every battle a different flow.',
    ru: 'Подстраивайся под каждый матч благодаря героям, предметам и целям на карте, которые постоянно меняют ход игры. Умные решения, тайминг и стратегия важны не меньше механики, поэтому каждое сражение ощущается по-разному.',
    cz: 'Přizpůsob se každému zápasu pomocí hrdinů, předmětů a cílů na mapě, které neustále mění průběh hry. Chytrá rozhodnutí, načasování a strategie jsou stejně důležité jako mechaniky, takže každá bitva má jiný průběh.',
    zh: '通过英雄、装备和地图目标来适应每一场比赛，它们会不断改变游戏的进行方式。明智的决策、时机把握和策略与操作同样重要，让每场战斗都拥有不同的节奏。',
    fr: 'Adaptez-vous à chaque match grâce aux héros, aux objets et aux objectifs de carte qui modifient sans cesse la manière de jouer. Les bonnes décisions, le timing et la stratégie comptent autant que les mécaniques, ce qui donne à chaque bataille un rythme différent.',
    br: 'Adapte-se a cada partida por meio de heróis, itens e objetivos do mapa que mudam constantemente a forma como o jogo é jogado. Decisões inteligentes, timing e estratégia importam tanto quanto mecânicas, dando a cada batalha um ritmo diferente.',
    vi: 'Thích nghi với từng trận đấu thông qua tướng, trang bị và các mục tiêu bản đồ luôn thay đổi cách trận đấu diễn ra. Quyết định thông minh, thời điểm và chiến thuật quan trọng không kém kỹ năng cơ học, khiến mỗi cuộc chiến có nhịp độ khác nhau.',
    id: 'Beradaptasilah di setiap match melalui hero, item, dan objektif map yang terus mengubah cara permainan berlangsung. Keputusan cerdas, timing, dan strategi sama pentingnya dengan mekanik, membuat setiap pertempuran punya alur yang berbeda.',
  },
  [LOCALE.LANDING_OBJECTIVES_IMAGE_ALT]: {
    en: 'Kingdom of Pixels gold rune objective',
    ru: 'Цель с золотой руной в Kingdom of Pixels',
    cz: 'Cíl se zlatou runou v Kingdom of Pixels',
    zh: 'Kingdom of Pixels 金符文目标',
    fr: 'Objectif de rune dorée dans Kingdom of Pixels',
    br: 'Objetivo da runa dourada em Kingdom of Pixels',
    vi: 'Mục tiêu ngọc vàng trong Kingdom of Pixels',
    id: 'Objektif rune emas Kingdom of Pixels',
  },
  [LOCALE.LANDING_HERO_CAROUSEL_TITLE]: {
    en: 'Play Your Own Way',
    ru: 'Играй по-своему',
    cz: 'Hraj po svém',
    zh: '用你的方式游玩',
    fr: 'Jouez à votre façon',
    br: 'Jogue do seu jeito',
    vi: 'Chơi theo cách của bạn',
    id: 'Main dengan gayamu sendiri',
  },
  [LOCALE.LANDING_HERO_CAROUSEL_TEXT]: {
    en: 'Mix different heroes, items, and objectives to create your own playstyle. Every match brings new situations, keeping the gameplay fresh and engaging from start to finish.',
    ru: 'Сочетай разных героев, предметы и цели, чтобы создать собственный стиль игры. Каждый матч приносит новые ситуации, сохраняя игровой процесс свежим и увлекательным от начала до конца.',
    cz: 'Kombinuj různé hrdiny, předměty a cíle a vytvoř si vlastní styl hry. Každý zápas přináší nové situace, takže hraní zůstává svěží a poutavé od začátku do konce.',
    zh: '结合不同的英雄、装备和目标来打造属于你的玩法。每场比赛都会带来新的局势，让整个游戏过程从头到尾都保持新鲜和投入感。',
    fr: 'Mélangez différents héros, objets et objectifs pour créer votre propre style de jeu. Chaque match apporte de nouvelles situations, gardant le gameplay frais et captivant du début à la fin.',
    br: 'Misture diferentes heróis, itens e objetivos para criar seu próprio estilo de jogo. Cada partida traz novas situações, mantendo a jogabilidade sempre renovada e envolvente do começo ao fim.',
    vi: 'Kết hợp các vị tướng, trang bị và mục tiêu khác nhau để tạo nên lối chơi của riêng bạn. Mỗi trận đấu đều mang đến những tình huống mới, giúp gameplay luôn mới mẻ và cuốn hút từ đầu đến cuối.',
    id: 'Padukan hero, item, dan objektif yang berbeda untuk menciptakan gaya bermainmu sendiri. Setiap match menghadirkan situasi baru, membuat gameplay tetap segar dan menarik dari awal hingga akhir.',
  },
  [LOCALE.LANDING_HERO_CAROUSEL_ARIA_LABEL]: {
    en: 'Kingdom of Pixels heroes',
    ru: 'Герои Kingdom of Pixels',
    cz: 'Hrdinové Kingdom of Pixels',
    zh: 'Kingdom of Pixels 英雄',
    fr: 'Héros de Kingdom of Pixels',
    br: 'Heróis de Kingdom of Pixels',
    vi: 'Các tướng trong Kingdom of Pixels',
    id: 'Hero Kingdom of Pixels',
  },
  [LOCALE.LANDING_FAQ_TITLE]: {
    en: 'Frequently Asked Questions',
    ru: 'Часто задаваемые вопросы',
    cz: 'Často kladené otázky',
    zh: '常见问题',
    fr: 'Questions fréquentes',
    br: 'Perguntas frequentes',
    vi: 'Câu hỏi thường gặp',
    id: 'Pertanyaan yang sering diajukan',
  },
  [LOCALE.LANDING_FAQ_GAME_QUESTION]: {
    en: 'What kind of game is Kingdom of Pixels?',
    ru: 'Что за игра Kingdom of Pixels?',
    cz: 'Jaký typ hry je Kingdom of Pixels?',
    zh: 'Kingdom of Pixels 是什么类型的游戏？',
    fr: 'Quel type de jeu est Kingdom of Pixels ?',
    br: 'Que tipo de jogo é Kingdom of Pixels?',
    vi: 'Kingdom of Pixels là thể loại game gì?',
    id: 'Game seperti apa Kingdom of Pixels itu?',
  },
  [LOCALE.LANDING_FAQ_GAME_ANSWER]: {
    en: 'A 2D online multiplayer side-scrolling MOBA platformer focused on skill-based combat.',
    ru: 'Это 2D онлайн многопользовательский сайд-скроллинговый MOBA-платформер, ориентированный на боевую систему, зависящую от навыка.',
    cz: 'Je to 2D online multiplayer side-scrolling MOBA plošinovka zaměřená na souboje založené na dovednostech.',
    zh: '这是一款专注于技巧型战斗的 2D 在线多人横版卷轴 MOBA 平台游戏。',
    fr: 'Un MOBA platformer 2D en ligne à défilement horizontal, centré sur des combats basés sur le skill.',
    br: 'Um MOBA platformer 2D online side-scrolling focado em combate baseado em habilidade.',
    vi: 'Một game MOBA platformer cuộn cảnh ngang 2D nhiều người chơi trực tuyến tập trung vào chiến đấu dựa trên kỹ năng.',
    id: 'Game MOBA platformer side-scrolling 2D multiplayer online yang berfokus pada pertarungan berbasis skill.',
  },
  [LOCALE.LANDING_FAQ_MULTIPLAYER_QUESTION]: {
    en: 'Is Kingdom of Pixels multiplayer?',
    ru: 'Kingdom of Pixels — это мультиплеер?',
    cz: 'Je Kingdom of Pixels multiplayer?',
    zh: 'Kingdom of Pixels 支持多人游戏吗？',
    fr: 'Kingdom of Pixels est-il multijoueur ?',
    br: 'Kingdom of Pixels é multiplayer?',
    vi: 'Kingdom of Pixels có phải game multiplayer không?',
    id: 'Apakah Kingdom of Pixels multiplayer?',
  },
  [LOCALE.LANDING_FAQ_MULTIPLAYER_ANSWER]: {
    en: 'Yes, it is an online multiplayer game where players compete in real-time matches.',
    ru: 'Да, это онлайн многопользовательская игра, в которой игроки соревнуются в матчах в реальном времени.',
    cz: 'Ano, je to online multiplayer hra, kde hráči soupeří v zápasech v reálném čase.',
    zh: '是的，这是一款在线多人游戏，玩家会在实时对局中互相竞争。',
    fr: 'Oui, c’est un jeu multijoueur en ligne où les joueurs s’affrontent dans des matchs en temps réel.',
    br: 'Sim, é um jogo multiplayer online em que os jogadores competem em partidas em tempo real.',
    vi: 'Có, đây là game multiplayer trực tuyến nơi người chơi cạnh tranh trong các trận đấu thời gian thực.',
    id: 'Ya, ini adalah game multiplayer online tempat pemain bertanding dalam match real-time.',
  },
  [LOCALE.LANDING_FAQ_FRIENDS_QUESTION]: {
    en: 'Can I play with friends?',
    ru: 'Можно ли играть с друзьями?',
    cz: 'Mohu hrát s přáteli?',
    zh: '我可以和朋友一起玩吗？',
    fr: 'Puis-je jouer avec des amis ?',
    br: 'Posso jogar com amigos?',
    vi: 'Tôi có thể chơi cùng bạn bè không?',
    id: 'Bisakah saya bermain dengan teman?',
  },
  [LOCALE.LANDING_FAQ_FRIENDS_ANSWER]: {
    en: 'Yes, you can create custom lobby to play with friends. You can also queue for ranked matches.',
    ru: 'Да, ты можешь создать пользовательское лобби, чтобы играть с друзьями. Также можно вставать в очередь на рейтинговые матчи.',
    cz: 'Ano, můžeš vytvořit vlastní lobby a hrát s přáteli. Můžeš se také zařadit do fronty na hodnocené zápasy.',
    zh: '可以，你可以创建自定义大厅与朋友一起玩，也可以排队参加排位赛。',
    fr: 'Oui, vous pouvez créer un salon personnalisé pour jouer avec des amis. Vous pouvez aussi lancer une file pour des matchs classés.',
    br: 'Sim, você pode criar uma sala personalizada para jogar com amigos. Também é possível entrar na fila para partidas ranqueadas.',
    vi: 'Có, bạn có thể tạo phòng tùy chỉnh để chơi cùng bạn bè. Bạn cũng có thể xếp hàng cho các trận đấu xếp hạng.',
    id: 'Ya, kamu bisa membuat custom lobby untuk bermain bersama teman. Kamu juga bisa queue untuk match ranked.',
  },
  [LOCALE.LANDING_FAQ_COMMUNITY_QUESTION]: {
    en: 'Is there a community server?',
    ru: 'Есть ли сервер сообщества?',
    cz: 'Existuje komunitní server?',
    zh: '有社区服务器吗？',
    fr: 'Y a-t-il un serveur communautaire ?',
    br: 'Existe um servidor da comunidade?',
    vi: 'Có máy chủ cộng đồng không?',
    id: 'Apakah ada server komunitas?',
  },
  [LOCALE.LANDING_FAQ_COMMUNITY_ANSWER_PREFIX]: {
    en: 'Yes, we have a community discord where you can talk to players or developers of the game. ',
    ru: 'Да, у нас есть Discord-сообщество, где можно общаться с игроками и разработчиками игры. ',
    cz: 'Ano, máme komunitní Discord, kde můžeš mluvit s hráči i vývojáři hry. ',
    zh: '有的，我们有一个社区 Discord，你可以在那里与玩家或开发者交流。 ',
    fr: 'Oui, nous avons un Discord communautaire où vous pouvez parler avec les joueurs et les développeurs du jeu. ',
    br: 'Sim, temos um Discord da comunidade onde você pode conversar com jogadores e desenvolvedores do jogo. ',
    vi: 'Có, chúng tôi có một Discord cộng đồng nơi bạn có thể trò chuyện với người chơi hoặc nhà phát triển của trò chơi. ',
    id: 'Ya, kami memiliki Discord komunitas tempat kamu bisa berbicara dengan pemain maupun pengembang game. ',
  },
  [LOCALE.LANDING_FAQ_COMMUNITY_LINK]: {
    en: 'Discord Link',
    ru: 'Ссылка на Discord',
    cz: 'Odkaz na Discord',
    zh: 'Discord 链接',
    fr: 'Lien Discord',
    br: 'Link do Discord',
    vi: 'Liên kết Discord',
    id: 'Tautan Discord',
  },
  [LOCALE.LANDING_FAQ_MOBILE_QUESTION]: {
    en: 'Is the game playable on mobile?',
    ru: 'Можно ли играть на мобильных устройствах?',
    cz: 'Lze hru hrát na mobilu?',
    zh: '这款游戏能在手机上玩吗？',
    fr: 'Le jeu est-il jouable sur mobile ?',
    br: 'O jogo pode ser jogado no celular?',
    vi: 'Game có chơi được trên di động không?',
    id: 'Apakah game ini bisa dimainkan di ponsel?',
  },
  [LOCALE.LANDING_FAQ_MOBILE_ANSWER]: {
    en: 'No, the game is currently only playable on desktop.',
    ru: 'Нет, сейчас игра доступна только на компьютере.',
    cz: 'Ne, hra je momentálně hratelná pouze na desktopu.',
    zh: '不可以，目前这款游戏只能在桌面端游玩。',
    fr: 'Non, le jeu est actuellement jouable uniquement sur ordinateur.',
    br: 'Não, no momento o jogo só pode ser jogado no desktop.',
    vi: 'Không, hiện tại trò chơi chỉ có thể chơi trên máy tính.',
    id: 'Tidak, saat ini game hanya bisa dimainkan di desktop.',
  },
  [LOCALE.LANDING_FAQ_SIGNIN_QUESTION]: {
    en: 'How to Sign In?',
    ru: 'Как войти?',
    cz: 'Jak se přihlásit?',
    zh: '如何登录？',
    fr: 'Comment se connecter ?',
    br: 'Como fazer login?',
    vi: 'Đăng nhập như thế nào?',
    id: 'Bagaimana cara masuk?',
  },
  [LOCALE.LANDING_FAQ_SIGNIN_ANSWER_PREFIX]: {
    en: 'For persistent account, you can sign in with your Google account. You can also play game on ',
    ru: 'Для постоянного аккаунта ты можешь войти через Google. Также можно играть через ',
    cz: 'Pro trvalý účet se můžeš přihlásit pomocí Google účtu. Hru můžeš také hrát na ',
    zh: '如果你想使用长期账号，可以使用 Google 账号登录。你也可以在 ',
    fr: 'Pour un compte permanent, vous pouvez vous connecter avec votre compte Google. Vous pouvez aussi jouer au jeu sur ',
    br: 'Para uma conta permanente, você pode entrar com sua conta Google. Você também pode jogar em ',
    vi: 'Để có tài khoản lâu dài, bạn có thể đăng nhập bằng tài khoản Google. Bạn cũng có thể chơi game trên ',
    id: 'Untuk akun permanen, kamu bisa masuk dengan akun Google. Kamu juga bisa memainkan game di ',
  },
  [LOCALE.RENAME_ERROR_ALREADY_EXISTS]: {
    en: 'Name is already taken. Select another one!',
    ru: 'Это имя уже занято. Выберите другое!',
    cz: 'Toto jméno je již obsazeno. Vyberte jiné!',
    zh: '此名稱已有人使用，請另外取名！',
    fr: 'Le nom est déjà pris. Sélectionnez-en un autre!',
    br: 'Nome já está em uso. Selecione outro!',
    vi: 'Tên đã được sử dụng. Chọn một cái khác!',
    id: 'Nama sudah digunakan. Pilih yang lain!',
  },
  [LOCALE.RENAME_ERROR_INCORRECT_NAME]: {
    en: 'The name must be between 3 and 12 letters long and cannot contain forbidden letters.',
    ru: 'Имя должно быть от 3 до 12 букв и не должно содержать запрещенных символов.',
    cz: 'Jméno musí být dlouhé 3 až 12 písmen a nesmí obsahovat zakázané znaky.',
    zh: '名稱必須介於3到12個字母之間，且不能包含禁用文字。',
    fr: 'Le nom doit comporter entre 3 et 12 lettres et ne peut pas contenir de lettres interdites.',
    br: 'O nome deve ter entre 3 e 12 letras e não pode conter letras proibidas.',
    vi: 'Tên phải từ 3 đến 12 chữ cái và không được chứa chữ cái kì lạ.',
    id: 'Nama harus terdiri dari 3 hingga 12 huruf dan tidak boleh mengandung huruf yang dilarang.',
  },
  [LOCALE.RENAME_ERROR_NO_CONNECTION]: {
    en: "Can't connect with server",
    ru: 'Нет соединения с сервером',
    cz: 'Nelze se připojit k serveru',
    zh: '無法連接到伺服器',
    fr: 'Impossible de se connecter au serveur',
    br: 'Não é possível conectar-se ao servidor',
    vi: 'Không thể kết nối với máy chủ',
    id: 'Tidak dapat terhubung dengan server',
  },
  [LOCALE.LOADING]: {
    en: 'Loading...',
    ru: 'Загрузка...',
    cz: 'Načítá se...',
    zh: '載入中…',
    fr: 'Chargement...',
    br: 'Carregando...',
    vi: 'Đang tải...',
    id: 'Memuat...',
  },
  [LOCALE.CONGRATULATION]: {
    en: 'Congratulations',
    ru: 'Поздравляем',
    cz: 'Gratuluji',
    zh: '恭喜！',
    fr: 'Félicitations',
    br: 'Parabéns',
    vi: 'Chúc mừng',
    id: 'Selamat',
  },
  [LOCALE.PLAY_PAGE_RANKED_DESCRIPTION]: {
    en: ' - Reward: experience, coins and ELO\n - <b>+25% experience and coins</b>\n - Rank based matchmaking',
    ru: ' - Награды: опыт, монеты и Очки рейтинга\n - <b>+25% к получаемому опыту и монетам</b>\n - Подбор на основе ранга',
    cz: ' - Odměna: zkušenosti, mince a ELO\n - <b>+25% více zkušeností a mincí</b>\n - Dohazování na základě hodnocení',
    zh: ' - 獎勵：經驗值、金錢和ELO值\n - <b>+25% 經驗值和金錢</b>',
    fr: " - Récompense : expérience, pièces et ELO\n - <b>+25% d'expérience et de pièces</b>\n - Matchmaking basé sur le rang\n - 2 vs 2 seulement",
    br: ' - Recompensa: experiência, moedas e ELO\n - <b>+25% de experiência e moedas</b>\n - Matchmaking baseado em classificação',
    vi: ' - Phần thưởng: kinh nghiệm, xu và ELO\n - <b>+25% kinh nghiệm và xu</b>\n - Xếp hạng dựa trên kỹ năng',
    id: ' - Hadiah: pengalaman, koin, dan ELO\n - <b>+25% pengalaman dan koin</b>\n - Peringkat berdasarkan peringkat',
  },
  [LOCALE.PLAY_PAGE_UNRANKED_DESCRIPTION]: {
    en: ' - Reward: experience and coins',
    ru: ' - Награды: опыт и монеты',
    cz: ' - Odměna: zkušenosti a mince',
    zh: ' - 獎勵：經驗值和硬幣',
    fr: ' - Récompense : expérience et pièces',
    br: ' - Recompensa: experiência e moedas',
    vi: ' - Phần thưởng: kinh nghiệm và xu',
    id: ' - Hadiah: pengalaman dan koin',
  },
  [LOCALE.PLAY_PAGE_BLITZ_DESCRIPTION]: {
    en: ' - Score 15 points in under 5 minutes to win\n - Kills: 1 point, Gold Rune: 3 points, Tower: 6 points\n - 50% less experience and coins',
    ru: ' - Наберите 15 очков менее чем за 5 минут, чтобы победить\n - Убийства: 1 очко, Золотая руна: 3 очка, Башня: 6 очков\n - На 50% меньше получаемого опыта и монет',
    cz: ' - Získejte 15 bodů za méně než 5 minut pro výhru\n - Zabití: 1 bod, Zlatá runa: 3 body, Věž: 6 bodů\n - o 50% méně zkušeností a mincí',
    zh: ' - 在5分鐘内得15分獲勝\n - 擊殺：1分，黃金符文：3分，城池：6分\n - 减少 50% 的經驗值和金幣',
    fr: " - Marquez 15 points en moins de 5 minutes pour gagner\n - Tués: 1 point, Rune d'or: 3 points, Tour: 6 points\n - 50% d'expérience et de pièces en moins",
    br: ' - Ao fazer 15 pontos em menos de 5 minutos, sua equipe vence\n - Abates: 1 ponto, Runa de Ouro: 3 pontos e Torre: 6 pontos\n - 50% menos experiência e moedas',
    vi: ' - Đạt 15 điểm trong vòng dưới 5 phút để chiến thắng\n - Hạ gục: 1 điểm, Runa Vàng: 3 điểm, Trụ: 6 điểm\n - 50% kinh nghiệm và xu ít hơn',
    id: ' - Kumpulkan 15 poin dalam waktu kurang dari 5 menit untuk menang\n - Membunuh: 1 poin, Rune Emas: 3 poin, Menara: 6 poin\n - 50% kurang pengalaman dan koin',
  },
  [LOCALE.PLAY_PAGE_2VAI_DESCRIPTION]: {
    en: ' - Reward: experience and coins\n - 25% less experience and coins',
    ru: ' - Награды: опыт и монеты\n - На 25% меньше получаемого опыта и монет',
    cz: ' - Odměna: zkušenosti a mince\n - o 25 % méně zkušeností a mincí',
    zh: ' - 獎勵：經驗值和金幣\n - 减少 25% 的經驗值和金幣',
    fr: " - Récompense : expérience et pièces\n - 25% d'expérience et de pièces en moins",
    br: ' - Recompensa: experiência e moedas\n - 25% menos experiência e moedas',
    vi: ' - Phần thưởng: kinh nghiệm và xu\n - 25% kinh nghiệm và xu it hơn',
    id: ' - Hadiah: pengalaman dan koin\n - 25% kurang pengalaman dan koin',
  },
  [LOCALE.POPUP_GENERATE_NAME]: {
    en: 'Generate Name',
    ru: 'Сгенерировать имя',
    cz: 'Generovat jméno',
    zh: '產生名稱',
    fr: 'Générer un nom',
    br: 'Gerar Nome',
    vi: 'Tạo Tên',
    id: 'Buat Nama',
  },
  [LOCALE.LOGIN_ALREADY_LOGGED_IN]: {
    en: 'You are already logged in',
    ru: 'Вы уже вошли в систему',
    cz: 'Již jste přihlášeni',
    zh: '您已经登入了',
    fr: 'Vous êtes déjà connecté',
    br: 'Você já está logado',
    vi: 'Bạn đã đăng nhập',
    id: 'Anda sudah masuk',
  },
  [LOCALE.RANKED_MATCH]: {
    en: 'Ranked',
    ru: 'Рейтинговый',
    br: 'Ranqueado',
    cz: 'Hodnocený',
    zh: '排位賽',
    fr: 'Classé',
    vi: 'Xếp hạng',
    id: 'Peringkat',
  },
  [LOCALE.RANKED_QUEUE_BANNED_FOR]: {
    en: 'Banned for {}',
    ru: 'Блокировка на {}',
    br: 'Bloqueado por {}',
    cz: 'Zablokováno na {}',
    zh: '禁止排隊 {}',
    fr: 'Bloqué pendant {}',
    vi: 'Bị cấm trong {}',
    id: 'Diblokir selama {}',
  },
  [LOCALE.NORMAL_MATCH]: {
    en: 'Unranked Game',
    cz: 'Nehodnocená hra',
    zh: '非排位赛',
    fr: 'Partie non classée',
    ru: 'Не ранговая игра',
    br: 'Partida sem classificação',
    vi: 'Đánh thường',
    id: 'Permainan Tidak Berperingkat',
  },
  [LOCALE.PLAY_PAGE_PLAY_A_GAME]: {
    en: 'Play a Game!',
    ru: 'Играть!',
    br: 'Jogar uma partida!',
    cz: 'Hrát hru!',
    zh: '開始遊戲！',
    fr: 'Jouer une partie!',
    vi: 'Chơi một ván!',
    id: 'Mainkan game!',
  },
  [LOCALE.CASUAL_MATCH]: {
    en: 'Casual',
    ru: 'Повседневный',
    br: 'Casual',
    cz: 'Volný',
    zh: '隨意遊玩',
    fr: 'Décontracté',
    vi: 'Đánh Thường',
    id: 'Santai',
  },
  [LOCALE.BLITZ_MATCH]: {
    en: 'Blitz',
    ru: 'Блиц',
    br: 'Blitz',
    cz: 'Blitz',
    zh: '閃電',
    fr: 'Blitz',
    vi: 'Ván Nhanh',
    id: 'Blitz',
  },
  [LOCALE.AI_MATCH]: {
    en: 'AI Matches (PvAI):',
    ru: 'Игры против ботов:',
    br: 'Partida contra Bot (PvAI):',
    cz: 'Zápasy proti AI (PvAI):',
    zh: 'AI 對戰 (人對電腦)：',
    fr: "Matchs contre l'IA (PvIA):",
    vi: 'Trận đấu với AI (PvAI):',
    id: 'Pertandingan AI (PvAI):',
  },
  [LOCALE.BLITZ_PLAYERS_AND_TIME]: {
    en: '5min - 2V2',
    ru: '5мин - 2на2',
    br: '5min - 2V2',
    cz: '5min - 2v2',
    zh: '5分鐘 - 2v2',
    fr: '5min - 2v2',
    vi: '5 phút - 2v2',
    id: '5 menit - 2v2',
  },
  [LOCALE.RANKED_PLAYERS_AND_TIME]: {
    en: '10min - 2V2',
    ru: '10мин - 2 на 2',
    br: '10min - 2V2',
    cz: '10min - 2v2',
    zh: '10分鐘 - 2v2',
    fr: '10min - 2v2',
    vi: '10 phút - 2v2',
    id: '10 menit - 2v2',
  },
  [LOCALE.CASUAL_PLAYERS_AND_TIME]: {
    en: '8/10min - 1V1/2V2',
    ru: '8/10мин - 1на1/2на2',
    br: '8/10min - 1V1/2V2',
    cz: '8/10min - 1V1/2V2',
    zh: '8/10分鐘 - 1V1/2V2',
    fr: '8/10min - 1V1/2V2',
    vi: '8/10phút - 1V1/2V2',
    id: '8/10menit - 1V1/2V2',
  },
  [LOCALE.COOP_PLAYERS_AND_TIME]: {
    en: '10min - 2V2AI',
    ru: '10мин - 2 на 2 с ИИ',
    br: '10min - 2V2IA',
    cz: '10min - 2V2AI',
    zh: '10分鐘 - 2对2AI',
    fr: '10min - 2V2IA',
    vi: '10 phút - 2V2AI',
    id: '10menit - 2V2AI',
  },
  [LOCALE.ACTIVATE_ITEM]: {
    en: 'Activate Item',
    ru: 'Активировать',
    br: 'Ativar Item',
    cz: 'Aktivovat položku',
    zh: '啟用物品',
    fr: "Activer l'objet",
    vi: 'Kích hoạt đồ',
    id: 'Aktifkan Item',
  },
  [LOCALE.ACTIVE_ITEM]: {
    en: 'Item Active',
    ru: 'Предмет активен',
    br: 'Item Ativo',
    cz: 'Položka aktivní',
    zh: '物品啟用中',
    fr: 'Objet actif',
    vi: 'Kích hoạt đồ',
    id: 'Item Aktif',
  },
  [LOCALE.CURRENT_SEASON]: {
    en: 'Ongoing Season {} ends in ',
    ru: 'Текущий сезон {} заканчивается через ',
    br: 'Temporada atual {} termina em ',
    cz: 'Probíhající sezóna {} končí za ',
    zh: '正在进行的第 {} 季将在 ',
    fr: 'La saison en cours {} se termine dans ',
    vi: 'Mùa hiện tại {} kết thúc trong ',
    id: 'Musim {} berakhir dalam ',
  },
}
