/* eslint-disable no-irregular-whitespace */
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-nocheck
import { LOCALE } from '../locales'
import { home_page } from './home_page'

const locale_data: { [key in LOCALE]: { [key in string]: string } } = {
  ...home_page,
  /** Hero section */
  [LOCALE.KUMIHU_NAME]: {
    en: 'Kumihu',
    ru: 'Кумиху',
    zh: '庫咪戶',
    br: 'Kumihu',
    cz: 'Kumihu',
    fr: 'Kumihu',
  },
  [LOCALE.BELLE_NAME]: {
    en: 'Belle',
    ru: 'Белла',
    zh: '蓓蕾',
    br: 'Belle',
    cz: 'Belle',
    fr: 'Belle',
  },
  [LOCALE.ICEAT_NAME]: {
    en: "I'Ceat",
    ru: "Ай'сит",
    br: 'ICeat',
    cz: "I'Ceat",
    zh: '艾希特',
    fr: "I'Ceat",
  },
  [LOCALE.VEIL_NAME]: {
    en: 'Veil',
    ru: 'Вэйл',
    zh: '維爾',
    br: 'Veil',
    cz: 'Veil',
    fr: 'Voile',
  },
  [LOCALE.SPARROW_NAME]: {
    en: 'Sparrow',
    ru: 'Спарроу',
    zh: '史佩羅',
    br: 'Sparrow',
    cz: 'Vrabec',
    fr: 'Moineau',
  },
  [LOCALE.THOMAS_NAME]: {
    en: 'Thomas',
    ru: 'Томас',
    br: 'Thomas',
    cz: 'Tomáš',
    zh: '湯瑪士',
    fr: 'Thomas',
  },
  [LOCALE.FLIN_NAME]: {
    en: 'Flin',
    ru: 'Флин',
    zh: '弗林',
    br: 'Flin',
    cz: 'Flin',
    fr: 'Flin',
  },
  [LOCALE.KIRA_NAME]: {
    en: 'Kira',
    ru: 'Кира',
    zh: '奇菈',
    br: 'Kira',
    cz: 'Kira',
    fr: 'Kira',
  },
  [LOCALE.HAZEL_NAME]: {
    en: 'Hazel',
    ru: 'Хейзел',
    zh: '哈歇爾',
    br: 'Hazel',
    cz: 'Hazel',
    fr: 'Hazel',
  },
  [LOCALE.AREL_NAME]: {
    en: 'Arel',
    ru: 'Арел',
    zh: '艾瑞爾',
    br: 'Arel',
    cz: 'Arel',
    fr: 'Arel',
  },
  [LOCALE.ALVAR_NAME]: {
    en: 'Alvar',
    ru: 'Алвар',
    zh: '阿爾瓦',
    br: 'Alvar',
    cz: 'Alvar',
    fr: 'Alvar',
  },
  [LOCALE.FOXY_NAME]: {
    en: 'Foxy',
    cz: 'Foxy',
    zh: 'Foxy',
    ru: 'Фокси',
    fr: 'Foxy',
    br: 'Foxy',
  },
  [LOCALE.MAGDALENA_NAME]: {
    en: 'Magdalene',
    ru: 'Магдалина',
    cz: 'Magdalena',
    zh: '玛格达琳',
    fr: 'Magdalène',
    br: 'Magdalena',
  },
  [LOCALE.UNK_DESCRIPTION]: {
    en: 'Will be added soon!',
    ru: 'Скоро будет добавлено!',
    br: 'Será adicionado em breve!',
    cz: 'Brzy bude přidáno!',
    zh: '即将加入，敬请期待！',
    fr: 'Sera bientôt ajouté!',
  },
  [LOCALE.KUMIHU_DESCRIPTION]: {
    en: 'Kumihu is an evil spirit in the guise of a beautiful woman who is always hungry for new souls. But be careful: in the blink of an eye she can show her true form, destroying any chance to survive, since the Soul Sphere will catch even the most tenacious fools.',
    ru: 'Кумиху - злой дух, принявший облик прекрасной женщины, жаждущий новых душ. Но будьте осторожны: в мгновение ока она может показать свою истинную форму, уничтожив любой шанс на выживание, поскольку Сфера души поймает даже самых упорных дураков.',
    br: 'Um demonio da floresta que foi capturado pelo reino vemelho, Kumihu conseguiu fugir roubando o corpo de uma duqueza para se vingar das pessoas que a fizeram mal.',
    cz: 'Kumihu je zlý duch v převleku krásné ženy, která neustále touží po nových duších. Ale buďte opatrní: mrknutím oka může ukázat svou pravou podobu a zničit jakoukoli šanci na přežití, protože její sféra duše zachytí i ti nejhouževnatější blázni.',
    zh: '　　庫咪戶是一個偽裝成貌美女性的惡靈，總是渴求著新鮮的靈魂。萬分注意：一旦被靈魂球體逮到，只需眨眼之間，她就能現出真實面目將任何一絲存活的機會通通摧毀，縱使是最頑強的愚者也不例外。',
    fr: "Kumihu est un esprit maléfique se faisant passer pour une belle femme qui a toujours faim de nouvelles âmes. Mais attention : en un clin d'œil, elle peut montrer sa véritable forme, détruisant ainsi toute chance de survie, car la Sphère d'âme attrapera même les plus tenaces des fous.",
  },
  [LOCALE.ICEAT_DESCRIPTION]: {
    en: "Belonging to a colony of penguins in the arctic region of Civia, I'ceat stood out among the rest. Possessing magical powers, I'ceat can manifest ice and snow at the tip of his flippers. No one knows where his powers came from, but everyone embraces his uniqueness among the group. Waddling past the tall trees in the dense forest, I'ceat is determined to find the true meaning behind the powers he once used to protect his family.",
    ru: "Принадлежащий к колонии пингвинов в арктическом регионе Кливии, Ай'сит выделялся среди остальных. Обладая магическими способностями, Ай'сит может создавать лёд и снег на кончиках ласт. Никто не знает, откуда взялись его силы, но все в группе принимают его уникальность. Пробираясь мимо высоких деревьев в густом лесу, Ай'сит наполнен решимостью разыскать истинный смысл своих сил, которые он когда-то использовал для защиты своей семьи.",
    br: "Pertencente a uma colônia de pinguins na região ártica de Civia, I'ceat se destacou entre os demais. Possuindo poderes mágicos que apenas demônios tem, I'ceat pode manifestar pedras de gelo e neve da ponta de suas nadadeiras. Ninguém sabe de onde veio seus poderes, mas todos o aceitam no grupo acreditando não ter ligação com os demônios. Passando pelas árvores altas da floresta das fadas, I'ceat está determinado a encontrar o verdadeiro significado por trás dos poderes que ele usou para proteger sua colônia.",
    cz: "I'ceat patřil ke kolonii tučňáků v arktické oblasti Civia, ale vždy vyčníval mezi ostatními. Díky magickým schopnostem dokáže I'ceat vztvořit led a sníh na špičce svých křidel. Nikdo neví, kde se jeho schopnosti vzaly , ale každý přijímá jeho jedinečnost ve kmenu. Kolébájíc se kolem vysokých stromů v hustém lese je I'ceat odhodlán najít skutečný význam za schopnostmi, které kdysi používal k ochraně své rodiny.",
    zh: '　　隸屬於北極地帶希維亞的企鵝群，艾希特在企鵝群中脫穎而出。擁有魔法之力，艾希特可以在他的腳蹼間現出冰雪。沒人知曉他的能力從何而來，但大家都接納他在群體中的獨特性。搖搖擺擺地走過了重重的高樹茂林，艾希特下定了決心，去尋找他那曾經用來保護整個家族的力量其背後的真實意涵。',
    fr: "Appartenant à une colonie de pingouins dans la région arctique de Civia, I'ceat se démarquait des autres. Possédant des pouvoirs magiques, I'ceat peut manifester de la glace et de la neige à l'extrémité de ses palmes. Personne ne sait d'où viennent ses pouvoirs, mais tout le monde accepte son unicité au sein du groupe. En se dandinant devant les grands arbres de la forêt dense, I'ceat est déterminé à trouver la véritable signification derrière les pouvoirs qu'il utilisait autrefois pour protéger sa famille.",
  },
  [LOCALE.THOMAS_DESCRIPTION]: {
    en: "Coming from an underground laboratory in the heated war zone of Rotite, Thomas fought for Etygia's guerilla force and partook in ambushes focused on the upper ranks of the enemy forces. He gained notoriety among allies and foes alike because of his unique style of killing. During a secret experiment gone wrong, the test subject blasted the laboratory wide open. Wanting to leave the hectic environment and hellish landscape, Thomas dared to leave the guerilla force for good. Through the spray of bullets, he managed to swiftly make it past as he witnessed the loss of many lives in the chaos. For Thomas, he wanted freedom, but at the cost of betraying the kingdom. Keeping a low profile and lurking in the shadows, it's only a matter of time. The hunter has become the hunted.",
    ru: 'Выйдя из подземной лаборатории в жаркой зоне боевых действий Ротита, Томас сражался на стороне партизан Этигии и участвовал в засадах, сосредоточенных на верхних званиях вражеских сил. Он получил известность как среди союзников, так и среди врагов из-за своего уникального стиля убийств. Во время секретного эксперимента, который закончился неудачей, испытуемый полностью взорвал лабораторию. Желая покинуть суету и адские пейзажи, Томас осмелился навсегда покинуть партизанские отряды. Ему удалось быстро миновать осколки пуль, становясь свидетелем гибели многих людей в происходящем хаосе. Томас просто хотел свободы, даже ценой предательства целого королевства. Незаметность и скрытность в тени - это лишь вопрос времени. Охотник превратился в добычу.',
    br: 'Vindo de um laboratório subterrâneo na zona de guerra aquecida de Rotite, Thomas foi obrigado a lutar pelas forças de guerrilha de Etygia e sua especialidade era de emboscadas focadas nas fileiras superiores das forças inimigas. Ele ganhou notoriedade entre aliados e inimigos por causa de seu estilo único de luta com uma espada demoníaca. Durante um experimento secreto que deu errado, uma das cobaias explodiu um laboratório subterrâneo perto de onde ele patrulhava. Ele testemunhou a perda de muitas vidas no caos. Thomas aproveitou a oportunidade e se atreveu a deixar as forças de guerrilha, mas ao custo de trair o reino e virar um fugitivo.',
    cz: 'Tomáš, králík pocházející z podzemní laboratoře ve válečné zóně Rotite, bojoval za partyzánské síly Etygie a účastnil se přepadení zaměřených na vyšší řady nepřátelských sil. Díky svému jedinečnému stylu zabíjení si získal proslulost mezi spojenci i nepřáteli. Během tajného experimentu, který se pokazil, testovaný subjekt znicil laboratoř. Thomas chtěl opustit hektické prostředí a pekelnou krajinu a odvážil se navždy opustit partyzány. Přes spršku kulek se mu podařilo rychle uniknout, když byl svědkem ztráty mnoha životů v chaosu. Bunninju chtěl svobodu, ale za cenu zrady království. Držejic se nízko a číhat ve stínu, je to jen otázka času. Z lovce se stal lovený.',
    zh: '　　來自洛泰特激烈戰區的地下實驗室，湯瑪士作為艾提吉亞的游擊隊勢力一員作戰，並專門伏擊敵方勢力的高級階層。他因為其獨特的殺戮風格，在敵友之間皆惡名昭彰。在某一次機密實驗出錯時，受試者爆裂將實驗室炸毀了。渴望著離開這奔波不斷的環境以及猶如地獄般的光景，湯瑪士毅然決然離開了游擊隊勢力。他設法迅速離開，穿越過了漫天四散的子彈，同時親眼目睹了許多性命被葬送在這場混亂當中。對湯瑪士而言，他想要自由，然而代價則是背叛了整個王國。要時時刻刻保持低調潛伏在影子中，一個獵殺者反成了獵物，只會是時間上的問題。',
  },
  [LOCALE.SPARROW_DESCRIPTION]: {
    en: `A courageous and fierce woman previously a Hermit, Sparrow committed most of her life following the demon Artuklas. She and her family lived in a village deep within the dense Sasugroen Rainforest. Her strong sense of adventure distinguished her from the timid and discreet natured children of her generation. Together with her family, they pursued the path that Artuklas set for the Hermits.
        <br />Artuklas, being akin to discovery and knowledge, was intrigued by the curious Sparrow and her bravery to venture out, seeking the unknown and discovering information. He slowly forged his path to cater to Sparrow's needs, dismissing the other Hermits who wanted to follow and worship him. Sparrow noticed the changes, but Artuklas assured her that destiny chose this path for her to take. During the following years of training and preparing, the bond between the hermit and demon grew closer, and Artuklas divulged information about his kin to Sparrow.
        <br />Unfortunately, even with the training and rituals all complimenting Sparrow's strengths, the child could not fully grasp the power Artuklas extends to share. Artuklas, growing impatient and infuriated at the child's incompetency, decided to force a fraction of his power to flow through her body. This power would prove too much for Sparrow, and she would have to expel a lot of this to stay conscious.
        <br />A small scouting team of Guardians would take notice of the immense demonic energy concentrated in one spot. Upon arrival, they would see the shape of a greater demon trying to take control of a collapsed woman. They seized the opportunity to strike, but Sparrow retaliated, allowing Artuklas to escape in the chaos. After a long-drawn-out fight, the Guardians would subdue and overpower her because she could not effectively use her newfound abilities.`,
    ru: `Спарроу - смелая и свирепая девушка, в прошлом отшельник, большую часть своей жизни посвятившая следованию демону Артукласу. Она и ее семья жили в деревне глубоко в густом тропическом лесу Сасугроен. Её сильное стремление к приключениям отличало её от робких и сдержанных детей её возраста. Вместе с её семьей они пошли по пути, который Артуклас указал отшельникам.
        <br />Артукласу были по душе открытия и новые знания, и он был очень заинтригован любопытной Спарроу и ее храбростью, когда она отправлялась на поиски неизвестного. Он медленно прокладывал свой путь, чтобы удовлетворить потребности Спарроу, увольняя других отшельников, которые хотели следовать за ним и поклоняться ему. Спарроу замечала изменения, но Артуклас заверял, что сама судьба избрала для неё этот путь. В последующие годы обучения и подготовки связь между отшельницей и демоном стала теснее, и Артуклас выдал Спарроу информацию о своём с ней родстве.
        <br />К сожалению, даже с обучением и ритуалами, дополняющими сильные стороны Спарроу, ребёнок не мог полностью осознать силу, которой Артуклас делится. Артуклас, теряя терпение и гневаясь из-за некомпетентности ребёнка, решил заставить часть своей силы течь через её тело. Эта сила оказалась бы слишком большой для Спарроу, и ей пришлось бы исключить многое из этого, чтобы оставаться в сознании.
        <br />Небольшая разведывательная группа стражей вскоре заметит огромную демоническую энергию, сосредоточенную в одном месте. По прибытии они увидят очертания огромного демона, пытающегося взять под контроль лежащую в обмороке девушку. Они воспользовались возможностью нанести удар, но Спарроу контратаковала, позволив Артукласу сбежать в хаосе. После затяжной битвы стражи подавили и усмирили её пыл, поскольку она не могла эффективно использовать свои новообретённые способности.`,
    br: `Elizabeth Dolores Sperrow II, uma mulher corajosa e feroz do reino de Etygia, teve um casamento político com o Rei de Eilys Edgar III, com o tempo ela se apaixonou por ele mas tudo mudou depois que seu marido foi assassinado por um demônio da floresta.
        <br A Rainha de Eilys ficou sedenta por vingança, sem saber o motivo pelo qual seu marido foi assassinado, ela declarou guerra aos seres mágicos, agora ela luta na linha de frente para se vingar e descobrir a verdade.`,
    zh: `　　曾經作為一名隱士，史佩羅勇敢而兇猛，過往一直追隨著惡魔阿圖克拉斯。她與她的家人住在薩蘇古隆恩熱帶雨林深處的一個村落，她那強大的冒險意識將她與她那一代膽小而謹慎的孩子們區分了開來。隨著她的家族一行，他們追隨著阿圖克拉斯替隱士們設下的道路。
        <br />　　阿圖克拉斯，近乎於探索與見聞，對於史佩羅勇敢冒險，尋求未知以及探索情報的好奇心感到興趣。他漸漸打造出一條專門迎合史佩羅需求的道路，將其他想要追隨崇拜他的隱士們通通遣送走。史佩羅注意到了這些變動，但阿圖克拉斯向她保證，是命運選擇了這條道路，迎接她的到來。在接下來這幾年來的訓練及準備中，隱士與惡魔的關係越來越緊密，而阿圖克拉斯則透漏與史佩羅結識為親屬關係的消息。
        <br />　　不幸的是，縱然在訓練與儀式當中史佩羅的力量一致受到大家讚揚，這個孩子依然無法完全掌握阿圖克拉斯共享給她的能量。阿圖克拉斯開始感到不耐煩，被孩子的無能給激怒了，決定將他一小部分份的能量強行灌輸到她的身體。這份能量對史佩羅來說太多了，她必須將大量的能量驅散才能保持意識清醒。
        <br />　　一組守衛者的小偵查隊注意到了匯集在一點的邪惡能量。到達之後，他們看到了一個更大的惡魔形體正在試圖操控一個已經倒下的女人。他們逮到了機會迎擊，但史佩羅展開了反擊，使得阿圖克拉斯在這場混亂當中逃脫而出。在一場曠日持久的戰鬥後，守衛隊制伏並打敗了她，因為她無法有效使用她那新發現的能力。`,
  },
  [LOCALE.BELLE_DESCRIPTION]: {
    en: "Part of an ancient race of fay creatures in the ancient woods, Belle was born with arcane control over plants unmatched by any before her, she was a kindred elementalist and used her knowledge of nature to heal those in need, however both sides tried to recruit her but failed and while the guardians were merely disappointed, the hermits made repetitive attempts to augment her into their forces. Eventually the cultists decided to remove the threat and they brought a trio of hermit leaders: Flin, Kumihu, and Puppeteer to either taint her of kill her, Belle successfully defeated Flin before succumbing to the charm spells cast by Kumihu with her last fragment of consciousness she threw a pod at Kumihu which exploded in her face, as Belle got back onto her feet she was bound by strings materializing from Puppeteer's fingers and lost control over her body, as she was forced to walk back to the hermit camp she struggled against the glowing threads but she was no match for a major demon. At the hands of the hermits Belle was tortured and violated until her original happy and joyous self was trapped in the deepest corners of her mind while a new hateful personality arose and she was never the same again, maybe some arcane healer might come along and reawaken her old self or perhaps she shall be trapped as an insane hermit for eternity.",
    br: 'Parte de uma antiga raça de criaturas fay na floresta antiga, Belle nasceu com controle sobre as plantas, seu pai era um humano e sua mãe uma fada, depois de ter dois filhos, sua mãe escondeu sua família em uma parte isolada da floresta magica, quando ela e seu irmão cresceram, seu pai desapareceu misteriosamente sem deixar pistas, agora Belle e seu irmão procuram por seu pai e tentam esconder sua verdadeira identidade.',
    ru: "Она, — частичка древней расы сказочных существ, живущих в древних лесах, родилась с волшебным даром контроля над растениями, и никто из её вида прежде не имел этой способности. Она была потомственной повелительницей элементов и использовала свои знания о природе, чтобы исцелять нуждающихся. Обе стороны предпринимали попытки завербовать её, но они были тщетны. В то время как стражи опустили руки, отшельники предпринимали неоднократные попытки усилить её, пытаясь сделать частью своей армии. В конце концов культисты решили решить всё раз и навсегда и привели троих лидеров-отшельников: Флина, Кумиху и Кукловода, чтобы либо осквернить ее до конца, либо убить. Белла успешно победила Флина, и прежде чем поддаться очаровывающим заклинаниям Кумиху, она смогла бросить взрывной бутон прямо в лицо ведьме. Нити Кукловода, появившиеся из его пальцев, оплетали Беллу, и в конце концов она потеряла контроль над своим телом. Ей был отдан приказ возвращаться в лагерь отшельников. Светящиеся нити не давали ей и шанса хоть как-то дать отпор и победить главного демона, и она вынуждена была подчиниться. Отшельники многочисленными истязаниями превратили прежде жизнерадостную и отзывчивую личность Беллы в нечто бесчувственное и ненавистное. Может быть, когда-то какой-нибудь целитель-волшебник и сможет пробудить её от зловещего контроля, но пока Белла остаётся узницей своих глубоких уголков разума, где её 'я' уже, возможно, никогда не станет прежним.",
    zh: '　　作為住在神木中古老種族的妖精生物，蓓蕾生來就擁有任何植物無法比擬的奧術操控能力。她曾是有血統的元素師，並使用她大自然的知識治癒傷患，然而兩派勢力試圖徵召她加入都失敗了。而當守衛者一方打消主意之時，隱士們還是反覆試圖將她納入成為他們的一己之力。最終，邪教徒們決定抹除這份威脅，而他們帶來了三位領袖：弗林、庫咪戶與傀儡師來玷汙或抹殺她。在屈服於庫咪戶的魅惑咒術前，蓓蕾擊敗了弗林，並竭盡她那最後支離破碎的意識將一顆豆莢扔向庫咪戶，在她臉上炸裂。當蓓蕾要重新起身時，她被傀儡師手上操控的細線給束縛住，身體不得動彈。她被迫走回隱士的營地，她奮力掙扎抵抗發光的絲線，但在強大惡魔的面前，她完全無法抗衡。成了隱士們的囊中之物後，蓓蕾不斷受到凌辱與侵犯，直到她原本的快樂與喜悅都被困在最深處的角落。此時，她誕生了另一個充滿仇恨的人格，她已經不再是原本的她了。或許某位奧術治癒師會跟隨而來，重新將原本的她喚醒，又或許她會永遠受困，成為了一名瘋狂的隱士。',
  },

  [LOCALE.KIRA_DESCRIPTION]: {
    en: 'As a young girl, Kira used to sit at the window of her home and watch the lightning. As she grew up, she began a hobby of chasing storm clouds, hoping to see flashes of electricity in the sky. The rain did not bother her, the wind could not deter her, only when she felt the true power of the storm did she stop. As Kira reached the highest peak of a mountain, she was struck by the thunder she chased. As she fell, she was found by a hermit and brought back to a hidden encampment watched over by a demonic vassal. She was forged into whatever they wanted her to be against any free will. They made her into an electromancer, to aid the dark forces. They did not expect her to fight back as she called forth fury from above. Most of the hermits were caught unprepared and annihilated while the demonic leader named Draklavain strode through the barrage and would have killed her if not for hunting party of guardians attracted by the chaos. As she left with them, she found a tome and with it became an important asset to the crusade against the demons, although some say the tome found her.',
    br: 'Ex-general do exército do rei. Agora professora da Escola Mágica de demonologia do reino de Eilys, Kira é uma renomada instrutora, possuindo o demônio relâmpago selado em seu livro, ela procura ensinar a seus alunos a melhor maneira de usar o poder dos selados.',
    ru: 'В юности Кира любила сидеть у окна своего дома и наблюдать за молниями, а повзрослев, увлеклась погоней за грозовыми тучами в надежде увидеть в небе вспышки молний. Дождь её совершенно не беспокоил, а ветер не мог удержать её порыв. Лишь только почувствовав истинную силу бури она смогла остановиться. Она и не заметила, как достигла самой высокой вершины горы. Гром, за которым она гналась, поразил её, из-за чего она сорвалась и упала, потеряв сознание, но чудом выжив. Её обнаружил отшельник и отнёс в скрытый лагерь под покровительством демонического вассала. Против её воли они провели тёмный ритуал,  превратив в электроманта, в надежде, что она поможет тёмным силам. Неожиданным стал для всех оказанный ею отпор: вызванная ярость с небес застала врасплох многих отшельников, стерев их с лица земли в одно мгновение. В это время, лидер демонов Драклавейн пробирался через заградительный огонь из вспышек молний в надежде уничтожить отступницу. К счастью, стражи, охотящиеся на силы хаоса нашли её и помогли сбежать, сокрыв от опасности. Во время побега Кира обнаружила старинную книгу на своём пути, которую она сумела использовать в дальнейшем походе против армии демонов. Поговаривают, что не она нашла книгу, а книга нашла её.',
    zh: '　　曾是年輕少女時，奇菈習慣坐在她家中的窗邊觀望閃電。長大後，追尋雷雲，期望能夠在空中看見閃電成為她的愛好，就連風雨也無法撼動她那蓬勃的心，直到她感受到暴風的真實之力後才會就此打住。當她爬向山頂的巔峰，她被她不斷追逐的閃電擊中，她沉寂後被一名隱士發現，並帶回了一個祕密營地交由惡魔附庸看守。違背了她的自由意志，他們想將她鍛造成任何他們想要的樣子，使她成為協助闇黑勢力的雷電巫師。但他們沒料想到她會召喚雷霆之怒展開逆襲，大部分的隱士因而毫無防備的被擒獲與殲滅，若不是此時此刻，惡魔首領「德拉克拉文」正為了被混沌勢力吸引而來的守衛狩獵隊而穿越槍林彈雨，他大概早已斷送她的性命。當她與守衛者們同行離開後，她發現了一本魔道書，而有了這本書，它將會成為與惡魔黨決一聖戰的重要資產。雖然有人是這麼說的：「是這本書找到了她。」',
  },

  [LOCALE.DAMAGE_TYPE_NORMAL]: {
    en: 'Normal',
    ru: 'Физический',
    br: 'Normal',
    cz: 'Normální',
    zh: '一般攻擊',
    fr: 'Normal',
  },
  [LOCALE.DAMAGE_TYPE_MAGICAL]: {
    en: 'Magical',
    ru: 'Магический',
    br: 'Mágica',
    cz: 'Magický',
    zh: '魔法攻擊',
    fr: 'Magique',
  },
  [LOCALE.DAMAGE_TYPE_PURE]: {
    en: 'Pure',
    ru: 'Чистый',
    br: 'Puro',
    cz: 'čistý',
    zh: '純攻擊',
    fr: 'Pur',
  },
  [LOCALE.DAMAGE_TYPE_DASH]: {
    en: 'Dash',
    ru: 'Рывок',
    br: 'Dash',
    cz: 'Skok',
    zh: '衝刺',
    fr: 'Dash',
  },
  [LOCALE.DAMAGE_TYPE_HEAL]: {
    en: 'Heal',
    ru: 'Исцеление',
    br: 'Cura',
    cz: 'Léčení',
    zh: '治癒',
    fr: 'Soigner',
  },
  [LOCALE.DAMAGE_TYPE_BUFF]: {
    en: 'Buff',
    ru: 'Усиление',
    br: 'Buff',
    cz: 'Posílení',
    zh: '強化',
    fr: 'Buff',
  },
  [LOCALE.COOLDOWN]: {
    en: 'Cooldown',
    ru: 'Перезарядка',
    br: 'Recarga',
    cz: 'Cooldown',
    zh: '冷卻時間',
    fr: 'Temps de recharge',
  },
  [LOCALE.LEVEL]: {
    en: 'Level',
    ru: 'Уровень',
    br: 'Nível',
    cz: 'Úroveň',
    zh: '等級',
    fr: 'Niveau',
  },
  [LOCALE.RED_TEAM]: {
    en: 'Red Team',
    ru: 'Красная команда',
    br: 'Time Vermelho',
    cz: 'Rudý tým',
    zh: '紅隊',
    fr: 'Équipe Rouge',
  },
  [LOCALE.BLUE_TEAM]: {
    en: 'Blue Team',
    ru: 'Синяя команда',
    br: 'Time Azul',
    cz: 'Modrý tým',
    zh: '藍隊',
    fr: 'Équipe Bleue',
  },
  [LOCALE.SECOND]: {
    en: 'Seconds',
    ru: 'сек.',
    br: 'Segundos',
    cz: 'Vteřin',
    zh: '秒',
    fr: 'Secondes',
  },
  [LOCALE.WARNING_NOT_IN_BASE]: {
    en: 'You can not buy items outside base!',
    ru: 'Вы не можете покупать предметы вне своей базы!',
    br: 'Você não pode comprar itens fora da base!',
    cz: 'Nemůžete nakupovat předměty mimo základnu!',
    zh: '你不能在你的基地外購買物品！',
    fr: "Vous ne pouvez pas acheter d'articles en dehors de la base !",
  },
  [LOCALE.WARNING_TOWER_ATTK]: {
    en: "Careful! You've been targeted by a tower! Fall back!",
    ru: 'Осторожно! Вы были атакованы башней! Отступайте!',
    br: 'Cuidado! Você é alvo de uma torre.',
    cz: 'Pozor! Byli jste zacílen věží! Ustupte!',
    zh: '小心！你已被城池鎖定目標！快逃！',
    fr: 'Attention ! Vous êtes pris pour cible par une tour ! Reculez !',
  },
  [LOCALE.LOGOUT]: {
    en: 'Logout',
    ru: 'Выход',
    br: 'Sair',
    cz: 'Odhlásit se',
    zh: '登出',
    fr: 'Déconnexion',
  },
  [LOCALE.GENERATE_LINK_CODE]: {
    en: 'Generate Link Code',
    cz: 'Vygenerovat kód odkazu',
    zh: '生成链接代码',
    ru: 'Сгенерировать код ссылки',
    fr: 'Générer le code de lien',
    br: 'Gerar código de link',
  },
  [LOCALE.LINK_CODE_DESCRIPTION]: {
    en: 'This link code expires in {} minutes. To sign in with a link code, select the EU SERVER and use the "Login with Link Code" option. Be sure to close this tab first!',
    cz: 'Tento odkazový kód vyprší za {} minut. Pro přihlášení pomocí odkazového kódu vyberte EU SERVER a použijte možnost "Přihlásit se pomocí odkazového kódu". Nezapomeňte nejprve zavřít tuto kartu!',
    zh: '此链接代码将在{}分钟后过期。要使用链接代码登录，请选择EU SERVER并使用“使用链接代码登录”选项。请确保先关闭此选项卡！',
    ru: 'Срок действия этого кода ссылки истекает через {} минут. Чтобы войти с помощью кода ссылки, выберите EU SERVER и используйте опцию "Войти с помощью кода ссылки". Обязательно закройте эту вкладку!',
    fr: 'Ce code de lien expire dans {} minutes. Pour vous connecter avec un code de lien, sélectionnez le serveur EU et utilisez l\'option "Connexion avec un code de lien". Assurez-vous de fermer cet onglet en premier !',
    br: 'Este código de link expira em {} minutos. Para fazer login com um código de link, selecione o EU SERVER e use a opção "Login com código de link". Certifique-se de fechar esta guia primeiro!',
  },
  [LOCALE.LINK_CODE_ERR]: {
    en: 'Could not generate link code.',
    cz: 'Nepodařilo se vygenerovat kód odkazu.',
    zh: '无法生成链接代码。',
    ru: 'Не удалось сгенерировать код ссылки.',
    fr: 'Impossible de générer le code de lien.',
    br: 'Não foi possível gerar o código do link.',
  },
  [LOCALE.FLOATING_NUMBERS]: {
    en: 'Floating Numbers',
    ru: 'Всплывающие числа',
    br: 'Números Flutuantes',
    cz: 'Plovoucí čísla',
    zh: '流動號碼',
    fr: 'Nombres flottants',
  },
  [LOCALE.FULL_SCREEN]: {
    en: 'Toggle Full Screen',
    ru: 'Полноэкранный режим',
    br: 'Tela cheia',
    cz: 'Zapnout režim plné obrazovky',
    zh: '釘選全螢幕',
    fr: 'Activer le mode plein écran',
  },
  [LOCALE.MOUSE_SUPPORT]: {
    en: 'Mouse Support',
    ru: 'Поддержка мыши',
    br: 'Suporte para Mouse',
    cz: 'Podpora Myši',
    zh: '滑鼠支援',
    fr: 'Support de la souris',
    cz: 'Podpora myši',
    ru: 'Поддержка мыши',
    br: 'Suporte para Mouse',
  },
  [LOCALE.GLOBAL_CHAT]: {
    en: 'Global Chat',
    ru: 'Глобальный чат',
    br: 'Chat Global',
    cz: 'Globální chat',
    zh: '全球聊天',
    fr: 'Chat mondial',
    ru: 'Глобальный чат',
    br: 'Chat Global',
  },
  [LOCALE.HOME]: {
    en: 'Home',
    ru: 'Домой',
    br: 'Inicio',
    cz: 'Domů',
    zh: '首頁',
    fr: 'Accueil',
  },
  [LOCALE.PLAY]: {
    en: 'Play',
    ru: 'Играть',
    br: 'Jogar',
    cz: 'Hrát',
    zh: '遊玩',
    fr: 'Jouer',
  },
  [LOCALE.LEADERBOARD]: {
    en: 'Leaderboard',
    ru: 'Таблица лидеров',
    br: 'Placar',
    cz: 'Žebříček',
    zh: '排行榜',
    fr: 'Classement',
  },
  [LOCALE.HEROES]: {
    en: 'Heroes',
    ru: 'Герои',
    br: 'Personagens',
    cz: 'Hrdinové',
    zh: '英雄榜',
    fr: 'Héros',
  },
  [LOCALE.HERO]: {
    en: 'Hero',
    ru: 'Герой',
    br: 'Personagem',
    cz: 'Hrdina',
    zh: '英雄',
    fr: 'Héros',
  },
  [LOCALE.WAITING_FOR_OPPONENTS]: {
    en: 'Waiting for Opponents',
    ru: 'Ожидание оппонентов',
    br: 'Esperando oponentes',
    cz: 'Čekání na soupeře',
    zh: '等待對手中',
    fr: "En attente d'adversaires",
  },
  [LOCALE.TIME_TO_BATTLE]: {
    en: 'Time To Battle',
    ru: 'Времени до начала',
    br: 'Tempo de escolha',
    cz: 'Čas bojovat',
    zh: '距戰鬥時間',
    fr: 'Temps avant la bataille',
    cz: 'Čas boje',
    ru: 'Время до битвы',
    fr: 'Temps avant le combat',
    br: 'Tempo para a batalha',
    zh: '战斗时间',
  },
  [LOCALE.RANDOM_PICK]: {
    en: 'Random Pick',
    ru: 'Случайный выбор',
    br: 'Escolha aleatória',
    cz: 'Náhodný Výběr',
    zh: '亂數選擇',
    fr: 'Choix aléatoire',
  },
  [LOCALE.LOCKED_IN]: {
    en: 'Locked In',
    ru: 'Выбрано',
    br: 'Escolhido',
    cz: 'Vybráno',
    zh: '已鎖定',
    fr: 'Verrouillé',
  },
  [LOCALE.PICK_HERO]: {
    en: 'Pick Hero',
    ru: 'Выбрать героя',
    br: 'Confirmar',
    cz: 'Vyber Hrdinu',
    zh: '選擇英雄',
    ru: 'Выбрать героя',
    fr: 'Choisir un héros',
    br: 'Escolher Herói',
  },
  [LOCALE.BAN_HERO]: {
    en: 'Ban Hero',
    ru: 'Заблокировать героя',
    br: 'Banir personagem',
    cz: 'Ban Hrdinu',
    zh: '禁掉英雄',
    ru: 'Bloquer le héros',
    br: 'Заблокировать героя',
  },
  [LOCALE.ONLINE_PLAYERS]: {
    en: 'Online Players',
    ru: 'Игроков онлайн',
    br: 'Jogadores Online',
    cz: 'Online hráči',
    zh: '線上玩家數',
    fr: 'Joueurs en ligne',
  },
  [LOCALE.RATING]: {
    en: 'Rating',
    ru: 'Рейтинг',
    br: 'Pontos',
    cz: 'Hodnocení',
    zh: '評級',
    fr: 'Classement',
  },
  [LOCALE.MMR]: {
    en: 'MMR',
    ru: 'MMR',
    br: 'MMR',
    cz: 'MMR',
    zh: '匹配等級',
    fr: 'MMR',
  },
  [LOCALE.TOTAL_GAMES]: {
    en: 'Total Games',
    ru: 'Всего игр',
    br: 'Total de jogos',
    cz: 'Celkově her',
    zh: '總遊玩次數',
    fr: 'Total des jeux',
  },
  [LOCALE.TOTAL_WINS]: {
    en: 'Total Wins',
    ru: 'Всего побед',
    br: 'Total de vitórias',
    cz: 'Celkově výtězství',
    zh: '總勝利次數',
    fr: 'Victoires totales',
  },
  [LOCALE.GAME_WINS]: {
    en: 'Wins',
    ru: 'Побед',
    br: 'vitórias',
    cz: 'Výtězství',
    zh: '勝利次數',
    fr: 'Victoires',
  },
  [LOCALE.GAME_LOSSES]: {
    en: 'Losses',
    ru: 'Поражений',
    br: 'Derrotas',
    cz: 'Proher',
    zh: '戰敗次數',
    fr: 'Défaites',
  },
  [LOCALE.RANK]: {
    en: 'Rank',
    ru: 'Ранг',
    br: 'Rank',
    cz: 'Hodnost',
    zh: '等級',
    fr: 'Classement',
  },
  [LOCALE.PLAYER]: {
    en: 'Player',
    ru: 'Игрок',
    br: 'Jogador',
    cz: 'Hráč',
    zh: '玩家',
    fr: 'Joueur',
  },
  [LOCALE.PLAYERS]: {
    en: 'Players',
    br: 'Jogador',
    ru: 'Игроки',
    cz: 'Hráči',
    zh: '玩家數',
    fr: 'Joueurs',
  },
  [LOCALE.CHOOSE_HERO]: {
    en: 'CHOOSE YOUR HERO',
    ru: 'ВЫБЕРИТЕ ВАШЕГО ГЕРОЯ',
    br: 'Escolha seu Personagem',
    cz: 'VYBER HRDINU',
    zh: '選擇你的英雄',
    fr: 'CHOISISSEZ VOTRE HÉROS',
  },
  [LOCALE.TRAINING_MATCH]: {
    en: 'Training Match (AI)',
    ru: 'Тренировочный матч (ИИ)',
    br: 'Partida de Tutorial (AI)',
    cz: 'Tréninkový zápas (UI)',
    zh: '練習賽（電腦）',
    fr: "Match d'entraînement (IA)",
    cz: 'Тренировочный матч (ИИ)',
    ru: "Match d'entraînement (IA)",
    br: "Match d'entraînement (IA)",
  },
  [LOCALE.PRACTICE_MATCH]: {
    en: 'Practice Hero',
    ru: 'Тренировка',
    br: 'Treino',
    cz: 'Vyzkoušet hrdinu',
    zh: '測試英雄',
    fr: 'Entraînement',
  },
  [LOCALE.PLAY_NOW]: {
    en: 'Play Now!',
    ru: 'Сыграть сейчас!',
    br: 'Jogar agora!',
    cz: 'Hrát teď!',
    zh: '開始玩！',
    fr: 'Jouer maintenant !',
  },
  [LOCALE.TIME]: {
    en: 'Time',
    ru: 'Время',
    br: 'Tempo',
    cz: 'Čas',
    zh: '時間',
    fr: 'Temps',
  },
  [LOCALE.TAG_MAGE]: {
    en: 'MAGE',
    ru: 'МАГ',
    br: 'MAGO',
    cz: 'MÁG',
    zh: '法师',
    fr: 'MAGE',
  },
  [LOCALE.TAG_ASSASSIN]: {
    en: 'ASSASSIN',
    ru: 'УБИЙЦА',
    br: 'ASSASSINO',
    cz: 'ASSASSÍN',
    zh: '刺客',
    fr: 'ASSASSIN',
  },
  [LOCALE.TAG_BRUISER]: {
    en: 'BRUISER',
    ru: 'ГРОМИЛА',
    br: 'LUTADOR',
    cz: 'ASSASSÍN',
    zh: '創擊者',
    fr: 'BRUISER',
  },
  [LOCALE.TAG_TANK]: {
    en: 'TANK',
    ru: 'ТАНК',
    br: 'TANQUE',
    cz: 'TANK',
    zh: '坦克',
    fr: 'CHAR',
  },
  [LOCALE.TAG_SUPPORT]: {
    en: 'SUPPORT',
    ru: 'ПОДДЕРЖКА',
    br: 'SUPPORTE',
    cz: 'SUPPORT',
    zh: '支援',
    fr: 'SOUTIEN',
  },
  [LOCALE.TAG_RANGE]: {
    en: 'RANGED',
    cz: 'NA DÁLKU',
    zh: '遠程',
    ru: 'ДАЛЬНИЙ БОЙ',
    fr: 'À DISTANCE',
    br: 'A DISTANCIA',
  },
  [LOCALE.TAG_RECOMMENDED]: {
    en: 'RECOMMENDED',
    ru: 'РЕКОМЕНДУЕМЫЙ',
    br: 'RECOMENDADO',
    cz: 'ODPORÚČAME',
    zh: '強力推薦',
    fr: 'RECOMMANDÉ',
  },
  [LOCALE.POST_KDA]: {
    en: 'K/D/A',
    ru: 'У/С/С',
    br: 'K/D/A',
    cz: 'Z/U/A',
    zh: '殺敵/死亡/助攻',
    fr: 'T/M/D', // Tuer/Mourir/Assister
    br: 'K/M/A', // Matar/Morrer/Ajudar
  },
  [LOCALE.POST_HERO_DAMAGE]: {
    en: 'Hero Damage',
    ru: 'Урон по героям',
    br: 'Dano do Personagem',
    cz: 'Poškození hrdinů',
    zh: '對英雄傷害',
    fr: 'Dommages aux héros',
  },
  [LOCALE.POST_TOWER_DAMAGE]: {
    en: 'Tower Damage',
    ru: 'Урон по башне',
    br: 'Dano da Torre',
    cz: 'Poškození vězí',
    zh: '對城池傷害',
    fr: 'Dommages de la tour',
  },
  [LOCALE.POST_MINIONS_KILLED]: {
    en: 'Last Hits',
    ru: 'Миньонов убито',
    br: 'Último Hit',
    cz: 'Pěšáků zabito',
    zh: '最後造成傷害',
    fr: 'Derniers coups',
    cz: 'Pěšáků zabito',
    ru: 'Миньонов убито',
    fr: 'Derniers coups',
    br: 'Último Hit',
    zh: '最後造成傷害',
  },
  [LOCALE.POST_GRADE]: {
    en: 'Grade',
    cz: 'Hodnocení',
    zh: '成绩',
    ru: 'Оценка',
    fr: 'Note',
    br: 'Nota',
  },
  [LOCALE.POST_TOTAL_NETWORTH]: {
    en: 'Total Networth',
    ru: 'Всего золота',
    br: 'Total de dano',
    cz: 'Majetek',
    zh: '獲得總價值',
    fr: 'Valeur nette totale',
  },
  [LOCALE.POST_TOTAL_HEALING]: {
    en: 'Total Healing',
    ru: 'Всего исцеления',
    br: 'Total de cura',
    zh: '總治療量',
    cz: 'Celkové léčení',
    fr: 'Guérison totale',
  },
  [LOCALE.POST_LEAVE_GAME]: {
    en: 'Leave Game',
    ru: 'Покинуть игру',
    br: 'Voltar ao inicio',
    cz: 'Opustit Hru',
    zh: '離開遊戲',
    fr: 'Quitter le jeu',
  },
  [LOCALE.RESET_CDS]: {
    en: 'Reset Cooldowns',
    cz: 'Resetovat doby odpočinku',
    zh: '重置冷却时间',
    ru: 'Сбросить перезарядки',
    fr: 'Réinitialiser les temps de recharge',
    br: 'Redefinir Tempos de Recarga',
  },
  [LOCALE.POST_BLUE_TEAM_WIN]: {
    en: 'Blue Team won!',
    ru: 'Синяя команда победила!',
    br: 'Time azul Venceu!',
    cz: 'Vyhrál modrý tým!',
    zh: '蓝队获胜！',
    fr: "L'équipe bleue a gagné!",
  },
  [LOCALE.POST_RED_TEAM_WIN]: {
    en: 'Red Team won!',
    ru: 'Красная команда победила!',
    br: 'Time vermelho Venceu!',
    cz: 'Vyhrál rudý tým!',
    zh: '红队获胜！',
    fr: "L'équipe rouge a gagné !",
  },
  [LOCALE.CHAT_ALL]: {
    en: 'ALL',
    ru: 'ВСЕМ',
    br: 'Todos',
    cz: 'VŠE',
    zh: '大家',
    fr: 'TOUS',
  },
  [LOCALE.CHAT_ALLIES]: {
    en: 'ALLIES',
    ru: 'СОЮЗНИКАМ',
    br: 'Grupo',
    cz: 'SPOJENCI',
    zh: '隊友',
    fr: 'ALLIÉS',
  },
  [LOCALE.CHAT_GAMEMASTER]: {
    en: 'GAMEMASTER',
    ru: 'ИГРОВОЙ МАСТЕР',
    br: 'Administrador',
    cz: 'GAMEMASTER',
    zh: '管理員',
    fr: 'MAÎTRE DE JEU',
    ru: 'ИГРОВОЙ МАСТЕР',
    br: 'Administrador',
  },
  [LOCALE.POPUP_SELECT_SEND]: {
    en: 'Send',
    ru: 'Отправить',
    br: 'Mandar',
    cz: 'Odeslat',
    zh: 'ID進房',
    fr: 'Envoyer',
  },
  [LOCALE.POPUP_SELECT_ACCEPT]: {
    en: 'Accept',
    ru: 'Принять',
    br: 'Aceitar',
    cz: 'Příjmout',
    zh: '接受',
    fr: 'Accepter',
  },
  [LOCALE.POPUP_SELECT_REJECT]: {
    en: 'Reject',
    ru: 'Отклонить',
    br: 'Recusar',
    cz: 'Zámítnout',
    zh: '拒絕',
    fr: 'Rejeter',
  },
  [LOCALE.POPUP_SELECT_CLOSE]: {
    en: 'Close',
    ru: 'Закрыть',
    br: 'Fechar',
    cz: 'Zavřít',
    zh: '關閉',
    fr: 'Fermer',
  },
  [LOCALE.FORCE_RENAME_SELECT_NAME]: {
    en: 'Select your name!',
    ru: 'Выберите ваше имя!',
    br: 'Escolha seu nome!',
    cz: 'Vyberte si své jméno!',
    zh: '选择您的姓名！',
    fr: 'Choisissez votre nom !',
  },
  [LOCALE.POPUP_SELECT_MESS_GUESTMODE]: {
    en: "As a guest, you have limited access to game! <br /> Sign in with <b style='color: red'>G-Mail</b> to access ranked, save your stats, and get less ADS!",
    ru: "У вас ограниченный доступ к игре! Ваша статистика будет утеряна, если вы закроете браузер...<br /> Подключите ваш <b style='color: red'>аккаунт G-Mail</b> для получения доступа ко всем функциям и чтобы убрать рекламу!",
    br: "Você tem acesso limitado ao jogo! Suas estatísticas são perdidas quando você sai do navegador...<br /> Conecte-se a sua <b style='color: red'>Conta do G-Mail</b> para acessar todos os recursos, e sem anúncios!",
    cz: "Máte omezený přístup ke hře! Vaš pokrok bude ztracen až ukončíte prohlížeč...<br /> Připojte svůj <b style='color: red'>účet G-Mail</b> a získejte přístup ke všem funkcím. A žádné reklamy !",
    zh: "你以訪問受限狀態進入遊戲！你的遊玩紀錄將在離開瀏覽器後遺失…<br /> 連結你的 <b style='color: red'>G-Mail 帳號</b> 以獲得所有功能，且無任何廣告！",
    fr: "En tant qu'invité, vous avez un accès limité au jeu ! <br /> Connectez-vous avec <b style='color: red'>G-Mail</b> pour accéder au classement, enregistrer vos statistiques et obtenir moins de publicités !",
  },
  [LOCALE.POPUP_SELECT_NAME_GUESTMODE]: {
    en: 'GUEST MODE!',
    ru: 'РЕЖИМ ГОСТЯ!',
    br: 'MODO CONVIDADO!',
    cz: 'JSTE V REŽIME HOST!',
    zh: '陌生人模式！',
    fr: 'MODE INVITÉ !',
  },
  [LOCALE.POPUP_SELECT_GUESTMODE_OPT]: {
    en: 'Connect GMAIL Account',
    ru: 'Подключить аккаунт GMAIL',
    br: 'Conectar conta GMAIL',
    cz: 'Připojit účet GMAIL',
    zh: '連結G-Mail帳號',
    fr: 'Connecter un compte GMAIL',
  },
  [LOCALE.POPUP_BATTLE_END]: {
    en: 'Battle Ended',
    ru: 'Битва окончена',
    br: 'Jogo encerrado',
    cz: 'Bitva je ukončena',
    zh: '战斗结束',
    fr: 'Bataille terminée',
  },
  [LOCALE.POPUP_BATTLE_FOUND]: {
    en: 'Battle Found!',
    ru: 'Найдена битва!',
    br: 'Jogo encontrado',
    cz: 'Nalezena bitva!',
    zh: '發現戰鬥！',
    fr: 'Bataille trouvée!',
    br: 'Batalha encontrada!',
  },
  [LOCALE.POPUP_BATTLE_FOUND_MESS]: {
    en: 'Time Remaining',
    ru: 'Времени осталось',
    br: 'Tempo restante',
    cz: 'Zbýva času',
    zh: '剩餘時間',
    fr: 'Temps restant',
    cz: 'Оставшееся время',
    ru: 'Оставшееся время',
    br: 'Temps restant',
  },
  [LOCALE.POPUP_BATTLE_WAITING]: {
    en: 'Waiting for Players...',
    ru: 'Ожидание игроков...',
    br: 'Esperando por jogadores ...',
    cz: 'Čekání na hráče...',
    zh: '等待其他玩家中…',
    fr: 'En attente des joueurs...',
  },
  [LOCALE.POPUP_BATTLE_LEFT]: {
    en: 'Someone left...',
    ru: 'Кто-то вышел...',
    br: 'Alguém saiu ...',
    cz: 'Někdo opustil hru...',
    zh: '有人離開了…',
    fr: "Quelqu'un est parti...",
  },
  [LOCALE.POPUP_SELECT_FIRST_TIME_TRAINING]: {
    en: 'You must complete training before playing against players!',
    ru: 'Вы должны пройти обучение перед игрой против других игроков!',
    br: 'Você deve completar o treinamento antes de jogar contra outros jogadores!',
    cz: 'Musíte dokončit trénink před hraním proti hráčům!',
    zh: '在与玩家对战之前，您必须完成训练！',
    fr: "Vous devez terminer la formation avant de jouer contre d'autres joueurs!",
  },
  [LOCALE.POPUP_SELECT_FIRST_TIME_TRAINING_START]: {
    en: 'Get me into a tutorial!',
    ru: 'Начать обучение!',
    br: 'Iniciar Tutorial',
    cz: 'Dostaň mě do tutoriálu!',
    zh: '讓我進入教程！',
    fr: 'Mettez-moi dans un tutoriel !',
  },
  [LOCALE.POPUP_SELECT_FAILED_QUEUE]: {
    en: 'Failed to queue, try again!',
    ru: 'Произошла ошибка во время попытки встать в очередь, попробуйте снова!',
    br: 'Falha ao entrar na fila, tente novamente!',
    cz: 'Nepodařilo se zařadit do fronty, zkuste to znovu!',
    zh: '入隊失敗，請重試！',
    fr: "Échec de la mise en file d'attente, réessayez !",
  },
  [LOCALE.POPUP_SELECT_BANNED_QUEUE]: {
    en: 'You are banned from queue for rejecting a match! Try again in ',
    ru: 'Ваша возможность стать в очередь заблокирована, так как вы отклоняли слишком много матчей! Попробуйте снова через ',
    br: 'Você foi banido da fila por rejeitar varias partidas! tente novamente em ',
    cz: 'Máte zákaz vstupu do fronty za odmítnutí zápasů! Zkuste to za',
    zh: '你因拒絕參戰被禁止入隊！請重試於',
    fr: "Vous êtes banni de la file d'attente pour avoir refusé un match ! Réessayez dans ",
  },
  [LOCALE.AN_GOT_A]: {
    en: 'got a ',
    ru: 'получает ',
    br: 'tenho um ',
    cz: 'dostal ',
    zh: '奪得',
    fr: "j'ai un ",
  },
  [LOCALE.AN_IS_ON]: {
    en: 'is on ',
    ru: ' ',
    br: 'está ligado ',
    cz: 'má ',
    zh: '成了',
    fr: 'est allumé ',
  },
  [LOCALE.AN_FIRST_BLOOD]: {
    en: 'First Blood',
    ru: 'Первую кровь',
    br: 'Primeira morte',
    cz: 'První zabití',
    zh: '初殺',
    fr: 'Premier Sang',
  },
  [LOCALE.AN_DOUBLE_KILL]: {
    en: 'Double Kill',
    ru: 'Даблкилл',
    br: 'DOUBLE KILL',
    cz: 'Dvojité zabití',
    zh: '雙殺',
    fr: 'Double Kill',
  },
  [LOCALE.AN_TRIPLE_KILL]: {
    en: 'TRIPLE KILL',
    ru: 'ТРИПЛКИЛЛ',
    br: 'TRIPLE KILL',
    cz: 'TROJITÉ ZABITÍ',
    zh: '三殺',
    fr: 'TRIPLE KILL',
    ru: 'ТРИПЛКИЛЛ',
    br: 'TRIPLE KILL',
  },
  [LOCALE.AN_ULTRA_KILL]: {
    en: 'ULTRA KILL!!',
    ru: 'КВАДРАКИЛЛ!!',
    br: 'ULTRA KILL!!',
    zh: '爆殺！！',
    cz: 'ULTRA KILL!!',
    fr: 'ULTRA KILL!!',
  },
  [LOCALE.AN_KILLING_SPREE]: {
    en: 'Killing Spree',
    ru: 'получает серию убийств',
    br: 'MATANÇA!',
    cz: 'Zabíjející řádění',
    zh: '殺戮狂魔',
    fr: 'Série de meurtres',
  },
  [LOCALE.AN_MEGA_KILL]: {
    en: 'Mega Kill',
    ru: 'совершает мега-убийство',
    br: 'MEGA KILL!',
    cz: 'Mega zabití',
    zh: '超級殺戮者',
    fr: 'Méga Kill',
  },
  [LOCALE.AN_DOMINATING]: {
    en: 'Dominating',
    ru: 'доминирует',
    br: 'DOMINANDO!',
    cz: 'Dominujicí',
    zh: '主宰者',
    fr: 'Dominant',
  },
  [LOCALE.AN_RAMPAGE]: {
    en: 'Rampage',
    ru: 'в ярости',
    br: 'RAMPAGE!',
    cz: 'Krveprolití',
    zh: '狂者',
    fr: 'Ravage',
    cz: 'Krveprolití',
    ru: 'Буйство',
    br: 'RAMPAGE!',
  },
  [LOCALE.AN_OWNAGE]: {
    en: 'OWNAGE!',
    ru: 'ПРЕВОСХОДЕН!',
    br: 'OWNAGE!',
    cz: 'VYNIKAJÍCÍ!',
    zh: '奪權者！',
    fr: 'OWNAGE!',
  },
  [LOCALE.AN_GODLIKE]: {
    en: 'GODLIKE!',
    ru: 'БОГОПОДОБЕН!',
    br: 'DIVINO!',
    cz: 'BOŽSKÝ!',
    zh: '神乎其技！',
    fr: 'DIVIN!',
  },
  [LOCALE.HASTE_RUNE]: {
    en: 'Haste Rune',
    ru: 'Руну спешки',
    br: 'Runa de Aceleração',
    cz: 'Runa Spěchu',
    zh: '迅疾符文',
    fr: 'Rune de Hâte',
  },
  [LOCALE.DAMAGE_RUNE]: {
    en: 'Damage Rune',
    ru: 'Руну урона',
    br: 'Runa de dano',
    cz: 'Runa Poškození',
    zh: '傷害符文',
    fr: 'Rune de dégâts',
  },
  [LOCALE.ARCANE_RUNE]: {
    en: 'Arcane Rune',
    ru: 'Руну магии',
    br: 'Runa Arcana',
    cz: 'Runa Magie',
    zh: '奧術符文',
    fr: 'Rune Arcane',
  },
  [LOCALE.HEALING_RUNE]: {
    en: 'Healing Rune',
    ru: 'Руну исцеления',
    br: 'Runa de cura',
    cz: 'Runa Léčení',
    zh: '治癒符文',
    fr: 'Rune de guérison',
  },
  [LOCALE.BOUNTY_RUNE]: {
    en: 'Bounty Rune',
    ru: 'Руну золота',
    br: 'Runa da fortuna',
    cz: 'Runa zlata',
    zh: '黃金符文',
    fr: 'Rune de prime',
  },
  [LOCALE.ABILITY_POWER]: {
    en: 'Ability Power',
    ru: 'Сила умений',
    br: 'Poder de habilidade',
    cz: 'Síla kouzel',
    zh: '技能威力',
    fr: 'Puissance des compétences',
  },
  [LOCALE.DAMAGE]: {
    en: 'Attack Damage',
    ru: 'Сила атаки',
    br: 'Dano de ataque',
    cz: 'Poškození útoku',
    zh: '攻擊傷害',
    fr: "Dégâts d'attaque",
  },
  [LOCALE.ATTACK_SPEED]: {
    en: 'Attack Speed',
    ru: 'Скорость атаки',
    br: 'Velocidade de ataque',
    cz: 'Rychlost útoku',
    zh: '攻擊速度',
    fr: "Vitesse d'attaque",
  },
  [LOCALE.CRITICAL_CHANCE]: {
    en: 'Critical Chance',
    ru: 'Шанс крита',
    br: 'Chance de crítico',
    cz: 'Kritický zásah',
    zh: '爆擊機率',
    fr: 'Chance critique',
    cz: 'Шанс критики',
    br: 'Chance critique',
  },
  [LOCALE.ABILITY_HASTE]: {
    en: 'Ability Haste',
    ru: 'Сокращение перезарядки',
    br: 'Redução de recarga',
    cz: 'Redukce cooldownu',
    zh: '縮短冷卻時間',
    fr: 'Réduction du délai de récupération',
  },
  [LOCALE.LIFESTEAL]: {
    en: 'Lifesteal',
    ru: 'Кража здоровья',
    br: 'Roubo de vida',
    cz: 'Krádež Zdraví',
    zh: '吸血值',
    fr: 'Vol de vie',
  },
  [LOCALE.MAGICAL_DEFENSE]: {
    en: 'Magic Resistance',
    ru: 'Сопротивление магии',
    br: 'Resistência mágica',
    cz: 'Protimagická obrana',
    zh: '魔法抗性',
    fr: 'Résistance magique',
  },
  [LOCALE.ARMOR]: {
    en: 'Armor',
    ru: 'Броня',
    br: 'Armadura',
    cz: 'Zbroj',
    zh: '裝甲值',
    fr: 'Armure',
  },
  [LOCALE.HEALTH]: {
    en: 'Health',
    ru: 'Здоровье',
    br: 'Vida',
    cz: 'Zdravý',
    zh: '血量',
    fr: 'Santé',
  },
  [LOCALE.HEALTH_REGEN]: {
    en: 'Health Regeneration',
    ru: 'Регенерация здоровья',
    br: 'Regeneração de vida',
    cz: 'Regenerace Zdravý',
    zh: '回血速度',
    fr: 'Régénération de santé',
  },
  [LOCALE.MOVE_SPEED]: {
    en: 'Movement Speed',
    ru: 'Скорость передвижения',
    br: 'Velocidade de movimento',
    cz: 'Rychlost Pohybu',
    zh: '移動速度值',
    fr: 'Vitesse de déplacement',
    cz: 'Rychlost pohybu',
    ru: 'Скорость передвижения',
    br: 'Velocidade de movimento',
  },
  [LOCALE.CONSUMABLE]: {
    en: 'Consumable',
    ru: 'Расходуемое',
    br: 'consumível',
    cz: 'Spotřebič',
    zh: '消耗品',
    fr: 'Consommable',
  },
  [LOCALE.PICKUP]: {
    en: 'picked up',
    ru: 'подобрал',
    cz: 'vzal',
    br: 'pegou',
    zh: '選擇',
    fr: 'ramassé',
  },
  [LOCALE.POPUP_DISCONNECTED]: {
    en: "You've been disconected from the server, please refresh the page!",
    ru: 'Потеряно соединение с сервером. Пожалуйста, обновите страницу!',
    br: 'Você foi desconectado do servidor, atualize a página!',
    cz: 'Nebylo možné navázat spojení s hrou. Obnovte webovou stránku.',
    zh: '你已从服务器失连，请刷新页面！',
    fr: 'Vous avez été déconnecté du serveur, veuillez rafraîchir la page !',
  },
  [LOCALE.POPUP_REFRESH]: {
    en: 'Refresh',
    ru: 'обновить',
    br: 'recarregar',
    cz: 'obnovení',
    zh: '刷新',
    fr: 'Actualiser',
  },
  [LOCALE.YES]: {
    en: 'yes',
    ru: 'да',
    br: 'sim',
    cz: 'ano',
    zh: '是',
    fr: 'oui',
  },
  [LOCALE.CZ]: {
    en: 'cz',
    ru: 'чех',
    br: 'cz',
    cz: 'cz',
    zh: 'cz',
    fr: 'cz',
  },
  [LOCALE.ZH]: {
    en: 'zh',
    ru: 'кит',
    br: 'zh',
    cz: 'zh',
    zh: 'zh',
    fr: 'zh',
  },
  [LOCALE.RU]: {
    en: 'ru',
    ru: 'рус',
    br: 'ru',
    cz: 'ru',
    zh: 'ru',
    fr: 'ru',
  },
  [LOCALE.FR]: {
    en: 'fr',
    ru: 'фр',
    br: 'fr',
    cz: 'fr',
    zh: 'fr',
    fr: 'fr',
  },
  [LOCALE.BR]: {
    en: 'br',
    ru: 'порт',
    br: 'br',
    cz: 'br',
    zh: 'br',
    fr: 'br',
  },
  [LOCALE.POPUP_LOGOUT_TITLE]: {
    en: 'Are you sure?',
    ru: 'Уверены ли вы?',
    br: 'Tem certeza?',
    cz: 'Jste si jisti?',
    zh: '確定嗎？',
    fr: 'Êtes-vous sûr?',
  },
  [LOCALE.MSAA]: {
    en: 'Anti-aliasing',
    cz: 'Vyhlazování',
    br: 'Anti-aliasing',
    ru: 'Сглаживание',
    zh: '抗锯齿',
    fr: 'Anti-aliasing',
  },
  [LOCALE.TWOVSTWO_COOP]: {
    en: '2 v 2 Co-op vs AI',
    ru: '2 v 2 Co-op против ИИ',
    br: '2 v 2 Co-op vs AI',
    cz: '2 v 2 Co-op proti AI',
    zh: '2 v 2 Co-op vs AI',
    fr: '2 v 2 Co-op contre IA',
  },
  [LOCALE.EASY_BOT]: {
    en: '1 v 1 Easy Bot',
    ru: '1 против 1 Легкий бот',
    br: '1 v 1 Bot fácil',
    cz: '1 v 1 Lehký Bot',
    zh: '一对一简单电脑',
    fr: '1 contre 1 Bot facile',
  },
  [LOCALE.HARD_BOT]: {
    en: '1 v 1 Hard Bot',
    ru: '1 vs 1 Сложный Бот',
    cz: '1 v 1 Těžký Bot',
    zh: '一對一困難電腦',
    fr: '1 contre 1 Bot Difficile',
    br: '1 contra 1 Bot Difícil',
  },
  [LOCALE.SPECTATE]: {
    en: 'Spectate',
    ru: 'Наблюдать',
    br: 'Spectar',
    cz: 'Sledovat',
    zh: '觀戰',
    fr: 'Spectateur',
  },
  [LOCALE.WATCH]: {
    en: 'Battles',
    ru: 'Сражения',
    br: 'Batalhas',
    cz: 'Bitvy',
    zh: '戰鬥',
    fr: 'Batailles',
  },
  [LOCALE.VIEWERS]: {
    en: 'Viewers',
    ru: 'Зрителей',
    br: 'Espectadores',
    cz: 'Sleduje',
    zh: '觀眾數',
    fr: 'Spectateurs',
  },
  [LOCALE.POPUP_NO_GAMES_TO_SPECTATE]: {
    en: 'There are no games to spectate.',
    ru: 'Не найдено игр для просмотра.',
    br: 'Não há jogos para assistir.',
    cz: 'Nenašli sa žádné hry na sledování.',
    zh: '目前沒有進行中遊戲可觀看.',
    fr: "Il n'y a aucun jeu à regarder.",
  },
  [LOCALE.FREE_CAMERA]: {
    en: 'Free Camera',
    ru: 'Свободная камера',
    br: 'Camera Livre',
    cz: 'Volná Kamera',
    zh: '自由視角',
    fr: 'Caméra Libre',
  },
  [LOCALE.SPECTATOR_CHAT_MESSAGE]: {
    en: 'Spectators in Game: ',
    ru: 'Наблюдают за игрой: ',
    br: 'Espectadores no jogo: ',
    cz: 'Diváků v hře: ',
    zh: '觀眾數量: ',
    fr: 'Spectateurs en jeu: ',
  },
  [LOCALE.PRIVATE_LOBBY]: {
    en: 'Private Lobby',
    ru: 'Приватное лобби',
    br: 'Sala privada',
    cz: 'Privátní lobby',
    zh: '私人開房',
    fr: 'Lobby privé',
  },
  [LOCALE.FIND_LOBBY]: {
    en: 'Find a Lobby',
    ru: 'Найти лобби',
    br: 'Encontrar uma sala',
    cz: 'Najít lobby',
    zh: '尋找房間',
    fr: 'Trouver un lobby',
  },
  [LOCALE.CREATE_LOBBY]: {
    en: 'Create a Lobby',
    ru: 'Создать лобби',
    br: 'Criar uma sala',
    cz: 'Vytvořte lobby',
    zh: '創建私房',
    fr: 'Créer un lobby',
  },
  [LOCALE.TEAM_NAME]: {
    en: 'Team Name: ',
    ru: 'Название команды: ',
    br: 'Nome do time: ',
    cz: 'Název týmu: ',
    zh: '團隊名稱',
    fr: "Nom de l'équipe: ",
  },
  [LOCALE.JOIN]: {
    en: 'Join',
    ru: 'Присоединиться',
    br: 'Junte-se',
    cz: 'Přidat se',
    zh: '加入',
    fr: 'Rejoindre',
  },
  [LOCALE.LEAVE]: {
    en: 'Leave',
    ru: 'Выйти',
    br: 'Sair',
    cz: 'Opustit',
    zh: '離開',
    fr: 'Quitter',
  },
  [LOCALE.START]: {
    en: 'Start',
    ru: 'Начать игру',
    br: 'Iniciar',
    cz: 'Začít',
    zh: '開始',
    fr: 'Commencer',
  },
  [LOCALE.LOBBY_NAME]: {
    en: 'Title',
    cz: 'Název',
    zh: '标题',
    ru: 'Название',
    fr: 'Titre',
    br: 'Título',
  },
  [LOCALE.LOBBY_INIT_GOLDS]: {
    en: 'Initial Gold',
    ru: 'Начальное золото',
    br: 'Ouro inicial',
    cz: 'Počáteční zlaťaky',
    zh: '初始黃金',
    fr: 'Or initial',
  },
  [LOCALE.LOBBY_BASE_ABILITY_HASTE]: {
    en: 'Base Ability Haste',
    cz: 'Základní zrychlení schopností',
    zh: '基础技能加速',
    ru: 'Базовая скорость способностей',
    fr: 'Hâte de base des compétences',
    br: 'Aceleração Básica de Habilidade',
  },
  [LOCALE.LOBBY_DRAFT_PHASE]: {
    en: 'Draft Mode',
    ru: 'Режим выбора',
    br: 'Modo editado',
    zh: '草案模式',
    cz: 'Režim draftu',
    fr: 'Mode de sélection',
  },
  [LOCALE.DRAFT_BLIND_PICK]: {
    en: 'All Pick',
    ru: 'Выбор вслепую',
    br: 'Todos os picks',
    cz: 'Výber ze všech',
    zh: '無限制選角',
    fr: 'Tous les choix',
  },
  [LOCALE.DRAFT_CAPTAIN_DRAFT]: {
    en: 'Captain Draft',
    ru: 'Режим выбора (Капитаны)',
    br: 'Capitão',
    cz: 'Draft kapitánů',
    zh: '隊長草案',
    fr: 'Draft du capitaine',
    ru: 'Режим выбора (Капитаны)',
    br: 'Capitão',
  },
  [LOCALE.DRAFT_ALL_RANDOM]: {
    en: 'All Random',
    ru: 'Случайный выбор',
    br: 'Todos Aleatórios',
    cz: 'všichni náhodně',
    zh: '全部隨機選角',
    fr: 'Tous Aléatoires',
  },
  [LOCALE.CAPTAIN_DRAFT_SELECT_CAPTAIN]: {
    en: 'Select Captain!',
    ru: 'Выберите капитана!',
    br: 'Selecione o capitão!',
    cz: 'Vyber kapitána',
    zh: '選擇隊長！',
    fr: 'Sélectionnez le capitaine !',
  },
  [LOCALE.CAPTAIN_DRAFT_ENEMY_TURN_TO_BAN]: {
    en: 'Enemy turn to ban!',
    ru: 'Вражеская очередь блокировать!',
    br: 'Turno do inimigo para banir!',
    cz: 'Nepřítel na tahu, Zakazování hrdinů!',
    zh: '輪到敵方禁角！',
    fr: "Tour de l'ennemi pour bannir!",
    cz: 'Nepřítel na tahu, Zakazování hrdinů!',
    ru: 'Вражеская очередь блокировать!',
    br: 'Turno do inimigo para banir!',
  },
  [LOCALE.CAPTAIN_DRAFT_YOUR_TURN_TO_BAN]: {
    en: 'Your turn to ban!',
    ru: 'Ваша очередь блокировать!',
    br: 'Seu turno para banir!',
    cz: 'Jsi na tahu, Zakazování hrdinů!',
    zh: '輪到你禁角！',
    fr: 'À votre tour de bannir !',
    br: 'Ваша очередь запретить!',
  },
  [LOCALE.CAPTAIN_DRAFT_ENEMY_TURN_TO_PICK]: {
    en: 'Enemy turn to pick!',
    ru: 'Вражеская очередь выбирать!',
    br: 'Turno do inimigo para escolher!',
    cz: 'Nepřítel na tahu, vyberáni hrdinů!',
    zh: '輪到敵方選角！',
    fr: "Tour de l'ennemi de choisir!",
    cz: 'Nepřítel na tahu, vyberáni hrdinů!',
    ru: 'Вражеская очередь выбирать!',
    br: 'Turno do inimigo para escolher!',
  },
  [LOCALE.CAPTAIN_DRAFT_YOUR_TURN_TO_PICK]: {
    en: 'Your turn to pick!',
    ru: 'Ваша очередь выбирать!',
    br: 'Seu turno para escolher!',
    cz: 'Jsi na tahu, vyberáni hrdinů!',
    zh: '輪到你選角',
    fr: 'À votre tour de choisir!',
    cz: 'Ваша черга вибирати!',
    ru: 'Ваша очередь выбирать!',
    br: 'Sua vez de escolher!',
  },
  [LOCALE.CAPTAIN_DRAFT_SELECT_HERO]: {
    en: 'Select a Hero!',
    ru: 'Выберите героя!',
    br: 'Selecione seu personagem!',
    cz: 'Vybrat hrdinu',
    zh: '選擇一個英雄！',
    fr: 'Sélectionnez un héros !',
    cz: 'Выберите героя!',
    ru: 'Выберите героя!',
    br: 'Selecione seu personagem!',
  },
  [LOCALE.CAPTAIN_DRAFT_BECOME_CAPTAIN]: {
    en: 'Become Captain!',
    ru: 'Стать капитаном!',
    br: 'Torne-se capitão!',
    cz: 'Stát se kapitánem',
    zh: '成為隊長！',
    fr: 'Devenez capitaine!',
  },
  [LOCALE.TOURNAMENT_GAME]: {
    en: 'Tournament Game!',
    ru: 'Турнирная игра!',
    br: 'Jogo de torneio!',
    zh: '巡迴賽！',
    cz: 'Turnajová hra!',
    fr: 'Jeu de tournoi!',
  },
  [LOCALE.BANNED_HEROES]: {
    en: 'Banned Heroes',
    ru: 'Заблокированные герои',
    br: 'Heróis banidos',
    cz: 'Zakazaní hrdinové',
    zh: '禁掉英雄',
    fr: 'Héros bannis',
  },
  [LOCALE.RANKED_MATCH]: {
    en: 'Ranked',
    ru: 'Ранговая очередь',
    br: 'Lutas',
    cz: 'Hodnocení',
    zh: '爬分賽',
    fr: 'Classé',
  },
  [LOCALE.NORMAL_MATCH]: {
    en: 'Unranked',
    ru: 'Обычная очередь',
    cz: 'Nehodnocení',
    zh: '非排名',
    fr: 'Non classé',
    br: 'Não ranqueado',
  },
  [LOCALE.AI_MATCH]: {
    en: 'AI Matches (PvAI):',
    ru: 'Игры против ботов:',
    br: 'Partida contra Bot (PvAI):',
    cz: 'Zápasy proti AI (PvAI):',
    zh: 'AI 对战 (人机对战)：',
    ru: 'Игры против ИИ:',
    fr: "Matchs contre l'IA (PvIA):",
    br: 'Partida contra IA (PvIA):',
  },
  [LOCALE.PLAYER_STATS]: {
    en: 'Player Stats',
    ru: 'Статистика игрока',
    br: 'Estatísticas do jogador',
    zh: '玩家狀態',
    cz: 'Statistiky hráče',
    fr: 'Statistiques du joueur',
  },
  [LOCALE.WINRATE]: {
    en: 'Winrate',
    ru: 'Доля побед',
    br: 'Taxa de vitórias',
    zh: '勝率',
    cz: 'Winrate',
    fr: 'Taux de victoire',
  },
  [LOCALE.RECORD]: {
    en: 'Record',
    ru: 'Матчи',
    br: 'Registro',
    zh: '紀錄',
    cz: 'Záznam',
    fr: 'Enregistrement',
  },
  [LOCALE.MATCH_WON]: {
    en: 'Won Match',
    ru: 'Победа',
    br: 'Ganhou a partida',
    cz: 'Výhra',
    zh: '勝利',
    fr: 'Victoire',
  },
  [LOCALE.MATCH_LOSE]: {
    en: 'Lost Match',
    ru: 'Поражение',
    br: 'Perdeu a partida',
    cz: 'Prohra',
    zh: '敗北',
    fr: 'Match perdu',
  },
  [LOCALE.VERY_HIGH_SKILL]: {
    en: 'Very high skill',
    ru: 'Очень высокий уровень',
    br: 'Habilidade muito alta',
    cz: 'Velmi vysoká dovednost',
    zh: '頂尖技術區間',
    fr: 'Compétence très élevée',
  },
  [LOCALE.HIGH_SKILL]: {
    en: 'High skill',
    ru: 'Высокий уровень',
    br: 'Habilidade alta',
    cz: 'Vysoká dovednost',
    zh: '高技術區間',
    fr: 'Compétence élevée',
  },
  [LOCALE.NORMAL_SKILL]: {
    en: 'Normal skill',
    ru: 'Нормальный уровень',
    br: 'Habilidade normal',
    cz: 'Normální dovednost',
    zh: '一般技術區間',
    fr: 'Compétence normale',
  },
  [LOCALE.ST_GENERAL]: {
    en: 'General',
    cz: 'Hlavní',
    br: 'Geral',
    ru: 'Общие',
    zh: '主要',
    fr: 'Général',
  },
  [LOCALE.ST_AUDIO]: {
    en: 'Audio',
    ru: 'Звук',
    br: 'Áudio',
    zh: '音源',
    cz: 'Zvuk',
    fr: 'Audio',
  },
  [LOCALE.ST_HOTKEYS]: {
    en: 'Hotkeys',
    ru: 'Горячие клавиши',
    br: 'Teclas de atalho',
    zh: '按鍵',
    cz: 'Horké klávesy',
    fr: 'Raccourcis',
  },
  [LOCALE.ST_ACCOUNT]: {
    en: 'Account',
    cz: 'Účet',
    zh: '帐户',
    ru: 'Аккаунт',
    fr: 'Compte',
    br: 'Conta',
  },
  [LOCALE.ST_MISC]: {
    en: 'Misc.',
    ru: 'Прочее',
    br: 'Diversos',
    zh: '雜項',
    cz: 'Různé',
    fr: 'Divers',
  },
  [LOCALE.ST_AUDIO_MASTER_VOLUME]: {
    en: 'Master Volume',
    ru: 'Общая громкость',
    br: 'Volume principal',
    zh: '主音量',
    cz: 'Hlavní hlasitost',
    fr: 'Volume principal',
  },
  [LOCALE.MOVEMENT]: {
    en: 'Movement',
    cz: 'Pohyb',
    br: 'Movimento',
    ru: 'Передвижение',
    zh: '移動速度',
    fr: 'Mouvement',
  },
  [LOCALE.ABILITES]: {
    en: 'Abilites',
    cz: 'Schopnosti',
    br: 'Habilidades',
    ru: 'Способности',
    zh: '技能',
    fr: 'Compétences',
  },
  [LOCALE.ITEMS]: {
    en: 'Items',
    cz: 'Předměty',
    br: 'Itens',
    ru: 'Предметы',
    zh: '物品',
    fr: 'Articles',
  },
  [LOCALE.FRIENDS]: {
    en: 'Friends',
    cz: 'Přátelé',
    zh: '朋友',
    ru: 'Друзья',
    fr: 'Amis',
    br: 'Amigos',
  },
  [LOCALE.SHOP]: {
    en: 'Shop',
    cz: 'Obchod',
    zh: '商店',
    ru: 'Магазин',
    fr: 'Boutique',
    br: 'Loja',
  },
  [LOCALE.ST_KEYBIND_MOVEUP]: {
    en: 'Jump',
    cz: 'Skok',
    br: 'Pular',
    ru: 'Прыжок',
    zh: '跳躍',
    fr: 'Sauter',
  },
  [LOCALE.ST_KEYBIND_MOVEDOWN]: {
    en: 'Move Down',
    cz: 'pohyb dolů',
    br: 'Mover para baixo',
    ru: 'Движение вниз',
    zh: '落下',
    fr: 'Descendre',
  },
  [LOCALE.ST_KEYBIND_MOVELEFT]: {
    en: 'Move Left',
    cz: 'pohyb doleva',
    br: 'Mover para a esquerda',
    ru: 'Движение влево',
    zh: '往左',
    fr: 'Déplacer à gauche',
  },
  [LOCALE.ST_KEYBIND_MOVERIGHT]: {
    en: 'Move Right',
    cz: 'pohyb vpravo',
    br: 'Mover para a direita',
    ru: 'Движение вправо',
    zh: '往右',
    fr: 'Déplacer à droite',
  },
  [LOCALE.ST_KEYBIND_ATTACK]: {
    en: 'Attack',
    cz: 'Útok',
    br: 'Ataque',
    ru: 'Атака',
    zh: '攻擊',
    fr: 'Attaque',
  },
  [LOCALE.ST_KEYBIND_ABILITY]: {
    en: 'Ability',
    cz: 'Schopnost',
    br: 'Habilidade',
    ru: 'Способность',
    zh: '技能',
    fr: 'Capacité',
  },
  [LOCALE.ST_KEYBIND_ITEM]: {
    en: 'Item',
    cz: 'Předmět',
    br: 'Item',
    ru: 'Предмет',
    zh: '物品',
    fr: 'Objet',
  },
  [LOCALE.ST_KEYBIND_RECALL]: {
    en: 'Recall',
    cz: 'Odvolání',
    br: 'Recall',
    ru: 'Возвращение',
    zh: '召回',
    fr: 'Rappel',
    br: 'Recall',
  },
  [LOCALE.SCOREBOARD]: {
    en: 'Scoreboard',
    cz: 'Tabulka',
    br: 'Placar',
    ru: 'Таблица счёта',
    zh: '記分板',
    fr: 'Tableau des scores',
  },
  [LOCALE.AUOTBUY]: {
    en: 'Auto-Buy',
    cz: 'Automatické nákupy',
    br: 'Compra automática',
    ru: 'Автоматическая покупка предметов',
    zh: '自動購買',
    fr: 'Achat automatique',
    br: 'Compra automática',
    cz: 'Automatický nákup',
    ru: 'Автоматическая покупка',
    zh: '自动购买',
  },
  [LOCALE.SHOW_CHAT]: {
    en: 'Show Chat',
    cz: 'Zobrazit Chat',
    zh: '显示聊天',
    ru: 'Показать чат',
    fr: 'Afficher le chat',
    br: 'Mostrar Chat',
  },
  [LOCALE.VIDEO]: {
    en: 'Video',
    ru: 'Графика',
    br: 'Video',
    zh: '畫面',
    cz: 'Video',
    fr: 'Vidéo',
  },
  [LOCALE.ANTIALIASING]: {
    en: 'Antialiasing',
    ru: 'Сглаживание',
    br: 'Antialiasing',
    zh: '抗鋸齒',
    cz: 'Antialiasing',
    fr: 'Antialiasing',
  },
  [LOCALE.RESOLUTION]: {
    en: 'Resolution',
    cz: 'Rozlišení',
    br: 'Resolução',
    ru: 'Разрешение',
    zh: '分辨率',
    fr: 'Résolution',
  },
  [LOCALE.ST_MOUSE_SUPPORT_TOOLTIPS]: {
    en: 'This feature allows usage of a mouse for all attacks. Keep in mind that your hero will attack towards your mouse with Mouse Support enabled.',
    ru: 'Эта функция позволит использовать кнопки мыши для способностей. Будьте осторожны, если функция включена, ваш герой будет смотреть в сторону мыши. ',
    br: 'Esse recurso permitirá que os botões do mouse sejam usados ​​para habilidades e ataques. Tenha cuidado, seu personagem ficará de frente para a direção do mouse. ',
    zh: '此功能能夠使用滑鼠按鍵迎面發動技能。注意，你的英雄將會朝著滑鼠的方向動作。',
  },
  [LOCALE.ST_LANGUAGE]: {
    en: 'Language',
    cz: 'Jazýk',
    br: 'Idioma',
    ru: 'Язык',
    zh: '語言',
    fr: 'Langue',
  },
  [LOCALE.ST_FILTER_BAD_WORDS]: {
    en: 'Profanity Filter',
    cz: 'Filtr špatných slov',
    br: 'Filtro de palavrões',
    ru: 'Фильтр брани',
    zh: '過濾不雅詞語',
    fr: 'Filtre de grossièretés',
  },
  [LOCALE.ST_AUDIO_BGMUSIC_VOLUME]: {
    en: 'Background Music',
    cz: 'Hudba v pozadí',
    br: 'Background Music',
    ru: 'Фоновая музыка',
    zh: '背景音乐',
    fr: 'Musique de fond',
  },
  [LOCALE.LOBBY_SHARE_GAME]: {
    en: 'Copy Sharable Link',
    cz: 'Kopírovat sdílitelný odkaz',
    zh: '複製分享連結',
    ru: 'Скопировать ссылку на лобби',
    fr: 'Copier le lien partageable',
    br: 'Copiar link compartilhável',
  },
  [LOCALE.ST_ATMOSPHERIC_DETAILS]: {
    en: 'Atmospheric Details',
    ru: 'Атмосферные детали',
    br: 'Detalhes atmosféricos',
    cz: 'Atmosferické detaily',
    zh: '氛围渲染',
    fr: 'Détails atmosphériques',
  },
  [LOCALE.ADD_HARD_BOT]: {
    en: 'Add Hard Bot',
    cz: 'Přidat těžkého bota',
    br: 'Adicionar bot difícil',
    ru: 'Добавить сложного бота',
    zh: '加入困难电脑',
    fr: 'Ajouter un bot difficile',
  },
  [LOCALE.ST_UI_SCALE]: {
    en: 'UI Scale',
    ru: 'Масштаб интерфейса',
    cz: 'Velikost UI',
    zh: 'UI比例缩放',
    fr: "Échelle de l'interface utilisateur",
    br: 'Escala da interface do usuário',
  },
  [LOCALE.CHAT_COMMAND_GLOBAL]: {
    en: '/g <message> - send message in global chat, visible to all players',
    ru: '/g <сообщение> - отправить сообщение всем игрокам в глобальном чате',
    br: '/g <mensagem> - enviar mensagem para todos os jogadores',
    cz: '/g <zpráva> - poslat zprávu všem hráčům',
    zh: '/g <消息> - 向所有玩家發送消息',
    ru: '/g <сообщение> - отправить сообщение всем игрокам в глобальном чате',
    fr: '/g <message> - envoyer un message dans le chat global, visible par tous les joueurs',
    br: '/g <mensagem> - enviar mensagem para todos os jogadores',
  },
  [LOCALE.CHAT_COMMAND_ALL]: {
    en: '/all <message> - send message to all players in your current game',
    ru: '/all <сообщение> - отправить сообщение всем игрокам в текущей игре',
    br: '/all <mensagem> - enviar mensagem para todos os jogadores',
    cz: '/all <zpráva> - poslat zprávu všem hráčům',
    zh: '/all <消息> - 向當前游戲中的所有玩家發送消息',
    fr: '/all <message> - envoyer un message à tous les joueurs de votre partie actuelle',
  },
  [LOCALE.CHAT_COMMAND_WHISPER]: {
    en: '/whisper <player> <message> - send a private message to a player',
    ru: '/whisper <игрок> <сообщение> - отправить личное сообщение игроку',
    br: '/whisper <jogador> <mensagem> - enviar mensagem privada para um jogador',
    cz: '/whisper <hráč> <zpráva> - poslat soukromou zprávu hráči',
    zh: '/whisper <玩家> <消息> - 向玩家發送私人消息',
    fr: '/whisper <joueur> <message> - envoyer un message privé à un joueur',
  },
  [LOCALE.CHAT_COMMAND_WHISPER2]: {
    en: '/w <player> <message> - send a private message to a player',
    ru: '/w <игрок> <сообщение> - отправить личное сообщение игроку',
    br: '/w <jogador> <mensagem> - enviar mensagem privada para um jogador',
    cz: '/w <hráč> <zpráva> - poslat soukromou zprávu hráči',
    zh: '/w <玩家> <消息> - 向玩家發送私人消息',
    fr: '/w <joueur> <message> - envoyer un message privé à un joueur',
  },
  [LOCALE.CHAT_COMMAND_REPORT]: {
    en: '/report <message> - report an issue to the GameMasters',
    cz: '/nahlasit <zpráva> - nahlásit problém GameMasterům',
    zh: '/report <信息> - 向游戏管理员报告问题',
    ru: '/report <сообщение> - сообщить о проблеме Гейммастерам',
    fr: '/report <message> - signaler un problème aux Maîtres de jeu',
    br: '/reportar <mensagem> - reportar um problema aos GameMasters',
  },
  [LOCALE.CHAT_COMMAND_EXIT]: {
    en: '/exit - exit the game (practice only)',
    ru: '/exit - выйти из игры (только для практики)',
    br: '/exit - sair do jogo (apenas para prática)',
    cz: '/exit - opustit hru (pouze pro praktiku)',
    zh: '/exit - 離開遊戲 (僅限於練習模式)',
    fr: '/exit - quitter le jeu (pratique seulement)',
  },
  [LOCALE.NOT_FOUND_MATCHES]: {
    en: 'This player has no match history.',
    ru: 'У этого игрока нет истории игр.',
    cz: 'Tento hráč nemá žádnou historii zápasů.',
    zh: '该玩家没有比赛记录。',
    fr: "Ce joueur n'a pas d'historique de match.",
    br: 'Este jogador não possui histórico de partidas.',
  },
  [LOCALE.RANK_UNRANKED]: {
    en: 'Unknown',
    ru: 'Без ранга',
    cz: 'Neznámý',
    zh: '未知',
    fr: 'Inconnu',
    br: 'Desconhecido',
  },
  [LOCALE.RANK_BRONZE]: {
    en: 'Bronze',
    ru: 'Бронза',
    cz: 'Bronzový',
    zh: '青铜',
    fr: 'Bronze',
    br: 'Bronze',
  },
  [LOCALE.RANK_SILVER]: {
    en: 'Silver',
    ru: 'Серебро',
    cz: 'Stříbrný',
    zh: '银',
    fr: 'Argent',
    br: 'Prata',
  },
  [LOCALE.RANK_GOLD]: {
    en: 'Gold',
    ru: 'Золото',
    cz: 'Zlatý',
    zh: '黄金',
    fr: 'Or',
    br: 'Ouro',
  },
  [LOCALE.RANK_PLATINUM]: {
    en: 'Platinum',
    ru: 'Платина',
    cz: 'Platinový',
    zh: '白金',
    fr: 'Platine',
    br: 'Platina',
  },
  [LOCALE.RANK_DIAMOND]: {
    en: 'Diamond',
    ru: 'Алмаз',
    cz: 'Diamantový',
    zh: '钻石',
    fr: 'Diamant',
    br: 'Diamante',
  },
  [LOCALE.RANK_MYTHICAL]: {
    en: 'Mythical',
    ru: 'Мифический',
    cz: 'Mytický',
    zh: '神话',
    fr: 'Mythique',
    br: 'Mítico',
  },
  [LOCALE.HERO_MASTERY_MASTER]: {
    en: 'Master',
    ru: 'Мастер',
    cz: 'Mistr',
    zh: '大师',
    fr: 'Maître',
    br: 'Mestre',
  },
  [LOCALE.HERO_MASTERY_GRAND_MASTER]: {
    en: 'Grand Master',
    ru: 'Грандмастер',
    cz: 'Velký mistr',
    zh: '大师',
    fr: 'Grand Maître',
    br: 'Grande Mestre',
  },
  [LOCALE.RANK_CALIBRATION_DESCRIPTION]: {
    en: 'games left to calibrate rank!',
    ru: 'игр осталось до окончания калибровки ранга!',
    cz: 'her zbývá ke kalibraci ranku!',
    zh: '剩余游戏进行排名校准！',
    fr: 'parties restantes pour calibrer le rang !',
    br: 'partidas restantes para calibrar o ranking!',
  },
  [LOCALE.LEVEL_UP]: {
    en: 'Level Up',
    ru: 'Вы получили новый уровень',
    cz: 'Dosáhli jste nové úrovně',
    zh: '升级',
    fr: 'Niveau supérieur',
    br: 'Subir de nível',
  },
  [LOCALE.RANK_UP]: {
    en: 'You have been promoted to a new rank',
    ru: 'Вы достигли нового ранга',
    cz: 'Dosáhli jste nové hodnosti',
    zh: '您已晋升到新的等级',
    fr: 'Vous avez été promu à un nouveau rang',
    br: 'Você foi promovido para um novo cargo',
  },
  [LOCALE.POPUP_YOUR_REWARD]: {
    en: 'Your Reward!',
    cz: 'Tvoje odměna!',
    zh: '你的奖励！',
    ru: 'Ваша награда!',
    fr: 'Votre récompense !',
    br: 'Sua recompensa!',
  },
  [LOCALE.HERO_MASTERY]: {
    en: 'Hero Mastery',
    cz: 'Dovednost hrdiny',
    ru: 'Мастерство героя',
    zh: '英雄精通',
    fr: 'Maîtrise du héros',
    br: 'Maestria do herói',
  },
  [LOCALE.REQUIRED_LEVEL]: {
    en: 'Required Level',
    cz: 'Požadovaná úroveň',
    zh: '所需等级',
    ru: 'Необходимый уровень',
    fr: 'Niveau requis',
    br: 'Nível necessário',
  },
  [LOCALE.REQUIRED_HEROES]: {
    en: 'Required Heroes',
    cz: 'Požadovaní Hrdinové',
    zh: '所需英雄',
    ru: 'Требуемые герои',
    fr: 'Héros requis',
    br: 'Heróis Necessários',
  },
  [LOCALE.TOWER]: {
    en: 'Tower',
    cz: 'Věž',
    zh: '塔',
    ru: 'Башня',
    fr: 'Tour',
    br: 'Torre',
  },
  [LOCALE.OBSERVER_WARD]: {
    en: 'Observer Ward',
    cz: 'Pozorovací Ward',
    zh: '侦查守卫',
    ru: 'Тотем-наблюдатель',
    fr: 'Observer Ward',
    br: 'Ward de Observação',
  },
  [LOCALE.SENTRY_WARD]: {
    en: 'Sentry Ward',
    cz: 'Strážný totem',
    zh: '守卫宝珠',
    ru: 'Сторожевой тотем',
    fr: 'Totem de sentinelle',
    br: 'Totem de Sentinela',
  },
  [LOCALE.COOLDOWN_REDUCTION]: {
    en: 'Cooldown Reduction',
    ru: 'Сокращение перезарядки',
    cz: 'Redukce cooldownu',
    zh: '冷却缩减',
    fr: 'Réduction du temps de recharge',
    br: 'Redução de Tempo de Recarga',
  },
  [LOCALE.PHYSICAL_RESISTANCE]: {
    en: 'Normal Damage Resistance',
    ru: 'Сопротивление физическому урону',
    cz: 'Redukce normalního zranění',
    zh: '普通伤害抵抗',
    fr: 'Résistance aux dégâts normaux',
    br: 'Resistência a Danos Normais',
  },
  [LOCALE.PLAY_PAGE_LOBBIES]: {
    en: 'Lobbies',
    ru: 'Лобби',
    cz: 'Vlastní hra',
    zh: '大厅',
    fr: 'Salons',
    br: 'Salas',
  },
  [LOCALE.PLAY_PAGE_COOP_VS_AI]: {
    en: 'Co-op vs AI',
    cz: 'Spolupráce proti umělé inteligenci',
    zh: '合作对抗人工智能',
    ru: 'Игроки против ИИ',
    fr: 'Coopération contre IA',
    br: 'Co-op vs IA',
  },
  [LOCALE.PLAY_PAGE_PVP]: {
    en: 'PvP',
    cz: 'PvP',
    zh: 'PvP',
    ru: 'Игроки против игроков',
    fr: 'JcJ',
    br: 'JxJ',
  },
  [LOCALE.SHOP_EMOTES]: {
    en: 'Emotes',
    cz: 'Emoty',
    zh: '表情',
    ru: 'Эмоции',
    fr: 'Émotes',
    br: 'Emotes',
  },
  [LOCALE.SHOP_SKINS]: {
    en: 'Skins',
    cz: 'Skinování',
    zh: '皮肤',
    ru: 'Скины',
    fr: 'Skins',
    br: 'Skins',
  },
  [LOCALE.PURCHASE_HERO_TITLE]: {
    en: 'Buy {} for {} Gold?',
    cz: 'Koupit {} za {} zlatých?',
    zh: '购买 {} 以 {} 金币？',
    ru: 'Купить {} за {} золота?',
    fr: "Acheter {} pour {} pièces d'or?",
    br: 'Comprar {} por {} Ouro?',
  },
  [LOCALE.FRIENDS_PAGE_LIST]: {
    en: 'List',
    cz: 'Seznam',
    zh: '列表',
    ru: 'Список',
    fr: 'Liste',
    br: 'Lista',
  },
  [LOCALE.FRIENDS_PAGE_REQUESTS]: {
    en: 'Requests',
    cz: 'Žádosti',
    zh: '请求',
    ru: 'Запросы',
    fr: 'Demandes',
    br: 'Pedidos',
  },
  [LOCALE.FRIENDS_IN_GAME]: {
    en: 'In Game ({})',
    cz: 'Ve hře ({})',
    zh: '游戏中 ({})',
    ru: 'В игре ({})',
    fr: 'En jeu ({})',
    br: 'No jogo ({})',
  },
  [LOCALE.FRIENDS_IN_QUEUE]: {
    en: 'In Queue ({})',
    cz: 'Ve frontě ({})',
    zh: '在队列中 ({})',
    ru: 'В очереди ({})',
    fr: 'En attente ({})',
    br: 'Na fila ({})',
  },
  [LOCALE.FRIENDS_IN_LOBBY]: {
    en: 'In Private Lobby',
    cz: 'V soukromé lobby',
    zh: '在私人大厅',
    ru: 'В приватной комнате',
    fr: 'Dans le lobby privé',
    br: 'No Lobby Privado',
  },
  [LOCALE.FRIENDS_SPECTATING]: {
    en: 'Spectating Game ({})',
    cz: 'Sledování hry ({})',
    zh: '观战游戏 ({})',
    ru: 'Наблюдение за игрой ({})',
    fr: 'Partie en spectateur ({})',
    br: 'Assistindo Jogo ({})',
  },
  [LOCALE.FRIENDS_ONLINE]: {
    en: 'Online',
    cz: 'Online',
    zh: '在线',
    ru: 'Онлайн',
    fr: 'En ligne',
    br: 'Online',
  },
  [LOCALE.FRIENDS_OFFLINE]: {
    en: 'Offline',
    cz: 'Offline',
    zh: '离线',
    ru: 'Не в сети',
    fr: 'Hors ligne',
    br: 'Offline',
  },
  [LOCALE.FRIENDS_REMOVE]: {
    en: 'Remove Friend?',
    cz: 'Odstranit přítele?',
    zh: '删除好友？',
    ru: 'Удалить друга?',
    fr: "Supprimer l'ami ?",
    br: 'Remover amigo?',
  },
  [LOCALE.FRIENDS_NONE_ADDED]: {
    en: 'You have no friends added. Send a request to add one now!',
    cz: 'Nemáte přidané žádné přátele. Pošlete žádost o přidání nyní!',
    zh: '您还没有添加任何好友。现在发送请求添加一个吧！',
    ru: 'У вас нет добавленных друзей. Отправьте запрос, чтобы добавить одного сейчас!',
    fr: "Vous n'avez aucun ami ajouté. Envoyez une demande pour en ajouter un maintenant !",
    br: 'Você não tem amigos adicionados. Envie uma solicitação para adicionar um agora!',
  },
  [LOCALE.FRIENDS_ONLINE_COUNT]: {
    en: 'Friends Online: {}',
    cz: 'Přátelé online: {}',
    zh: '在线好友：{}',
    ru: 'Друзья онлайн: {}',
    fr: 'Amis en ligne : {}',
    br: 'Amigos online: {}',
  },
  [LOCALE.FRIENDS_REQUESTS_INCOMING]: {
    en: 'Friend Requests Received',
    cz: 'Přijaté žádosti o přátelství',
    zh: '收到的好友请求',
    ru: 'Полученные запросы в друзья',
    fr: "Demandes d'ami reçues",
    br: 'Solicitações de amizade recebidas',
  },
  [LOCALE.FRIENDS_REQUESTS_SENT]: {
    en: 'Friend Requests Sent',
    cz: 'Odeslané žádosti o přátelství',
    zh: '已发送的好友请求',
    ru: 'Отправленные запросы в друзья',
    fr: "Demandes d'ami envoyées",
    br: 'Solicitações de amizade enviadas',
  },
  [LOCALE.FRIENDS_SEND_REQUEST]: {
    en: 'Send Friend Request',
    cz: 'Odeslat žádost o přátelství',
    zh: '发送好友请求',
    ru: 'Отправить запрос в друзья',
    fr: "Envoyer une demande d'ami",
    br: 'Enviar solicitação de amizade',
  },
  [LOCALE.UNKNOWN]: {
    en: 'Unknown',
    cz: 'Neznámý',
    zh: '未知',
    ru: 'Неизвестно',
    fr: 'Inconnu',
    br: 'Desconhecido',
  },
  [LOCALE.CHAT_SYSTEM_WELCOME]: {
    en: 'Player {} has joined the game!',
    cz: 'Hráč {} se připojil do hry!',
    zh: '玩家 {} 加入了游戏！',
    ru: 'Игрок {} присоединился к игре!',
    fr: 'Le joueur {} a rejoint la partie !',
    br: 'O jogador {} entrou no jogo!',
  },
  [LOCALE.CHAT_SYSTEM_SPECTATE]: {
    en: 'Specators: {}',
    cz: 'Diváci: {}',
    zh: '观众: {}',
    ru: 'Зрители: {}',
    fr: 'Spectateurs: {}',
    br: 'Espectadores: {}',
  },
  [LOCALE.CHAT_SYSTEM_MUTED]: {
    en: 'You are muted for {} minutes.',
    cz: 'Jsi ztlumený na {} minut.',
    zh: '你被禁言{}分钟。',
    ru: 'Вы замучены на {} минут.',
    fr: 'Vous êtes réduit au silence pendant {} minutes.',
    br: 'Você está silenciado por {} minutos.',
  },
  [LOCALE.CHAT_SYSTEM_RENAME]: {
    en: 'You have been given a rename. Reload your page to change your name.',
    cz: 'Bylo vám přiděleno přejmenování. Načtěte stránku znovu, abyste změnili své jméno.',
    zh: '您已被赋予重命名。重新加载页面以更改您的名称。',
    ru: 'Ваше имя было изменено. Обновите страницу, чтобы увидеть изменения.',
    fr: 'Vous avez reçu un nouveau nom. Rechargez votre page pour changer votre nom.',
    br: 'Você recebeu um novo nome. Recarregue sua página para alterar seu nome.',
  },
  [LOCALE.CHAT_SYSTEM_PLAYER_LEFT]: {
    en: ' has left the game!',
    cz: ' opustil hru!',
    zh: ' 离开了游戏！',
    ru: ' покинул игру!',
    fr: ' a quitté la partie !',
    br: ' saiu do jogo!',
  },
  [LOCALE.CHAT_SYSTEM_REPORT]: {
    en: 'Your report has been sent to the GameMasters.',
    cz: 'Váš report byl odeslán GameMasterům.',
    zh: '您的举报已发送给游戏管理员。',
    ru: 'Ваше сообщение отправлено ГеймМастерам.',
    fr: 'Votre signalement a été envoyé aux Maîtres de jeu.',
    br: 'Seu relatório foi enviado para os GameMasters.',
  },
  [LOCALE.CHAT_SYSTEM_REPORT_ERR]: {
    en: 'Could not send your report to the GameMasters.',
    cz: 'Nepodařilo se odeslat váš report GameMasterům.',
    zh: '无法将您的报告发送给游戏管理员。',
    ru: 'Не удалось отправить ваш отчет GameMasters.',
    fr: "Impossible d'envoyer votre rapport aux GameMasters.",
    br: 'Não foi possível enviar seu relatório para os GameMasters.',
  },
  [LOCALE.CHAT_ADMIN_GET_PLAYER]: {
    en: 'Online: {} || Name: {} || Email: {} || ID: {} || IP: {}',
    cz: 'Online: {} || Jméno: {} || Email: {} || ID: {} || IP: {}',
    zh: '在线: {} || 姓名: {} || 电子邮件: {} || ID: {} || IP: {}',
    ru: 'Онлайн: {} || Имя: {} || Электронная почта: {} || ID: {} || IP: {}',
    fr: 'En ligne: {} || Nom: {} || Email: {} || ID: {} || IP: {}',
    br: 'Online: {} || Nome: {} || Email: {} || ID: {} || IP: {}',
  },
  [LOCALE.CHAT_ADMIN_GET_PLAYER_ERR]: {
    en: 'ERROR: {}',
    cz: 'CHYBA: {}',
    zh: '错误：{}',
    ru: 'ОШИБКА: {}',
    fr: 'ERREUR: {}',
    br: 'ERRO: {}',
  },
  [LOCALE.CHAT_ADMIN_BAN_IP]: {
    en: 'IP {} has been banned!',
    cz: 'IP {} byla zabanována!',
    zh: 'IP {} 已被封禁！',
    ru: 'IP {} был забанен!',
    fr: "L'IP {} a été bannie !",
    br: 'O IP {} foi banido!',
  },
  [LOCALE.CHAT_ADMIN_UNBAN_IP]: {
    en: 'IP {} has been unbanned!',
    cz: 'IP {} byla odbanována!',
    zh: 'IP {} 已解禁！',
    ru: 'IP {} был разбанен!',
    fr: "L'IP {} a été débannie !",
    br: 'O IP {} foi desbanido!',
  },
  [LOCALE.CHAT_ADMIN_BAN_PLAYER]: {
    en: 'Player {} has been banned!',
    cz: 'Hráč {} byl zabanován!',
    zh: '玩家 {} 已被封禁！',
    ru: 'Игрок {} был забанен!',
    fr: 'Le joueur {} a été banni !',
    br: 'O jogador {} foi banido!',
  },
  [LOCALE.CHAT_ADMIN_UNBAN_PLAYER]: {
    en: 'Player {} has been unbanned!',
    cz: 'Hráč {} byl odbanován!',
    zh: '玩家 {} 已解封！',
    ru: 'Игрок {} был разбанен!',
    fr: 'Le joueur {} a été débanni !',
    br: 'O jogador {} foi desbanido!',
  },
  [LOCALE.CHAT_ADMIN_MUTE]: {
    en: 'Player {} has been muted!',
    cz: 'Hráč {} byl ztlumen!',
    zh: '玩家 {} 已被禁言！',
    ru: 'Игрок {} был замучен!',
    fr: 'Le joueur {} a été réduit au silence !',
    br: 'O jogador {} foi silenciado!',
  },
  [LOCALE.CHAT_ADMIN_UNMUTE]: {
    en: 'Player {} has been unmuted!',
    cz: 'Hráč {} byl odtlumen!',
    zh: '玩家 {} 已被解除禁言！',
    ru: 'Игрок {} был размучен!',
    fr: 'Le joueur {} a été réactivé !',
    br: 'O jogador {} foi desmutado!',
  },
  [LOCALE.CHAT_ADMIN_KICK]: {
    en: 'Player {} has been kicked!',
    cz: 'Hráč {} byl vyhozen!',
    zh: '玩家 {} 已被踢出！',
    ru: 'Игрок {} был кикнут!',
    fr: 'Le joueur {} a été expulsé !',
    br: 'O jogador {} foi expulso!',
  },
  [LOCALE.CHAT_ADMIN_RENAME]: {
    en: 'Player {} has been given a rename!',
    cz: 'Hráči {} bylo změněno jméno!',
    zh: '玩家 {} 已更改名称！',
    ru: 'Имя игрока {} было изменено!',
    fr: 'Le joueur {} a été renommé !',
    br: 'O jogador {} recebeu um novo nome!',
  },
  [LOCALE.CHAT_ADMIN_FORCE_RENAME]: {
    en: 'Player {} has been force renamed to {}!',
    cz: 'Hráč {} byl přejmenován na {}!',
    zh: '玩家 {} 已被强制改名为 {}！',
    ru: 'Имя игрока {} было принудительно изменено на {}!',
    fr: 'Le joueur {} a été renommé de force en {} !',
    br: 'O jogador {} foi renomeado à força para {}!',
  },
  [LOCALE.CHAT_ADMIN_GET_PLAYER_ERR]: {
    en: 'Could not get player "{}"!',
    cz: 'Nepodařilo se najít hráče "{}"!',
    zh: '无法获取玩家 "{}"！',
    ru: 'Не удалось найти игрока "{}"!',
    fr: 'Impossible de récupérer le joueur "{}"!',
    br: 'Não foi possível obter o jogador "{}"!',
  },
  [LOCALE.CHAT_ADMIN_BAN_IP_ERR]: {
    en: 'Could not ban ip "{}"!',
    cz: 'Nepodařilo se zabanovat ip "{}"!',
    zh: '无法封禁IP地址 "{}"！',
    ru: 'Не удалось забанить ip "{}"!',
    fr: 'Impossible de bannir l\'adresse IP "{}" !',
    br: 'Não foi possível banir o IP "{}"!',
  },
  [LOCALE.CHAT_ADMIN_UNBAN_IP_ERR]: {
    en: 'Could not unban ip "{}"!',
    cz: 'Nepodařilo se odbanovat ip "{}"!',
    zh: '无法解封IP地址 "{}"！',
    ru: 'Не удалось разбанить ip "{}"!',
    fr: 'Impossible de débannir l\'adresse IP "{}" !',
    br: 'Não foi possível desbanir o IP "{}"!',
  },
  [LOCALE.CHAT_ADMIN_BAN_PLAYER_ERR]: {
    en: 'Could not ban player "{}"!',
    cz: 'Nepodařilo se zabanovat hráče "{}"!',
    zh: '无法封禁玩家 "{}"！',
    ru: 'Не удалось забанить игрока "{}"!',
    fr: 'Impossible de bannir le joueur "{}" !',
    br: 'Não foi possível banir o jogador "{}"!',
  },
  [LOCALE.CHAT_ADMIN_UNBAN_PLAYER_ERR]: {
    en: 'Could not unban player "{}"!',
    cz: 'Nepodařilo se odbanovat hráče "{}"!',
    zh: '无法解封玩家 "{}"！',
    ru: 'Не удалось разбанить игрока "{}"!',
    fr: 'Impossible de débannir le joueur "{}" !',
    br: 'Não foi possível desbanir o jogador "{}"!',
  },
  [LOCALE.CHAT_ADMIN_MUTE_ERR]: {
    en: 'Could not mute player "{}"!',
    cz: 'Nepodařilo se ztlumit hráče "{}"!',
    zh: '无法将玩家 "{}" 禁言！',
    ru: 'Не удалось замутить игрока "{}"!',
    fr: 'Impossible de rendre muet le joueur "{}" !',
    br: 'Não foi possível silenciar o jogador "{}"!',
  },
  [LOCALE.CHAT_ADMIN_UNMUTE_ERR]: {
    en: 'Could not unmute player "{}"!',
    cz: 'Nepodařilo se odtlumit hráče "{}"!',
    zh: '无法取消静音玩家 "{}"！',
    ru: 'Не удалось размутить игрока "{}"!',
    fr: 'Impossible de réactiver le son du joueur "{}" !',
    br: 'Não foi possível desmutar o jogador "{}"!',
  },
  [LOCALE.CHAT_ADMIN_KICK_ERR]: {
    en: 'Could not kick player "{}"!',
    cz: 'Nepodařilo se vyhodit hráče "{}"!',
    zh: '无法踢出玩家 "{}"！',
    ru: 'Не удалось кикнуть игрока "{}"!',
    fr: 'Impossible de kicker le joueur "{}" !',
    br: 'Não foi possível expulsar o jogador "{}"!',
  },
  [LOCALE.CHAT_ADMIN_RENAME_ERR]: {
    en: 'Could not give player {} a rename!',
    cz: 'Nepodařilo se změnit jméno hráče {}!',
    zh: '无法给玩家 {} 重命名！',
    ru: 'Не удалось изменить имя игрока {}!',
    fr: 'Impossible de donner à {} un nouveau nom !',
    br: 'Não foi possível dar um novo nome para o jogador {}!',
  },
  [LOCALE.CHAT_ADMIN_FORCE_RENAME_ERR]: {
    en: 'Could not force rename player {} to {}!',
    cz: 'Nepodařilo se přejmenovat hráče {} na {}!',
    zh: '无法强制将玩家 {} 重命名为 {}！',
    ru: 'Не удалось принудительно изменить имя игрока {} на {}!',
    fr: 'Impossible de renommer de force le joueur {} en {} !',
    br: 'Não foi possível renomear o jogador {} para {}!',
  },
  [LOCALE.CHAT_ADMIN_BAN_IP_ERR]: {
    en: 'Could not ban ip "{}"!',
    cz: 'Nepodařilo se zabanovat ip "{}"!',
    ru: 'Не удалось забанить ip "{}"!',
  },
  [LOCALE.CHAT_ADMIN_UNBAN_IP_ERR]: {
    en: 'Could not unban ip "{}"!',
    cz: 'Nepodařilo se odbanovat ip "{}"!',
    ru: 'Не удалось разбанить ip "{}"!',
  },
  [LOCALE.CHAT_ADMIN_BAN_PLAYER_ERR]: {
    en: 'Could not ban player "{}"!',
    cz: 'Nepodařilo se zabanovat hráče "{}"!',
    ru: 'Не удалось забанить игрока "{}"!',
  },
  [LOCALE.CHAT_ADMIN_UNBAN_PLAYER_ERR]: {
    en: 'Could not unban player "{}"!',
    cz: 'Nepodařilo se odbanovat hráče "{}"!',
    ru: 'Не удалось разбанить игрока "{}"!',
  },
  [LOCALE.CHAT_ADMIN_MUTE_ERR]: {
    en: 'Could not mute player "{}"!',
    cz: 'Nepodařilo se ztlumit hráče "{}"!',
    ru: 'Не удалось замутить игрока "{}"!',
  },
  [LOCALE.CHAT_ADMIN_UNMUTE_ERR]: {
    en: 'Could not unmute player "{}"!',
    cz: 'Nepodařilo se odtlumit hráče "{}"!',
    ru: 'Не удалось размутить игрока "{}"!',
  },
  [LOCALE.CHAT_ADMIN_KICK_ERR]: {
    en: 'Could not kick player "{}"!',
    cz: 'Nepodařilo se vyhodit hráče "{}"!',
    ru: 'Не удалось кикнуть игрока "{}"!',
  },
  [LOCALE.CHAT_ADMIN_RENAME_ERR]: {
    en: 'Could not give player {} a rename!',
    ru: 'Не удалось изменить имя игрока {}!',
  },
  [LOCALE.CHAT_ADMIN_FORCE_RENAME_ERR]: {
    en: 'Could not force rename player {} to {}!',
    ru: 'Не удалось принудительно изменить имя игрока {} на {}!',
  },
  [LOCALE.POPUP_AUTOBUY_TURNOFF]: {
    en: 'You cannot buy items while Auto-Buy is enabled! You can turn off Auto-Buy by disabling it in Settings.',
    ru: 'Вы не можете покупать предметы, пока активна автоматическая покупка предметов. Вы можете отключить её в настройках.',
    br: 'Você não pode comprar itens com o recurso de compra automática ativado. Você pode desativá-lo nas configurações',
    cz: 'Nemáte povoleno nakupovat zboží s funkcí autokoupě. Můžete ji vypnout v nastavení',
    zh: '您不允许使用自动购买功能购买物品。您可以在设置中关闭它',
    fr: "Vous ne pouvez pas acheter d'articles tant que l'achat automatique est activé ! Vous pouvez le désactiver dans les paramètres.",
  },
  [LOCALE.ACTIVE]: {
    en: 'Active',
    ru: 'Активно',
    br: 'Ativo',
    cz: 'Aktivní',
    zh: '活动',
    fr: 'Actif',
  },
  [LOCALE.CZ]: {
    en: 'Czech',
    cz: 'Čeština',
    zh: '捷克语',
    ru: 'Чешский',
    fr: 'Tchèque',
    br: 'Tcheco',
  },
  [LOCALE.ZH]: {
    en: 'Chinese',
    cz: 'Čínština',
    zh: '中文',
    ru: 'Китайский',
    fr: 'Chinois',
    br: 'Chinês',
  },
  [LOCALE.RU]: {
    en: 'Russian',
    cz: 'Ruština',
    zh: '俄语',
    ru: 'Русский',
    fr: 'Russe',
    br: 'Russo',
  },
  [LOCALE.FR]: {
    en: 'French',
    cz: 'Francouzština',
    zh: '法语',
    ru: 'Французский',
    fr: 'Français',
    br: 'Francês',
  },
  [LOCALE.BR]: {
    en: 'Brazilian Portuguese',
    cz: 'Brazilská portugalština',
    zh: '巴西葡萄牙语',
    ru: 'Бразильский португальский',
    fr: 'Portugais brésilien',
    br: 'Português brasileiro',
  },
  [LOCALE.PASSIVE]: {
    en: 'Passive',
    ru: 'Пассивно',
    br: 'Passivo',
    cz: 'Pasivní',
    zh: '被动',
    fr: 'PASSIF',
  },
  [LOCALE.WATCH_AD_BUTTON]: {
    en: 'Watch Ad and get reward',
    ru: 'Посмотреть рекламу и получить награду',
    cz: 'Sledujte reklamu a získejte odměnu',
    zh: '观看广告并获得奖励',
    fr: 'Regardez la publicité et obtenez une récompense',
    br: 'Assista ao anúncio e ganhe recompensa',
  },
  [LOCALE.WATCH_AD_DIALOG_ACTION_BUTTON]: {
    en: 'Yes! Watch AD',
    ru: 'Да! Посмотреть рекламу',
    cz: 'Ano! Sledujte reklamu',
    zh: '是的！观看广告',
    fr: 'Oui ! Regarder la publicité',
    br: 'Sim! Assista ao anúncio',
  },
  [LOCALE.WATCH_AD_DIALOG_TITLE]: {
    en: 'Do you want to watch an ad?',
    ru: 'Хотите посмотреть рекламу?',
    cz: 'Chcete sledovat reklamu?',
    zh: '您想观看广告吗？',
    fr: 'Voulez-vous regarder une publicité ?',
    br: 'Você quer assistir a um anúncio?',
  },
  [LOCALE.WATCH_AD_DIALOG_CONTEXT]: {
    en: 'You can watch AD only once per 10 minutes and you will get',
    ru: 'Вы можете смотреть рекламу только один раз в 10 минут и вы получите',
    cz: 'Reklamu můžete sledovat pouze jednou za 10 minut a dostanete',
    zh: '您每10分钟只能观看一次广告，您将获得',
    fr: "Vous ne pouvez regarder une publicité qu'une seule fois toutes les 10 minutes et vous obtiendrez",
    br: 'Você só pode assistir a um anúncio a cada 10 minutos e você receberá',
  },
  [LOCALE.JOIN_DISCORD_MODAL_TITLE]: {
    en: 'Join our Discord server!',
    ru: 'Присоединяйтесь к нашему серверу Discord!',
    cz: 'Připojte se k našemu serveru Discord!',
    zh: '加入我们的Discord服务器！',
    fr: 'Rejoignez notre serveur Discord !',
    br: 'Junte-se ao nosso servidor Discord!',
  },
  [LOCALE.JOIN_DISCORD_MODAL_CONTEXT]: {
    en: 'To get the latest news, updates, and communicate with other players!',
    ru: 'Чтобы получить последние новости, обновления и общаться с другими игроками!',
    cz: 'Abyste získali nejnovější zprávy, aktualizace a komunikovali s ostatními hráči!',
    zh: '获取最新消息、更新和与其他玩家交流！',
    fr: "Pour obtenir les dernières nouvelles, mises à jour et communiquer avec d'autres joueurs !",
    br: 'Para obter as últimas notícias, atualizações e se comunicar com outros jogadores!',
  },
  [LOCALE.JOIN_DISCORD_MODAL_ACTION_BUTTON]: {
    en: 'Join Discord',
    ru: 'Присоединиться к Discord',
    cz: 'Připojit se k Discord',
    zh: '加入Discord',
    fr: 'Rejoindre Discord',
    br: 'Entrar no Discord',
  },
  [LOCALE.SETTINGS_VERY_LOW]: {
    en: 'Very Low',
    ru: 'Очень низкий',
    cz: 'Velmi nízký',
    zh: '非常低',
    fr: 'Très bas',
    br: 'Muito baixo',
  },
  [LOCALE.SETTINGS_LOW]: {
    en: 'Low',
    ru: 'Низкий',
    cz: 'Nízký',
    zh: '低',
    fr: 'Faible',
    br: 'Baixo',
  },
  [LOCALE.SETTINGS_MEDIUM]: {
    en: 'Medium',
    ru: 'Средний',
    cz: 'Střední',
    zh: '中等',
    fr: 'Moyen',
    br: 'Médio',
  },
  [LOCALE.SETTINGS_HIGH]: {
    en: 'High',
    ru: 'Высокий',
    cz: 'Vysoký',
    zh: '高',
    fr: 'Élevé',
    br: 'Alto',
  },
  [LOCALE.SETTINGS_ULTRA]: {
    en: 'Ultra',
    ru: 'Ультра',
    cz: 'Ultra',
    zh: '超级',
    fr: 'Ultra',
    br: 'Ultra',
  },
  [LOCALE.QUICKCHAT]: {
    en: 'Open Quick Chat',
    ru: 'Открыть быстрые сообщения',
    cz: 'Otevřít rychlé zprávy',
    zh: '打开快速聊天',
    fr: 'Ouvrir le chat rapide',
    br: 'Abrir bate-papo rápido',
  },
  [LOCALE.ST_KEYBIND_QUICKCHAT_OPEN]: {
    en: 'Open Quick Chat',
    ru: 'Открыть быстрые сообщения',
    cz: 'Otevřít rychlé zprávy',
    zh: '打开快速聊天',
    fr: 'Ouvrir le chat rapide',
    br: 'Abrir bate-papo rápido',
  },
  [LOCALE.ST_KEYBIND_QUICKCHAT_MSG_1]: {
    en: 'Message 1',
    ru: 'Сообщение 1',
    cz: 'Zpráva 1',
    zh: '消息1',
    fr: 'Message 1',
    br: 'Mensagem 1',
  },
  [LOCALE.ST_KEYBIND_QUICKCHAT_MSG_2]: {
    en: 'Message 2',
    ru: 'Сообщение 2',
    cz: 'Zpráva 2',
    zh: '信息2',
    fr: 'Message 2',
    br: 'Mensagem 2',
  },
  [LOCALE.ST_KEYBIND_QUICKCHAT_MSG_3]: {
    en: 'Message 3',
    ru: 'Сообщение 3',
    cz: 'Zpráva 3',
    zh: '消息3',
    fr: 'Message 3',
    br: 'Mensagem 3',
  },
  [LOCALE.QUICKCHAT_GOOD_GAME]: {
    en: 'Good game!',
    ru: 'Хорошая игра!',
    cz: 'Dobrá hra!',
    zh: '好游戏！',
    fr: 'Bon jeu !',
    br: 'Bom jogo!',
  },
  [LOCALE.QUICKCHAT_WELL_PLAYED]: {
    en: 'Well played!',
    ru: 'Хорошо сыграно!',
    cz: 'Dobře zahráno!',
    zh: '打得好！',
    fr: 'Bien joué !',
    br: 'Bem jogado!',
  },
  [LOCALE.QUICKCHAT_GOLD]: {
    en: 'I have {gold} gold.',
    ru: 'У меня {gold} золота.',
    cz: 'Mám {gold} zlata.',
    zh: '我有{gold}金币。',
    fr: "J'ai {gold} pièces d'or.",
    br: 'Eu tenho {gold} ouro.',
  },
  [LOCALE.QUICKCHAT]: {
    en: 'Open Quick Chat',
    ru: 'Открыть быстрые сообщения',
    cz: 'Otevřít rychlé zprávy',
    zh: '打开快速聊天',
    fr: 'Ouvrir le chat rapide',
    br: 'Abrir bate-papo rápido',
  },
  [LOCALE.ST_KEYBIND_QUICKCHAT_OPEN]: {
    en: 'Open Quick Chat',
    ru: 'Открыть быстрые сообщения',
    cz: 'Otevřít rychlé zprávy',
    zh: '打开快速聊天',
    fr: 'Ouvrir le chat rapide',
    br: 'Abrir bate-papo rápido',
  },
  [LOCALE.ST_KEYBIND_QUICKCHAT_MSG_1]: {
    en: 'Message 1',
    ru: 'Сообщение 1',
    cz: 'Zpráva 1',
    zh: '消息1',
    fr: 'Message 1',
    br: 'Mensagem 1',
  },
  [LOCALE.ST_KEYBIND_QUICKCHAT_MSG_2]: {
    en: 'Message 2',
    ru: 'Сообщение 2',
    cz: 'Zpráva 2',
    zh: '消息2',
    fr: 'Message 2',
    br: 'Mensagem 2',
  },
  [LOCALE.ST_KEYBIND_QUICKCHAT_MSG_3]: {
    en: 'Message 3',
    ru: 'Сообщение 3',
    cz: 'Zpráva 3',
    zh: '消息3',
    fr: 'Message 3',
    br: 'Mensagem 3',
  },
  [LOCALE.ST_KEYBIND_QUICKCHAT_MSG_4]: {
    en: 'Message 4',
    ru: 'Сообщение 4',
    cz: 'Zpráva 4',
    zh: '消息4',
    fr: 'Message 4',
    br: 'Mensagem 4',
  },
  [LOCALE.ST_KEYBIND_QUICKCHAT_MSG_5]: {
    en: 'Message 5',
    ru: 'Сообщение 5',
    cz: 'Zpráva 5',
    zh: '消息5',
    fr: 'Message 5',
    br: 'Mensagem 5',
  },

  [LOCALE.QUICKCHAT_GOOD_GAME]: {
    en: 'Good game!',
    ru: 'Хорошая игра!',
    cz: 'Dobrá hra!',
    zh: '好游戏！',
    fr: 'Bon jeu !',
    br: 'Bom jogo!',
  },
  [LOCALE.QUICKCHAT_WELL_PLAYED]: {
    en: 'Well played!',
    ru: 'Хорошо сыграно!',
    cz: 'Dobře zahráno!',
    zh: '打得好！',
    fr: 'Bien joué !',
    br: 'Bem jogado!',
  },
  [LOCALE.QUICKCHAT_GOLD]: {
    en: 'I have {gold} gold.',
    ru: 'У меня {gold} золота.',
    cz: 'Mám {gold} zlata.',
    zh: '我有{gold}金币。',
    fr: "J'ai {gold} pièces d'or.",
    br: 'Eu tenho {gold} ouro.',
  },
  [LOCALE.QUICKCHAT_SPELL_K_CD]: {
    en: 'My K has {SPELL_K_CD} seconds left on cooldown.',
    ru: 'У меня {SPELL_K_CD} секунд осталось до перезарядки К.',
    cz: 'Můj K má {SPELL_K_CD} sekund do konce cooldownu.',
    zh: '我的K技能还有{SPELL_K_CD}秒冷却时间。',
    fr: 'Mon K a {SPELL_K_CD} secondes de recharge restantes.',
    br: 'Meu K tem {SPELL_K_CD} segundos restantes no tempo de recarga.',
  },
  [LOCALE.QUICKCHAT_SPELL_K_READY]: {
    en: 'My K is ready.',
    ru: 'Мой К готов.',
    cz: 'Můj K je připraven.',
    zh: '我的K技能已准备好。',
    fr: 'Mon K est prêt.',
    br: 'Meu K está pronto.',
  },
  [LOCALE.QUICKCHAT_SPELL_L_CD]: {
    en: 'My L has {SPELL_L_CD} seconds left on cooldown.',
    ru: 'У меня {SPELL_L_CD} секунд осталось до перезарядки Л.',
    cz: 'Můj L má {SPELL_L_CD} sekund do konce cooldownu.',
    zh: '我的L技能还有{SPELL_L_CD}秒冷却时间。',
    fr: 'Mon L a {SPELL_L_CD} secondes de recharge restantes.',
    br: 'Meu L tem {SPELL_L_CD} segundos restantes no tempo de recarga.',
  },
  [LOCALE.QUICKCHAT_SPELL_L_READY]: {
    en: 'My L is ready.',
    ru: 'Мой Л готов.',
    cz: 'Můj L je připraven.',
    zh: '我的L技能已准备好。',
    fr: 'Mon L est prêt.',
    br: 'Meu L está pronto.',
  },
  [LOCALE.MMR_CHANGE]: {
    en: 'MMR Change',
    ru: 'Изменение MMR',
    cz: 'Změna MMR',
    zh: 'MMR变化',
    fr: 'Changement de MMR',
    br: 'Mudança de MMR',
  },
}
export default locale_data
